### ISSUE TITLE
Add unit test for RECENT_DATE

### ISSUE THREAD

**Issue by SethMichaelLarson** [shazow/urllib3#1005]
I've got a feeling this value could be easily forgotten to be updated over time. Could we perhaps add a unit test that will fail if it gets to be too far away from the current date.  It seems like it was last modified in mid 2014 but wasn't updated since then, should this value be updated now?

Link to the blame: https://github.com/shazow/urllib3/blame/master/urllib3/connection.py#L59
##

**Comment by Lukasa** [comment]
We should probably consider updating this sometime soon, yeah. Might be worth having a unit test.

**Comment by SethMichaelLarson** [comment]
Perhaps having a maximum distance from the current date of 2 years?  Also, should I update it to 2015 perhaps? I can submit a PR for this if that's what's wanted.

**Comment by haikuginger** [comment]
Why don't we just determine it programmatically during the test? :trollface:
