### ISSUE TITLE
Activate codecov for urllib3

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#1007]
What do I need to do?

I signed in and added the webhook, anything else?

[![codecov](https://codecov.io/gh/shazow/urllib3/branch/master/graph/badge.svg)](https://codecov.io/gh/shazow/urllib3)
##

**Comment by Lukasa** [comment]
I suspect that's it, though if you'd like us to add the badge lemme know.

**Comment by shazow** [comment]
Suuure. :)

**Comment by SethMichaelLarson** [comment]
We work so hard for 100% coverage might as well show it off. ;)

**Comment by Lukasa** [comment]
Oh, @shazow, can we make codecov a required status?

**Comment by shazow** [comment]
@Lukasa How does one do that?

**Comment by shazow** [comment]
I think it might be a codecov yaml config thing?

**Comment by sigmavirus24** [comment]
You have to go to the repository settings, protected branches, and turn it on there I think?

**Comment by SethMichaelLarson** [comment]
@Sigmavirus24 is correct it's in repo settings

**Comment by shazow** [comment]
<img width="999" alt="screen shot 2016-10-24 at 1 08 12 pm" src="https://cloud.githubusercontent.com/assets/6292/19655705/f2ad28de-99ea-11e6-9aa3-1e59729956f4.png">

---

<img width="992" alt="screen shot 2016-10-24 at 1 08 30 pm" src="https://cloud.githubusercontent.com/assets/6292/19655719/05987cfa-99eb-11e6-9105-e6a28435ed85.png">

---

<img width="1000" alt="screen shot 2016-10-24 at 1 08 37 pm" src="https://cloud.githubusercontent.com/assets/6292/19655721/05a12058-99eb-11e6-92f4-1546a666374b.png">

---

<img width="314" alt="screen shot 2016-10-24 at 1 08 47 pm" src="https://cloud.githubusercontent.com/assets/6292/19655720/059d4460-99eb-11e6-94a2-ac6b387c0e08.png">

**Comment by Lukasa** [comment]
We may need a new PR that actually fires the codecov commit status.

**Comment by SethMichaelLarson** [comment]
@Lukasa Yeah that is needed, I thought it would be on by default but I guess it's not. :/

**Comment by SethMichaelLarson** [comment]
This still needs to be done, now that a PR has been received it should show up in the Branch Protection section as an option. `Options -> Branches -> master [Edit] -> codecov (project) [Required]`

**Comment by Lukasa** [comment]
@shazow ^

**Comment by SethMichaelLarson** [comment]
:tada:
