### ISSUE TITLE
question: default ssl configuration difference between linux distros

### ISSUE THREAD

**Issue by TomasTomecek** [shazow/urllib3#1020]
Hello gentlemen. I'm kind of stuck on a SSL/TLS issue and would appreciate some feedback from professionals. Here it is:

we have [this test case](https://github.com/docker/docker-py/blob/8bf5be6455c43ba57bdc2a2e48a22ba99afd49ff/tests/unit/ssladapter_test.py#L23) in docker-py which I'm assuming ensures that the client uses safe TLS:

```python
try:
    import requests.packages.urllib3 as urllib3
except ImportError:
    import urllib3

ssl_context = urllib3.util.ssl_.create_urllib3_context()

assert ssl_context.options & OP_NO_SSLv3
assert ssl_context.options & OP_NO_SSLv2
assert not ssl_context.options & OP_NO_TLSv1
```

This works in upstream just fine. But in Fedora this started to fail in rawhide (spin with latest upstream packages). Bear in mind, that we try to [unbundle](http://pkgs.fedoraproject.org/cgit/rpms/python-requests.git/tree/python-requests.spec#n105) as much as possible in Fedora, so requests is using upstream urllib3, not the bundled one.

And that's where my knowledge ends. This is [the test failure](https://github.com/docker/docker-py/issues/1265 ):

```
tests/unit/ssladapter_test.py:27: in test_only_uses_tls
    assert ssl_context.options & OP_NO_SSLv2
E   AssertionError: assert (2181170175L & 0)
E    +  where 2181170175L = <ssl.SSLContext object at 0x3ffa4cbdde8>.options
```

I have these packages installed:
```
compat-openssl10-1.0.2j-5.fc26.x86_64
openssl-libs-1.1.0b-3.fc26.x86_64
openssl-1.1.0b-3.fc26.x86_64
python3-urllib3-1.16-3.fc26.noarch
python2-urllib3-1.16-3.fc26.noarch
```

I can easily reproduce (python 3, same is happening with python 2)

```python
In [1]: import urllib3

In [2]: c = urllib3.util.ssl_.create_urllib3_context()

In [3]: c.options
Out[3]: 2181170175

In [4]: c.options & ssl.OP_NO_SSLv3
Out[4]: 33554432  # good

In [5]: c.options & ssl.OP_NO_SSLv2
Out[5]: 0  # bad

In [6]: c.options & ssl.OP_NO_TLSv1
Out[6]: 0  # good?
```

The question: should we explicitly pass to `create_urllib3_context` that we want TLS?

**Comment by Lukasa** [comment]
In the first instance, problems with distro-provided packages should be referred to that distribution. Given that we didn't ship the code, the first job of the distribution is to work out if their own packages have broken the code.

In this instance, it should be noted that it may not be possible to pass OP_NO_SSLv2 to the context in question. Fedora Rawhide's OpenSSL may literally have no SSLv2 support compiled into it (it may have been compiled with `no-ssl2`). You should investigate the output of `openssl version -a`.

**Comment by TomasTomecek** [comment]
@Lukasa you're the man! The issue was that openssl was compiled without ssl2 support. Hence `OP_NO_SSLv2` was set to 0. Thank you very much!

**Comment by Lukasa** [comment]
=D No problem. Happy to help!
