### ISSUE TITLE
Broken link in AppEnginePlatformWarning

### ISSUE THREAD

**Issue by znorris** [shazow/urllib3#1027]
The [AppEnginePlatformWarning](https://github.com/shazow/urllib3/blob/8ca014adde2c005ccee07c150a18d853d27b26a2/urllib3/contrib/appengine.py#L114) link is currently [broken](https://urllib3.readthedocs.io/en/latest/contrib.html). Should be: http://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html

**Comment by Lukasa** [comment]
Yup, looks wrong to me, want to file a PR to fix it?

**Comment by SethMichaelLarson** [comment]
Can be closed? :)
