### ISSUE TITLE
Unexpected HostChangedError due to downcasing of hostname

### ISSUE THREAD

**Issue by NickMolloy** [shazow/urllib3#1032]
On version 1.19

```urllib3.exceptions.HostChangedError``` is thrown when a pool is created for a host with uppercase letters, and then a request is made with url containing this hostname.
```python
from urllib3 import HTTPConnectionPool

pool = HTTPConnectionPool("Example.com")
response = pool.request('GET', "http://Example.com")
```

Gives:
```
Traceback (most recent call last):
  File "minimum.py", line 5, in <module>
    response = pool.request('GET', "http://Example.com")
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 549, in urlopen
    raise HostChangedError(self, url, retries)
urllib3.exceptions.HostChangedError: HTTPConnectionPool(host='Example.com', port=None): Tried to open a foreign host with url: http://Example.com
```

Is this the expected behavior, or should a ConnectionPools host also be downcased when doing is_same_host() ?

**Comment by haikuginger** [comment]
Hmmm. I don't think that this is necessarily _intended_ behavior, but I don't think it's necessarily incorrect either. Can I ask why you're specifically using ConnectionPool instead of PoolManager? In general, we'd suggest using the higher-level API to avoid issues like this.

**Comment by NickMolloy** [comment]
I'm not sure why I was using ConnectionPool, I will use PoolManager instead. I only noticed this in some old code after I upgraded urllib3 via pip.
As to whether this is the correct behavior, rfc952 declares that no distinction is made between upper and lower case.

**Comment by Lukasa** [comment]
So the biggest issue here is probably that we should forcibly lowercase the hostname in the base `ConnectionPool` class. I'd accept a patch that does that.

**Comment by SethMichaelLarson** [comment]
@Lukasa Is a blind `lower` call appropriate? I thought that function was too smart for it's own good with some non-ASCII characters.

**Comment by Lukasa** [comment]
urllib3 doesn't tolerate non-ascii characters so I don't really mind how smart it is. ;)

**Comment by SethMichaelLarson** [comment]
Ah okay nevermind. :)

**Comment by nateprewitt** [comment]
@SethMichaelLarson @NickMolloy are either of you planning on putting this together? If not, I've got some time to cobble this together.

**Comment by SethMichaelLarson** [comment]
I can add this change with some tests tonight, should be easy enough.
