### ISSUE TITLE
Support for certificate subject when using subjectAltName=IP Address is broken

### ISSUE THREAD

**Issue by fbouliane** [shazow/urllib3#1043]
Since I upgraded to Urllib3 v.1.19.1, Some certificate stopped to be valid. I realized that the code does not verify the subject of the certificate anymore if an IPAddress entry is present in the SubjectAltName when using the hostname to query.

Steps to reproduce
---

1. Setup a https host with a certificate with a CommonName in the subject and an IP address in the subjectAltName (without any DNSname)
2. Query the hostname of the host using this certificate.
    
Incorrect Behavior
---
    
The CommonName of the certificate will be ignored and the verification will fail

    [exec] requests.packages.urllib3.connection: ERROR: Certificate did not match expected hostname: $HOSTNAME. Certificate: {'subjectAltName': (('IP Address', '$IP'),), 'subject': ((('commonName', u'*.$DOMAIN'),),), 'notAfter': '$TIMESTAMP'}

My analysis
---

I think the issue was introduced with the [PR#922] which introduce the verification of IP Address in the SubjectAltName. [Following the logic introduced], If a IP Address is specified in the SubjectAltName, the code adds it to the dnsnames list, causing the CommonName of the certificate to be ignored.

I think the intended behavior is to support CommonName presemt in the Subject only if there is no DNSname entries in the SubjectAltName, whether or not there is an IpAddress is present.

[PR#922]: https://github.com/shazow/urllib3/pull/922/files
[Following the logic introduced]: https://github.com/shazow/urllib3/blob/master/urllib3/packages/ssl_match_hostname/_implementation.py#L132-L139

**Comment by Lukasa** [comment]
This behaviour is deliberate. If there are *any* entries in the subjectAltName field that we can validate on we totally disregard the commonName field. This is because commonName is being deprecated, and should be disregarded. 

We can validate appropriately if it's present in the subjectAlternativeName field by installing the `[secure]` extra: `pip install urllib3[secure]`.

**Comment by fbouliane** [comment]
Thanks for taking the time to reply.

BTW, For further readers I found the RFC 6125 that supports your decision.

    As noted, a client MUST NOT seek a match for a reference identifier
    of CN-ID if the presented identifiers include a DNS-ID, SRV-ID,
    URI-ID, or any application-specific identifier types supported by the
    client.

https://tools.ietf.org/html/rfc6125#section-6.4.4
