### ISSUE TITLE
Old "cryptography" package causes crash

### ISSUE THREAD

**Issue by aseering** [shazow/urllib3#1044]
Cross-posting this from kennethreitz/requests#3714 ; folks there seemed to think that this would be best addressed within urllib3:

As of `requests==2.12.1` \[EDIT: and whatever version of urllib3 it embeds\], `requests[security]` depends on `cryptography>=1.3.4`.  That's fine.  However, `requests` (without `[security]`) crashes if `cryptography==1.0.2` is installed.  This is a perfectly valid configuration of packages according to `pip`; as a user, I would expect it to behave as if I had not specified `[security]` (because I didn't specify it).

The specific failure is discussed a bit more here:

http://discuss.flexget.com/t/unhandled-error-in-plugin-configure-series-solved/2900

The crash was resolved, also as described at the above link, by running:

```
pip install --upgrade cryptography
```

Uninstalling `cryptography` would probably have worked fine too.

The crash appears to be caused because `requests` internally tests for `[security]` by importing a thing which imports its bundled `pyopenssl` which imports `cryptography`; if that succeeds, the extra is used.  But with a too-old version of `cryptography`, it imports just fine but it constructs objects that are missing required fields.

I can think of a couple approaches here:

* Catch this failure and print an error message that more-helpfully explains that your `cryptography` package needs updating
* Validate the version/functionality of the `cryptography`package more carefully, and don't enable the `[security]` extra's features if an old version happens to be installed

I'd be happy to post a PR for either approach.  Right now I'm looking for feedback on whether it's worth addressing this (I'd certainly appreciate it) and on what approach you'd prefer.

**Comment by Lukasa** [comment]
Hi again!

So, urllib3 *also* has an appropriate extra that *also* enforces this constraint, so we want to worry about it here too. I think we need to adjust `inject_into_urllib3` to do some feature detection. I'd be happy to review a pull request that adds this kind of checking.

**Comment by Lukasa** [comment]
Resolved in #1045.
