### ISSUE TITLE
Necessary to cleanup DefaultSelector in def _wait_for_io_events() ?

### ISSUE THREAD

**Issue by aniapte** [shazow/urllib3#1046]
Hello,

We are hitting the error "filedescriptor out of range in select()"  when creating too many new connections. We are using urllib3 as a part of requests. In order to get around it we are waiting for https://github.com/shazow/urllib3/pull/1001 to get released. The questions I have are:

1. When will https://github.com/shazow/urllib3/pull/1001 be released as part of a new urllib3 release?
2. I was looking at the patch and was wondering if any cleanup is required for the DefaultSelector() object that is created in the util._wait_for_io_events() function. See https://github.com/shazow/urllib3/blob/master/urllib3/util/wait.py#L22. The epoll selector class does have the close() method where it closes the platform epoll object - but is the close() called from anywhere?

regards,
aniruddha

**Comment by Lukasa** [comment]
1. As it's been merged, it'll be part of the next release. There is no schedule for that release, though. Such a release also has to propagate into requests, which can usually mean a wait time of around 3 months.

2. Yeah, probably that should use the selector like a context manager. The explicit cleanup isn't entirely necessary, the gc will eventually get everything, but there's no reason not to use a context manager here. I'll welcome a patch for this. /cc @SethMichaelLarson

**Comment by SethMichaelLarson** [comment]
I'm on it!
