### ISSUE TITLE
Read timeout causes retry despite HTTP method used

### ISSUE THREAD

**Issue by alexdias** [shazow/urllib3#1059]
Hello,

We've encountered an issue in which a read timeout will always cause a retry (unless the *read* parameter to the *Retry* class is set to 0), no matter what HTTP method is used to perform the request. Part of the code path that is followed seems to be https://github.com/shazow/urllib3/blob/7002c1347c677b2743244bf36bd05aa3625f57f1/urllib3/connectionpool.py#L642.
To give more context, we're encountering retries on POST requests (which are not indempotent) when a server's response time causes a read timeout.

Is this known behaviour? We were expecting the *method_whitelist* parameter to apply to any type of errors.

Thanks.

**Comment by Lukasa** [comment]
Yup. It looks like this was simply not put in place, or a refactor broke it at some point.

Anyone who would like to can undertake fixing it.

**Comment by alexdias** [comment]
Thanks Cory, I'll see if I can submit a patch in the next few days.

**Comment by posener** [comment]
@Lukasa , hello, seems like read error also ignores the retry method_whitelist attribute. is it intentional?

**Comment by Lukasa** [comment]
@posener I suspect it's the exact same as the timeout problem discussed in this issue: it just got lost.

**Comment by posener** [comment]
Great, @alexdias, are you going to fix this too? Need some help here?
Cheers,
Eyal

**Comment by alexdias** [comment]
@posener Hi Eyal, I've only done the read timeout thus far but I can do the read error tomorrow. Thanks!

**Comment by posener** [comment]
@alexdias , Hi, Just to be clear,
I'm also talking about the read timeout error,
The thing is, that, for example if we currently get a read timeout on a POST method, and the POST method is not in the `method_whitelist`, the retry still make another attempt.
My sense tells that it shouldn't. at least that is what the api that the object exposes suggests.

MANY THANKS!

**Comment by alexdias** [comment]
@posener Ah yes, that is the exact thing I am fixing :)

**Comment by Lukasa** [comment]
Resolved by #1066.
