### ISSUE TITLE
localhost DNS resolution problem in tests with misconfigured /etc/hosts

### ISSUE THREAD

**Issue by ncoghlan** [shazow/urllib3#1070]
[After further investigation, I figured out the problem here was either an old or just plain misconfigured `/etc/hosts`, but decided it made the most sense to submit the issue anyway and then immediately close it, in case someone else runs into a similar problem]

Running the tests on Fedora 25, I found an interesting failure case for the "Does an IPv6 local loopback actually work?" checks in the DummyServer implementation. Specifically (the port number below comes from starting a SocketDummyServerTestCase test case in an interactive Python shell):

```
$ netstat -tl | grep 37677
tcp6       0      0 localhost6.locald:37677 [::]:*                  LISTEN
$ ping localhost -c 1
PING localhost.localdomain (127.0.0.1) 56(84) bytes of data.
...
$ ping localhost6 -c 1
PING localhost6(localhost6.localdomain6 (::1)) 56 data bytes
```

What appeared to be happening was that `socket.bind()` accepted `"localhost"` as a valid interface name to bind to, so the dummy server code at https://github.com/shazow/urllib3/blob/master/dummyserver/server.py#L53 sets `HAS_IPV6_AND_DNS` and binds to `::1`, but when the client tries to *resolve* `"localhost"` it gets handed `127.0.0.1`, which then doesn't work.

Using Charles-François's queries from https://bugs.python.org/issue18792 I saw:

```
>>> for addr in socket.getaddrinfo("localhost", 0): print(addr)
... 
(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))
(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0))
(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 0))
>>> for addr in socket.getaddrinfo("localhost6", 0): print(addr)
... 
(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0))
(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('::1', 0, 0, 0))
(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_RAW: 3>, 0, '', ('::1', 0, 0, 0))
```

Which sounded a lot like the problems discussed in https://github.com/shazow/urllib3/pull/611

However checking a fresh Fedora container image suggests that the expectation is for `localhost` to be used for both IPv4 and IPv6, and my local workstation just has some old config settings lying around:

```
$ docker run --rm fedora:25 cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      3fe6f8fb4bb1
```

So I edited `/etc/hosts` to also list `localhost` on the `::1` line and the test issue went away.

**Comment by ncoghlan** [comment]
Turns out the test issues *mostly* went away. I still see the following error under 2.7:

```
FAIL: test_source_address (test.with_dummyserver.test_connectionpool.TestConnectionPool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ncoghlan/devel/urllib3/test/with_dummyserver/test_connectionpool.py", line 631, in test_source_address
    self.assertEqual(r.data, b(addr[0]))
AssertionError: '::1' != '127.0.0.1'
```

**Comment by Lukasa** [comment]
I suspect that behaviour is going to be related to wacky problems regarding the socket module, and is unlikely to be enormously important. =)
