### ISSUE TITLE
If the response is complete, stream/read_chunked should short-circuit return the empty string.

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#1088]
Originally seen in kennethreitz/requests#3807.

Basically, read_chunked should check whether `_fp` is `None`. If it is, it should immediately return the empty byte string rather than do any processing.

Put another way, this shouldn't blow up:

```python
import urllib3

http = urllib3.PoolManager()
resp = http.request('GET', 'http://http2bin.org/stream/100')
resp.read()
next(resp.read_chunked())
```

I recommend someone who wants to help out pick this issue up, it should be easily fixed and tested.

**Comment by nateprewitt** [comment]
I believe we already check that `_fp` isn't None [here](https://github.com/shazow/urllib3/blob/master/urllib3/response.py#L518-L525), right? I think the actual issue is we're not checking that `_fp.fp` isn't None which signals the connection has been closed (and hopefully read).

**Comment by Lukasa** [comment]
Can we not just ask the fp directly whether it's closed?

**Comment by nateprewitt** [comment]
@Lukasa, yeah, it looks like `closed` on the Response object will correctly check this for us.

**Comment by jschneier** [comment]
I was about to go and fix this -- shouldn't we just `return` so that `StopIteration` is raised instead of returning `b''`?

**Comment by zefoo** [comment]
Any updates on this? I'm getting a ton of these in a recent project. Thank you!
