### ISSUE TITLE
Running urllib3 tests on windows platform

### ISSUE THREAD

**Issue by lorien** [shazow/urllib3#1090]
Hello Andrey,
Recently I have been working on integration tests of one of my projects with appveyor service (windows-based continuous integration service).
I can write and debug appveyor.yml config file so you be able to run tests on appveyor service.
Let me know if you are interested. Thanks.

**Comment by Lukasa** [comment]
@lorien Thanks for the suggestion! However, we have an open PR to do just that: see #1006.
