### ISSUE TITLE
Missing response headers when malformed header is part of the response

### ISSUE THREAD

**Issue by gboudreau** [shazow/urllib3#1110]
Python 3.5, urllib3 1.20

```
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'https://online.chasecanada.ca/ChaseCanada_Consumer/Login.do')
>>> r.status
200
>>> r.headers
HTTPHeaderDict({'Date': 'Sat, 04 Feb 2017 20:09:21 GMT'})
>>>
```

I'm pretty sure the problem is caused by an invalid HTTP header returned by the server:

    HTTP/1.1 200 OK
    Date: Sat, 04 Feb 2017 19:16:34 GMT
    My Param: None
    [...]

It directly follows the Date response header, which is returned fine, but since no other response headers is returned, I think this broken header is breaking the HTTP response headers parser.

Of note: the `http.client.HTTPresponse.headers` object (`HTTPMessage`) shows all headers in `_payload`, but only the `Date` header in `_headers`.

**Comment by SethMichaelLarson** [comment]
Pretty sure that spaces aren't allowed in HTTP header field names. Whatever server they're using it's not compliant. :/

**Comment by sigmavirus24** [comment]
So this is a problem with `http.client` and the object it uses to parse headers. Instead of skipping invalid headers (@SethMichaelLarson is correct that the `My Param:` header is invalid) it stops parsing all headers. There's also little urllib3 can do except move off of `http.client`, which, is underway for urllib3 2.0.

**Comment by gboudreau** [comment]
I filed an issue in the Python tracker (http://bugs.python.org/issue29445), and was pointed to a possible duplicate (http://bugs.python.org/issue24363).
Testing the latest patch attached to 24363, I can confirm this resolves my issue. Hopefully, this gets  merged soon, but until then, I least I can manually apply the patch where I need it.
