### ISSUE TITLE
urllib3 cannot build against LibreSSL

### ISSUE THREAD

**Issue by mrobbetts** [shazow/urllib3#1113]
I'm using NixOS, and having the following issue:
https://github.com/NixOS/nixpkgs/issues/22616

It seems that, at least in its default configuration, urllib3 requires SSLv3 -- but libreSSL doesn't provide it. Is there a way to use urllib3 with libreSSL?

**Comment by Lukasa** [comment]
Your test failures are benign: they just test a few weird functions. They're a pain though: they do require certain OpenSSL configurations that aren't guaranteed. 

So there is no particular issue here: you should find that the actual code runs ok, and just those tests misbehave. I'll open a new issue to track that problem, and please reopen this if you find there are other ongoin issues.
