### ISSUE TITLE
urllib3 1.20 test failures in test/contrib/test_socks.py

### ISSUE THREAD

**Issue by wizeman** [shazow/urllib3#1120]
Hi,

When trying to upgrade urllib3 to version 1.20, I'm getting a bunch of test failures in `test.contrib.test_socks.TestSOCKS4Proxy` and `test.contrib.test_socks.TestSocks5Proxy`. The full log is here: https://gist.github.com/wizeman/a362f0f1e1c9364e1197801ca6c70326

As you can see, I'm using python 2.7.

What could be the cause?
I'm surprised you aren't getting these test errors, as it doesn't seem to be a transient failure (like a timeout or something similar).

**Comment by Lukasa** [comment]
Looks like your pysocks module is old. What version do you have installed?

**Comment by wizeman** [comment]
I'm using pysocks 1.5.0.

**Comment by Lukasa** [comment]
Our setup.py requires at least pysocks version 1.5.6.

**Comment by wizeman** [comment]
Indeed, after updating pysocks to version 1.6.6, the mentioned tests passed.

Thanks for such a quick response!

**Comment by Lukasa** [comment]
No problem at all. =)
