### ISSUE TITLE
status_forcelist specific retry counter

### ISSUE THREAD

**Issue by tuukkamustonen** [shazow/urllib3#1147]
`read`, `connect` and `redirect` have separate counters but poor `status_forcelist` only counts on `total`. Would it be possible to add similar counter for `status_forcelist`, e.g. `status=3`?

I may try to sketch something up, if this doesn't feel too stupid.

Use case: I want to all one retry for read/connect/status-retry, but if I do `Retry(total=3, connect=1, read=1, status_forcelist=[...])` then in case there is no connect or read error, status will be retried 3 times, unless I'm mistaken.

**Comment by Lukasa** [comment]
That sounds like a reasonable enhancement. I'd be happy to review a patch like that.

**Comment by tuukkamustonen** [comment]
This has been implemented. Closing.
