### ISSUE TITLE
1.21 fails to build

### ISSUE THREAD

**Issue by JayCeeJr** [shazow/urllib3#1155]
Collecting urllib3==1.2.1
  Downloading urllib3-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-DBcrHA/urllib3/setup.py", line 25, in <module>
        tests_requirements = requirements + open('test-requirements.txt').readlines()
    IOError: [Errno 2] No such file or directory: 'test-requirements.txt'

**Comment by Lukasa** [comment]
That's not 1.21, that's 1.2.1, which is *ancient*. Your pip command is wrong. ;)
