### ISSUE TITLE
TestHTTPS.test_ca_dir_verified skipped on Python 2.7.8 or older

### ISSUE THREAD

**Issue by SethMichaelLarson** [shazow/urllib3#1164]
[`TestHTTPS.test_ca_dir_verified`](https://github.com/shazow/urllib3/blob/master/test/with_dummyserver/test_https.py#L150) has the `@onlyPy279OrNewer` decorator to skip on Python 2.7.8 or older. However the test contains logic which checks the Python version and then does different verifications based on whether `sys.version` is greater or equal to `(2, 7, 9)`. See below:

```python
@onlyPy279OrNewer
@notSecureTransport
def test_ca_dir_verified(self):

    # ...

    if sys.version_info >= (2, 7, 9):
        self.assertFalse(warn.called, warn.call_args_list)
    else:  # <--- This branch is never taken?
        self.assertTrue(warn.called)
        call, = warn.call_args_list
        error = call[0][1]
        self.assertEqual(error, InsecurePlatformWarning)
```

Was it intentional to keep this branch?

The decorator for the test was added in commit https://github.com/shazow/urllib3/commit/e15ea73b23574b6f7ce5867d4f8d25aed2718b3f which came shortly after the test was created.

**Comment by Lukasa** [comment]
Hrm, probably not? Let's try removing it and see what happens. :wink:

**Comment by SethMichaelLarson** [comment]
My favorite way of debugging. :)
