### ISSUE TITLE
not fork safe on osx

### ISSUE THREAD

**Issue by gromgull** [shazow/urllib3#1179]
This is actually a OSX "feature", and not a urllib3 bug - but I sank a lot of time into debugging it, and maybe it could be detected and a warning could be logged, or at least it could be documented?

The underlying problem is that proxy settings are looked up using some system api, which in turn uses libdispatch, which is not fork-safe. This can lead to segfaults.

My bug report: http://bugs.python.org/issue30385 (with a smallish program to replicate consistently, with `requests`)

The still open python bug http://bugs.python.org/issue13829 

Is it worth adding some logic to check if we're on osx and requests were made one pid - then later with another pid? (I don't know if there is a better way to detect a fork) - and if so log a warning?

**Comment by haikuginger** [comment]
@gromgull, I wasn't able to reproduce using your sample script on macOS 10.12.4, pyenv-installed Python 3.6.1, and the following pip freeze:

```
requests==2.14.2
SQLAlchemy==1.1.10
tornado==4.5.1
```

Can you paste a pip freeze output? Additionally, if you could clarify the version of MacOS you're using, that'd be great - the upstream bug says "MacOS 16.4.0", which I'm pretty sure isn't right. 😉

I also wasn't able to reproduce the issue with the following code (which should exercise what seems to be the problematic codepath):

```python
for i in range(8):
	x = os.fork()
	if x:
		print(x)
		from urllib.request import proxy_bypass
		proxy_bypass('169.254.1.1')
		proxy_bypass('google.com')
```

Two further points.

First, based on the other user's stacktrace from the upstream ticket, it looks like the problematic call is being made inside requests, rather than in urllib3. If that's the case, kennethreitz/requests would be the appropriate place to open a bug.

Second, you mentioned upstream that you can only get this to happen if you include a couple (unused) Tornado imports. It sounds like those imports might be doing some patching, in which case it'd be harder to determine if this is within scope for us to handle. If we can get a reproduceable test case that includes Tornado, the next step would be to create a failure case using just the standard library and urllib3 (or requests, if applicable).

**Comment by Lukasa** [comment]
Yeah, I think we don't want to consider this a urllib3 bug. urllib3 does not support being actively initialized and then forked, and it can break urllib3 in a surprisingly large number of ways. Short of decorating every entry point into the codebase to do fork detection I don't think we've got a reasonable chance of spotting this. 😦

**Comment by MojoJojo** [comment]
I think I might be encountering a similar issue on Python 3.7.6 and Mac OS 10.15.2. I'm working with Apache airflow to move some data from an S3 bucket. Airflow uses Boto3 and Botocore to connect to S3. In Botocore `utils.py`(line 529) there is a call to `proxy_bypass` which is imported from `compat.py` which in turn resolves to `from urllib.request import parse_http_list, getproxies, proxy_bypass` in Python 3.
Upon hitting the above `proxy_bypass` call, the the thread crashes with the attached stack trace Mac Console for Python 3.7. I've repeated this several times and it crashes each time, no matter what the supplied hostname argument is.

However, if I copy and paste the code @haikuginger posted above, it works without issues. 

Output from pip freeze:

adal==1.2.2
alabaster==0.7.12
alembic==1.3.2
amqp==2.5.2
analytics-python==1.2.9
ansiwrap==0.8.4
apache-airflow==1.10.7
apispec==1.3.3
appnope==0.1.0
argcomplete==1.11.1
asn1crypto==1.3.0
aspy.yaml==1.3.0
astroid==2.3.3
atlasclient==1.0.0
attrs==19.3.0
aws-xray-sdk==0.95
azure-common==1.1.24
azure-cosmos==3.1.2
azure-datalake-store==0.0.48
azure-mgmt-containerinstance==1.5.0
azure-mgmt-resource==7.0.0
azure-nspkg==3.0.2
azure-storage==0.36.0
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
Babel==2.8.0
backcall==0.1.0
bcrypt==3.1.7
beautifulsoup4==4.7.1
billiard==3.6.1.0
bleach==3.1.0
blinker==1.4
boto==2.49.0
boto3==1.7.84
botocore==1.10.84
cached-property==1.5.1
cachetools==4.0.0
cassandra-driver==3.21.0
cattrs==0.9.0
celery==4.4.0
certifi==2019.11.28
cffi==1.13.2
cfgv==2.0.1
cgroupspy==0.1.6
chardet==3.0.4
click==6.7
cloudant==0.5.10
colorama==0.4.3
colorlog==4.0.2
configparser==3.5.3
cookies==2.2.1
coverage==5.0.3
croniter==0.3.31
cryptography==2.8
cx-Oracle==7.3.0
Cython==0.29.14
datadog==0.33.0
decorator==4.4.1
defusedxml==0.6.0
dill==0.3.1.1
dnspython==1.16.0
docker==3.7.3
docker-pycreds==0.4.0
docopt==0.6.2
docutils==0.16
dumb-init==1.2.2
ecdsa==0.15
elasticsearch==5.5.3
elasticsearch-dsl==5.4.0
entrypoints==0.3
fastavro==0.22.9
flake8==3.7.9
flake8-colors==0.1.6
flaky==3.6.1
Flask==1.1.1
Flask-Admin==1.5.4
Flask-AppBuilder==2.2.1
Flask-Babel==0.12.2
Flask-Bcrypt==0.7.1
Flask-Caching==1.3.3
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.1
flask-swagger==0.2.13
Flask-WTF==0.14.2
flower==0.9.3
freezegun==0.3.13
fsspec==0.6.2
funcsigs==1.0.2
future==0.16.0
future-fstrings==1.2.0
gcsfs==0.6.0
geomet==0.1.2
google-api-core==1.16.0
google-api-python-client==1.7.11
google-auth==1.10.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud-bigquery==1.23.1
google-cloud-bigtable==0.33.0
google-cloud-container==0.3.0
google-cloud-core==1.2.0
google-cloud-dlp==0.13.0
google-cloud-language==1.3.0
google-cloud-spanner==1.9.0
google-cloud-speech==1.3.1
google-cloud-storage==1.25.0
google-cloud-texttospeech==0.5.0
google-cloud-translate==2.0.0
google-cloud-videointelligence==1.12.1
google-cloud-vision==0.41.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
graphviz==0.13.2
grpc-google-iam-v1==0.12.3
grpcio==1.26.0
grpcio-gcp==0.2.2
gunicorn==19.10.0
hdfs==2.5.8
hmsclient==0.1.1
httplib2==0.16.0
identify==1.4.10
idna==2.8
ijson==2.5.1
imagesize==1.2.0
importlib-metadata==1.4.0
inflection==0.3.1
ipdb==0.12.3
ipython==7.11.1
ipython-genutils==0.2.0
iso8601==0.1.12
isodate==0.6.0
itsdangerous==1.1.0
JayDeBeApi==1.1.1
jedi==0.15.2
Jinja2==2.10.3
jira==2.0.0
jmespath==0.9.4
JPype1==0.7.1
json-merge-patch==0.2
jsondiff==1.1.1
jsonpickle==1.2
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
kombu==4.6.7
kubernetes==10.0.1
lazy-object-proxy==1.4.3
ldap3==2.6.1
lockfile==0.12.2
Mako==1.1.0
Markdown==2.6.11
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.5.1
marshmallow-sqlalchemy==0.21.0
mccabe==0.6.1
mistune==0.8.4
mock==3.0.5
mongomock==3.18.0
more-itertools==8.1.0
moto==1.3.5
msrest==0.6.10
msrestazure==0.6.2
multi-key-dict==2.0.3
mypy==0.720
mypy-extensions==0.4.3
mysqlclient==1.3.14
nbconvert==5.6.1
nbformat==5.0.3
nodeenv==1.3.4
nteract-scrapbook==0.3.1
ntlm-auth==1.4.0
numpy==1.18.1
oauthlib==3.1.0
oscrypto==1.2.0
packaging==20.0
pandas==0.25.3
pandas-gbq==0.13.0
pandocfilters==1.4.2
papermill==1.2.1
parameterized==0.7.1
paramiko==2.7.1
parso==0.5.2
pathspec==0.7.0
pbr==5.4.4
pendulum==1.4.4
pexpect==4.7.0
pickleshare==0.7.5
pinotdb==0.1.1
pluggy==0.13.1
pre-commit==1.21.0
prison==0.1.2
prompt-toolkit==3.0.2
protobuf==3.11.2
psutil==5.6.7
psycopg2-binary==2.8.4
ptyprocess==0.6.0
py==1.8.1
pyaml==19.12.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycparser==2.19
pycryptodome==3.9.4
pycryptodomex==3.9.4
pydata-google-auth==0.2.1
pydruid==0.5.8
pyflakes==2.1.1
Pygments==2.5.2
PyHive==0.6.1
PyJWT==1.7.1
pykerberos==1.2.1
pymongo==3.10.1
pymssql==2.1.4
PyNaCl==1.3.0
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.7
pysftp==0.2.9
PySmbClient==0.1.5
pytest==5.3.3
pytest-cov==2.8.1
python-daemon==2.1.2
python-dateutil==2.8.1
python-editor==1.0.4
python-http-client==3.2.1
python-jenkins==1.6.0
python-jose==2.0.2
python3-openid==3.1.0
pytz==2019.3
pytzdata==2019.3
pywinrm==0.4.1
PyYAML==5.3
pyzmq==18.1.1
qds-sdk==1.13.2
redis==3.3.11
requests==2.22.0
requests-futures==0.9.4
requests-kerberos==0.12.0
requests-mock==1.7.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
responses==0.10.9
rsa==4.0
s3transfer==0.1.13
sasl==0.2.1
sendgrid==5.6.0
sentinels==1.0.0
sentry-sdk==0.14.0
setproctitle==1.1.10
six==1.14.0
slackclient==1.3.2
snowballstemmer==2.0.0
snowflake-connector-python==2.1.3
snowflake-sqlalchemy==1.1.18
soupsieve==1.9.5
Sphinx==2.3.1
sphinx-argparse==0.2.5
sphinx-autoapi==1.0.0
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-dotnetdomain==0.4
sphinxcontrib-golangdomain==0.2.0.dev0
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-httpdomain==1.7.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
SQLAlchemy==1.3.12
SQLAlchemy-JSONField==0.9.0
SQLAlchemy-Utils==0.36.1
sshtunnel==0.1.5
tabulate==0.8.6
tenacity==4.12.0
termcolor==1.1.0
testpath==0.4.4
text-unidecode==1.2
textwrap3==0.9.2
thrift==0.13.0
thrift-sasl==0.3.0
toml==0.10.0
tornado==5.1.1
tqdm==4.41.1
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.1
tzlocal==1.5.1
unicodecsv==0.14.1
Unidecode==1.1.1
uritemplate==3.0.1
urllib3==1.25.7
vertica-python==0.10.1
vine==1.3.0
virtualenv==16.7.9
wcwidth==0.1.8
webencodings==0.5.1
websocket-client==0.54.0
Werkzeug==0.16.0
wrapt==1.11.2
WTForms==2.2.1
xmltodict==0.12.0
yamllint==1.20.0
zdesk==2.7.1
zipp==2.0.0
zope.deprecation==4.4.0

The only difference I could see at this point is that the test code above uses `os.fork` while Airflow's scheduler uses `subprocess.check_call(command, close_fds=True)`. Not sure if that makes a difference.  I will try and replicate this issues outside Airflow and see if I can post an updated.


[python3.7_2020-01-26-024825.log](https://github.com/urllib3/urllib3/files/4113060/python3.7_2020-01-26-024825.log)

**Comment by MojoJojo** [comment]
Confirmed same as @gromgull . Still open at https://bugs.python.org/issue13829.
