### ISSUE TITLE
requests/dev version of urllib3 don't play nice together in tox

### ISSUE THREAD

**Issue by alexwlchan** [shazow/urllib3#1182]
Working with a local clone of current master (ae4adde):

```console
$ tox -e docs
GLOB sdist-make: /Users/alexwlchan/repos/urllib3/setup.py
docs create: /Users/alexwlchan/repos/urllib3/.tox/docs
docs installdeps: -r/Users/alexwlchan/repos/urllib3/docs/requirements.txt
docs inst: /Users/alexwlchan/repos/urllib3/.tox/dist/urllib3-dev.zip
docs installed: alabaster==0.7.10,appdirs==1.4.3,asn1crypto==0.22.0,Babel==2.4.0,backports.ssl-match-hostname==3.5.0.1,certifi==2017.4.17,cffi==1.10.0,chardet==3.0.3,coverage==3.7.1,cryptography==1.8.2,docutils==0.13.1,enum34==1.1.6,funcsigs==1.0.2,idna==2.5,imagesize==0.7.1,ipaddress==1.0.18,Jinja2==2.9.6,MarkupSafe==1.0,mock==1.3.0,ndg-httpsclient==0.4.2,nose==1.3.7,nose-exclude==0.4.1,packaging==16.8,pbr==3.0.1,pkginfo==1.4.1,pluggy==0.3.1,psutil==4.3.1,py==1.4.33,pycparser==2.17,Pygments==2.2.0,pyOpenSSL==17.0.0,pyparsing==2.2.0,PySocks==1.5.6,pytz==2017.2,requests==2.16.5,six==1.10.0,snowballstemmer==1.2.1,Sphinx==1.6.2,sphinxcontrib-websupport==1.0.1,tornado==4.2.1,tox==2.1.1,twine==1.5.0,typing==3.6.1,urllib3===dev,virtualenv==15.1.0
docs runtests: PYTHONHASHSEED='3695751977'
docs runtests: commands[0] | rm -rf /Users/alexwlchan/repos/urllib3/docs/_build
docs runtests: commands[1] | make -C /Users/alexwlchan/repos/urllib3/docs html
sphinx-build -b html -d _build/doctrees  '-W' . _build/html
Running Sphinx v1.6.2
making output directory...

Exception occurred:
  File "/Users/alexwlchan/repos/urllib3/.tox/docs/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    major, minor, patch = urllib3_version
ValueError: need more than 1 value to unpack
The full traceback has been saved in /var/folders/jy/351n9lnj5l3f07rtf2xybxx00000gn/T/sphinx-err-dn6eJg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
ERROR: InvocationError: '/usr/bin/make -C /Users/alexwlchan/repos/urllib3/docs html'
________________________________________________________________________________ summary _________________________________________________________________________________
ERROR:   docs: commands failed
```

**Comment by Lukasa** [comment]
This seems like a problem with our tox installation, possibly the results of a dependency issue? Seems like it must be pretty recent given that it hasn't happened in CI. @jonparrott, again, any thoughts here?

**Comment by alexwlchan** [comment]
The `docs` issue looks like a problem with yesterday’s decision to unbundle dependencies from requests – suddenly urllib3 is presenting a version number "dev", which is confusing [the requests code for parsing urllib3](https://github.com/kennethreitz/requests/blob/master/requests/__init__.py#L50). @Lukasa As a requests maintainer, where would be the best fix for that? Change the way urllib3 presents itself in tox, or add a workaround in requests itself?

Less sure about the `gae` issue.

**Comment by Lukasa** [comment]
Oh god. Why are we importing Requests in the docs build?

**Comment by alexwlchan** [comment]
> Why are we importing Requests in the docs build?

You’re not, Sphinx is.

```console
$ pip install Sphinx
$ pip freeze | grep requests
requests==2.16.5
```

**Comment by Lukasa** [comment]
Oh lol because Requests is required by Sphinx, that's why. Goddamn it, this is a Requests bug.

**Comment by Lukasa** [comment]
Actually it's worse than that. Sphinx requires Requests, and Requests requires a specific version of urllib3 that *may not be the development release*. I'm genuinely unsure of how to resolve this issue.

**Comment by alexwlchan** [comment]
(This seems unrelated to the `gae` failure, so I’m going to split that out into a separate issue.)

**Comment by Lukasa** [comment]
As an example of what the above means, it becomes impossible for us to build docs for urllib3 v2.0 until after it's released, because it cannot possibly work with the Requests that's in Sphinx.

**Comment by Lukasa** [comment]
This is a surprisingly profound problem. There's a very real chicken-and-egg issue here: tox needs to import urllib3 to correctly autodoc it, but the act of doing so breaks the unvendored Requests. I guess for the moment we can add a docs dependency to pin to a vendored Requests release, which is pretty silly.

**Comment by Lukasa** [comment]
This will still leave us with a real problem down the line, both because Requests' is doing insufficiently sensible checking of urllib3 and because if Requests never widens its pins we'll run into real trouble in v2.

**Comment by alexwlchan** [comment]
> both because Requests' is doing insufficiently sensible checking of urllib3

Should Requests be doing any checking at all of the urllib3 version? Or is that something that should be trusted to setup.py/pip?

**Comment by jonparrott** [comment]
The problem is that even if we remove Request's version range, it's possible for us to break Requests (and therefore Sphinx) by installing our dev version.

**Comment by jonparrott** [comment]
@Lukasa looks like it's time for us to release urllib4! 🤣

**Comment by Lukasa** [comment]
Ultimately as long as pip has no dep solver we're at risk of having a bad urllib3 version for Requests, and at least in principle this should reduce the amount of time we spend debugging that for Requests. However, as @jonparrott notes, this doesn't avoid our core problem which is actual compat problems!
