### ISSUE TITLE
SSL errors ambiguous - requests/urllib3/certifi/ssl

### ISSUE THREAD

**Issue by shawndream** [shazow/urllib3#1194]
Lost a whole day+ struggling with vague cert errors before having to give up with no more leads to chase, and held my nose to slap a verify=False and disable_warnings() in my code.

I can't seem to get a self signed cert accepted by urllib3, either by providing the single cer directly to verify (tried exporting it in a variety of formats), or by appending it to the pem downloaded by certifi.

I'm not sure this is the right place to ask, but the groups for the certifi/urllib3/requests seemed a bit overlapping (and I have no idea how to reproduce it using raw ssl package requests)... and I was wondering if there could be any improvement of error clarity in the packages handling of cert failures.

 - what format exactly is certifi/urllib3 expecting for it's pem files (and how could folks use python tools like ssl.get_server_certificate to properly create one with all the Pound extras before the begin cert)?

 - How can I track down exactly what urllib3/ssl is complaining about when I have an (apparently) malformed cert file and get:
...
urllib3.exceptions.SSLError: unknown error (_ssl.c:3517)

 - Or when I use a raw get_server_certificate file with line breaks that seems to be read fine and imported fine to windows, but is ignored for certification with many layers of:
...
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
...
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

(depending on which package I'm trying to use to connect, when chrome and IE accept the installed single cert for the URL in question).

**Comment by Lukasa** [comment]
> what format exactly is certifi/urllib3 expecting for it's pem files

Assuming you're trying to verify a server cert, then there is only really one acceptable format for a PEM file. It looks like this:

```
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
```

This is a base64-encoded blob of binary data, between two delimiters. This *is* the PEM file format.

> how could folks use python tools like ssl.get_server_certificate to properly create one with all the Pound extras before the begin cert

`ssl.get_server_certificate` provides the leaf cert for a server. Assuming the server *really is* serving a self-signed cert, then that will be the root you need, in the format you need.

> How can I track down exactly what urllib3/ssl is complaining about when I have an (apparently) malformed cert file and get:
> ...
> urllib3.exceptions.SSLError: unknown error (_ssl.c:3517)

Again, generally speaking, by asking OpenSSL. The OpenSSL command line tool provides a `verify` subcommand that can be used to attempt to verify a cert, which may give more details. However, OpenSSL generally does a *terrible* job of providing error output, so you may find that you don't get any extra details that way.

> Or when I use a raw get_server_certificate file with line breaks that seems to be read fine and imported fine to windows

What does "raw" mean? That command only outputs PEM, so if it's doing that then that's the data you need to provide to urllib3/requests.

Neither requests nor urllib3 read the Windows certificate store, so if you're importing it into that then that won't work. This is an ongoing problem in Python land which the Requests team is working to address, but it turns out to be extremely tough to do in a sensible way.


Can you show me the code you're using to point at the PEM?

**Comment by shawndream** [comment]
By raw I mean that the output of the ssl.get_server_certificate has endlines every 80 chars or so, and no poundsign extra data before it, unlike the pem files used by certifi. 

I just windcertstore.get_pem()  in case the begin cert block it provided was more PEMmy than ssl.get_server_certificate, but it behaved exactly the same (and looked similar - the file exported had \n every 80 chars or so and returned a c:749, and when the line breaks were removed to make it look more like the pem file used by certifi it gave me a c:3517)
`
pip install wincertstore
`

 `
import wincertstore
import requests

def liststore(thingy1, thingy2):
	for storename in (thingy1, thingy2):
		with wincertstore.CertSystemStore(storename) as store:
			for cert in store.itercerts(usage=wincertstore.SERVER_AUTH):
				if cert.get_name() == "alpha-ocr-01.alpha.local":
					##print(cert.get_name())
					return cert.get_pem()

PEM = liststore("CA", "Trusted Root Certification Authorities")
open('Alpha-OCR-01.pem', 'w+').write(PEM)
requests.get('https://alpha-ocr-01', verify='Alpha-OCR-01.pem')
`
Returned:
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 438, in send
    timeout=timeout
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#109>", line 1, in <module>
    requests.get('https://alpha-ocr-01', verify='Alpha-OCR-01.pem')
  File "C:\Python36\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 512, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

**Comment by Lukasa** [comment]
> By raw I mean that the output of the ssl.get_server_certificate has endlines every 80 chars or so, and no poundsign extra data before it, unlike the pem files used by certifi.

Those are irrelevant. The PEM files used by certifi still line break, and the pound signs are a PEM comment character. No meaningful difference there. :smile:

As to your code, it'd be great to see what the contents of the PEM file you wrote are. Do you mind sharing? If you want to share it with me privately for any reason you can mail me: my email is on my GitHub profile.

**Comment by shawndream** [comment]
I just generated it (and can generate a new one), although it was more fiddly than I thought it should be to get one that passed muster for modern browsers in terms of signing method and subject alt names.

here's the current one, pass for private key is (required for export from windows, although I know it's annoying to retrieve in python):   thankslukasa

I'd love to be able to test it through the python ssl package, as an openssl install seems like it will be using a different codebase.

[FullSelfCertTest.zip](https://github.com/shazow/urllib3/files/1042003/FullSelfCertTest.zip)

**Comment by Lukasa** [comment]
Wait, is this really the contents of the PEM file you wrote using the code above? Because it's not PEM formatted.

**Comment by Lukasa** [comment]
To be clear, when I say "the code above" I mean the result of `liststore("CA", "Trusted Root Certification Authorities")`.

**Comment by shawndream** [comment]
Sorry, no that's the full thing, let me get you the ones I was using.

[Alpha-OCR-pems.zip](https://github.com/shazow/urllib3/files/1042029/Alpha-OCR-pems.zip)

These are the ones from wincertstore (the code above) - the trim one is with endlines removed.

**Comment by Lukasa** [comment]
Hrm. Initially `openssl verify` does not seem to believe that this cert is the correct issuer. I'll try to dig into why.

**Comment by Lukasa** [comment]
So you've got a key usage extension that is problematic. Here's the textual representation of your cert:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            1f:2a:df:b4:a1:9b:3a:b1:46:d2:fe:16:22:87:e4:ea
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN = alpha-ocr-01.alpha.local
        Validity
            Not Before: May 29 18:24:22 2017 GMT
            Not After : May 29 18:24:22 2018 GMT
        Subject: CN = alpha-ocr-01.alpha.local
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a1:36:0c:3f:1b:83:e4:52:0c:23:82:ea:03:e8:
                    65:c7:bf:da:60:c7:de:6e:1f:f8:d8:38:a2:33:71:
                    7c:e1:7a:49:80:a5:13:27:34:c2:ae:45:7b:6a:a6:
                    9a:cb:a7:95:ac:71:72:07:47:8e:1a:b7:31:62:7f:
                    d8:64:dd:39:59:81:27:05:06:8a:25:77:f5:25:50:
                    55:42:ff:9d:71:7d:ba:89:2a:aa:70:04:3a:87:23:
                    f7:c0:88:a1:9b:92:97:7d:78:1c:a7:ef:e5:a9:7c:
                    7a:38:15:62:11:cc:25:c3:9a:38:69:3d:52:b5:c4:
                    ea:78:bc:7b:a2:98:1a:93:d2:99:d5:d4:a4:e0:16:
                    2e:02:09:72:74:ea:ec:8a:85:0b:01:a4:ba:da:4e:
                    4e:db:32:15:1e:2b:f6:af:be:a0:7b:b0:6e:10:d8:
                    41:56:77:39:55:60:cb:a0:b9:b9:1d:73:12:c3:8f:
                    3b:f5:4d:99:54:9a:c1:41:ad:7f:c9:2a:63:14:2f:
                    2b:31:9f:cd:eb:a7:b4:e8:b3:c1:38:80:c6:97:d2:
                    88:7d:b0:74:f9:af:b5:88:d5:81:35:db:4b:9f:f4:
                    75:c0:09:4e:6f:e5:b6:a7:b8:74:84:c6:76:05:70:
                    ca:97:da:bb:74:8c:5b:90:58:ef:4f:c2:5a:28:8f:
                    0a:4f
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Subject Key Identifier: 
                93:85:76:01:EF:C3:D4:96:B4:D6:8E:5D:92:24:71:E0:8F:F6:A3:9E
            X509v3 Key Usage: critical
                Key Encipherment
    Signature Algorithm: sha1WithRSAEncryption
         2e:0c:83:86:b6:e6:c7:69:54:f2:08:1e:a5:0a:e1:32:c4:fb:
         75:bd:f6:6e:ea:41:ad:c6:18:99:d5:63:7d:01:ae:f8:f8:f0:
         43:0f:7b:92:ff:15:4f:63:4c:1a:8f:5e:1f:ab:2e:58:c8:57:
         fe:a2:7e:24:34:81:ab:d2:b3:30:d8:81:f1:f0:cc:0e:51:df:
         9c:99:d0:28:f4:1d:ee:75:39:77:7e:b7:46:b1:79:79:06:03:
         59:bf:77:13:ef:18:10:e7:ab:15:dc:d3:57:24:d7:fe:d9:6e:
         24:67:ca:68:e2:62:70:9a:fd:cf:ae:d5:34:84:27:fd:29:98:
         74:75:f6:e6:76:2c:f3:1b:d6:ce:0f:b3:c4:09:7f:1a:8d:56:
         23:a6:22:33:93:95:11:df:a7:4b:38:5d:a6:6f:06:fc:c1:bd:
         00:e2:04:b2:af:15:9e:c2:22:5a:a0:4d:ac:c2:a7:94:4b:b8:
         3e:88:b4:f6:8d:3b:cd:91:86:68:ce:12:83:99:8e:2a:a5:20:
         d6:70:7e:d7:88:e4:80:91:fe:37:03:ae:08:6d:ce:3a:6b:2c:
         61:9f:eb:e8:e7:0d:6c:1b:b6:b4:4e:a3:71:61:dd:fd:9b:9f:
         6e:37:04:a4:8a:7c:5a:82:98:3f:c7:09:2a:48:6e:c8:ee:96:
         0d:07:5f:14
```

Note the Key Usage extension:

```
X509v3 Key Usage: critical
    Key Encipherment
```

This extension is marked "critical", meaning that it must guide the OpenSSL cert chain validation logic. Put another way, an X.509 certificate with this extension marked critical *must only* be used for purposes allowed in this field. This field only allows key encipherment. This allows the cert to be used for a TLS server *and nothing else*, where critically "nothing" includes "being a certificate authority". This is why OpenSSL isn't validating your cert chain: your cert chains up to a root that is not a valid certificate authority, and when it goes looking for other possible issuing certs it doesn't find any, so it gives up.

Yes, I will note that OpenSSL could be being *much* more helpful here.

If you want to use the Key Usage extension, you should add the `keyCertSign` usage, which allows the use of a cert to be a CA. Alternatively, you can remove that extension entirely, which will make OpenSSL happy.
