### ISSUE TITLE
urllib3 should do nothing on import contrib/pyopenssl in Python>=2.7.9 or 3.4

### ISSUE THREAD

**Issue by ya-isakov** [shazow/urllib3#1225]
If I understand correctly, recent Python versions support all functional provided by contrib/pyopenssl.py. Some third-party libs are uncoditionally trying to inject pyopenssl, so my opinion is that urllib3 should just do nothing, or fail with ImportError in recent Python

**Comment by Lukasa** [comment]
Nope. 

PyOpenSSL is frequently linked against a newer copy of OpenSSL than the Python it is installed against, especially on macOS. This means it continues to provide useful benefits. It is up to projects that use urllib3 to decide when to inject PyOpenSSL, not for urllib3 to refuse to do it.
