### ISSUE TITLE
When sending chunked requests, allow chunk body iterator to format chunks on its own

### ISSUE THREAD

**Issue by kislyuk** [shazow/urllib3#1227]
I'm working with a service that wants me to upload chunked requests with chunk extensions -
 appending a signature for each chunk in the chunk header, e.g.
```
PUT /foo
... headers..

4;CUSTOM_CHUNK_EXTENSION\r\n
Wiki\r\n
5;CUSTOM_CHUNK_EXTENSION\r\n
pedia\r\n
0;CUSTOM_CHUNK_EXTENSION\r\n
\r\n
```
I think the easiest way to accommodate this would be with a kwarg like `PoolManager.request(body=chunk_iterator, raw_chunks=True)`. This would optionally delegate the responsibility for formatting the chunks to the body iterator.

**Comment by Lukasa** [comment]
Thanks for this suggestion!

Chunk extensions are comfortably the least-deployed part of HTTP/1.1: they are so infrequently used that there is no specified way to translate them into HTTP/2, which had a mandate to represent everything representible in HTTP/1.1.

This makes me *extremely* disinclined to add a top-level API hook for this: you may literally be the only person in the Python community who has ever or will ever need it. You should be able to get around this by setting the Transfer-Encoding: chunked header and then passing a file-like object that does the chunking on `read()` calls: have you tried that?

**Comment by kislyuk** [comment]
From what I can tell, the `read()` buffer size is hardcoded to 8192 in https://github.com/python/cpython/blob/master/Lib/http/client.py#L961. I need chunks of a larger, configurable size.

While HTTP 2 drops chunked encoding, it does replace it with data frames, which seem very similar and more configurable. The application I'm talking to doesn't (yet?) support HTTP 2, but it does use chunk extensions as the only way to support streaming, and it's one of the largest APIs in the world (and probably the largest by data volume), so here we are.

In general, I wonder how much the lack of adoption of chunked encoding in general has contributed to bufferbloat in general. Hopefully HTTP 2 data frames will help with that.

I understand the reluctance to add this as a top level kwarg, but I would reiterate my feature request to have *some* way to take control of the chunk formatting. So far the workaround I've come up with is passable, but not very straightforward:
```
class ChunkingHTTPSConnection(urllib3.connection.HTTPSConnection):
    def request_chunked(self, method, url, body=None, headers=None):
        self.putrequest(method, url, skip_accept_encoding=True)
        for header, value in headers.items():
            self.putheader(header, value)
        self.endheaders()
        for chunk in body:
            self.send(chunk)

class ChunkingHTTPSConnectionPool(urllib3.HTTPSConnectionPool):
    ConnectionCls = ChunkingHTTPSConnection

def get_pool_manager(**kwargs):
    pool_manager = urllib3.PoolManager(**kwargs)
    pool_manager.pool_classes_by_scheme["https"] = ChunkingHTTPSConnectionPool
    return pool_manager

pool_manager().request(..., body=chunk_iterator, chunked=True)
```

**Comment by Lukasa** [comment]
Your chunk size is orthogonal to the `read()` size. You can just read out the partial chunk data as you go. There is no requirement that one `read()` call provide a  complete chunk.

**Comment by Lukasa** [comment]
As to the idea that DATA frames are "similar but more configurable", they are not. They are exactly the same as a single block of chunked encoding, with no room for chunk extensions. To define chunk extensions requires defining an extension to HTTP/2 itself, and once you do that you need to get all other implementations to agree to implement it. 

Put another way, chunk extensions in HTTP/1.1 are part of the core spec: in HTTP/2 they are not.

**Comment by kislyuk** [comment]
OK, I see what you mean with the `read()` solution. Yeah, that sounds like it should be more straightforward.

I guess I wasn't very clear with what I was saying about data frames. I'm not an HTTP 2 expert, but I was thinking that by making data frames the default way to send request/response bodies, HTTP 2 is promoting streaming to a higher support status than HTTP 1.1 (where many servers and clients don't support it). And I recognize that chunk extensions are an obscure feature (I'm only working with them because the API requires it), but I imagine in HTTP 2 an equivalent implementation would push that information into the internal app-specific format of each data frame.

**Comment by Lukasa** [comment]
So to be clear, I am 100% in favour of streaming and chunked encoding. The Python client tools have had much stronger support for chunked encoding for longer than in most language communities. My objection is *specifically* to chunk extensions, which have barely been deployed anywhere and are not present in their same "metadata" role in HTTP/2. I'd encourage anyone with APIs that use them to structure that API differently.

Regardless, it seems we have a solution, so for now I'm going to close this. Thanks for your suggestion!
