### ISSUE TITLE
Concurrency Issues on poolmanager.py and _collections.py

### ISSUE THREAD

**Issue by ginward** [shazow/urllib3#1232]
Dear urllib3 developers, 

After reading the source code, I have some questions on the thread-safety of the poolmanager. 

This code: 

  ```
  def connection_from_pool_key(self, pool_key, request_context=None):
        """
        Get a :class:`ConnectionPool` based on the provided pool key.
        ``pool_key`` should be a namedtuple that only contains immutable
        objects. At a minimum it must have the ``scheme``, ``host``, and
        ``port`` fields.
        """
        with self.pools.lock:
            # If the scheme, host, or port doesn't match existing open
            # connections, open a new ConnectionPool.
            pool = self.pools.get(pool_key)
            if pool:
                return pool

            # Make a fresh ConnectionPool of the desired type
            scheme = request_context['scheme']
            host = request_context['host']
            port = request_context['port']
            pool = self._new_pool(scheme, host, port, request_context=request_context)
            self.pools[pool_key] = pool

        return pool

```

It seems that it only locks the pool operation. However, it does not lock between after the pool is created and before the connection is made. During this gap, the connection could be closed by the following code: 

```
def __setitem__(self, key, value):
        evicted_value = _Null
        with self.lock:
            # Possibly evict the existing value of 'key'
            evicted_value = self._container.get(key, _Null)
            self._container[key] = value

            # If we didn't evict an existing value, we might have to evict the
            # least recently used item from the beginning of the container.
            if len(self._container) > self._maxsize:
                _key, evicted_value = self._container.popitem(last=False)

        if self.dispose_func and evicted_value is not _Null:
            self.dispose_func(evicted_value)
```

The RLock will be released after the connectionpool operation is completed. If the RLock is released, and another thread tries to operate on the connection pool - the existing connection could be evicted. Any call on the evicted connection could fail. 

I also looked at the source code that calls the `urlopen` function, and it seems that it is called without any lock whatsoever. It is either a plain HTTPConnectionPool object or a HTTPSConnectionPool object. 

It seems that after the new pool is created and added to the connection pool, no more thread-safety is guaranteed. 

Is this an issue, or is it just me mis-interpreting the code? 

Thanks,

Jinhua

**Comment by Lukasa** [comment]
> It seems that it only locks the pool operation. However, it does not lock between after the pool is created and before the connection is made. During this gap, the connection could be closed by the following code:

This appears to be a possible risk. More generally it seems that objects contained in the LRU cache cannot safely be used ever: if they are in the process of being evicted that eviction may occur while they are being used for some other purpose.

The risk does appear to be vanishingly low: it requires that more than `maxsize` connection pools are in use at once in very rapid succession such that the pools are being created and evicted very swiftly. In particular, `maxsize` pools need to be created in between the interval of creating a pool and a connection being extracted from it (in `_get_conn`).

This does not appear to happen often. However, we should aim to mitigate it. The easiest way to handle it would be to hold the lock longer: however, the urlopen function in `PoolManager` does not have the appropriate abstraction level to do this. It may be that the best thing to do is to just increase `maxsize` to a level where triggering this would be entirely improbable.

As to the connection pool thread safety, there is also thread safety there. Note that the connection pool uses a `LifoQueue` object to store connections. These are thread-safe. Once a connection is extracted from there it "belongs" to the thread making the request, and will not be visible to any others until it is completely used. Setting attributes on the pool is not thread safe, but it is also not the preferred API to urllib3: the PoolManager is.
