### ISSUE TITLE
Does Urllib3 support rate limiting?

### ISSUE THREAD

**Issue by ginward** [shazow/urllib3#1238]
I am about to interact with a RESTful API with a rate limit of 5 requests/second. I was wondering if the urllib3 connection pool has some sort of mechanism to limit the HTTP request rate? An  [example](http://code.activestate.com/recipes/511490-implementation-of-the-token-bucket-algorithm/) is the token-bucket algorithm.

I read briefly through the source code and it seems that I couldn't find any.

**Comment by Lukasa** [comment]
urllib3 does not provide any particular hook for implementing this. If you'd like to do so, you would need to do it yourself.
