### ISSUE TITLE
test_selectors.py tests fail with python 2.6 64bit and 27 64bit on windows 

### ISSUE THREAD

**Issue by itziakos** [shazow/urllib3#1247]
I have noticed that there are a number of tests like the `test_selectors.py::BaseSelectorTestCase::test_register` fail when run against python 2.6 64 bit and python 2.7 64bit. (see appveyor builds, 
https://ci.appveyor.com/project/itziakos/urllib3/build/1.0.7/job/m0xhyhhl05xdcmxi and https://ci.appveyor.com/project/itziakos/urllib3/build/1.0.7/job/i23k8bf88787c199)

The error is due to the fact that `socket.fileno()` returns a `long` on python 2.6 and 2.7  (64bits) and the 
[urllib3.util.selectors._fileobj_to_fd](https://github.com/shazow/urllib3/blob/master/urllib3/util/selectors.py#L41) does not specifically handle that case and the function will finally raise a [ValueError](https://github.com/shazow/urllib3/blob/master/urllib3/util/selectors.py#L50)

The interesting part is that the error was not picked up by the appveyor tests because tox will use the 32 bit python when running the tests.

*output from example build https://ci.appveyor.com/project/itziakos/urllib3/build/1.0.9/job/j84qscx038440brd#L248*
```
py26 runtests: PYTHONHASHSEED='187'
py26 runtests: commands[0] | pip --version
pip 9.0.1 from c:\projects\urllib3\.tox\py26\lib\site-packages (python 2.6)
py26 runtests: commands[1] | python -c import struct; print(struct.calcsize('P') * 8)
32
py26 runtests: commands[2] | pip install .[socks,secure]
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Processing c:\projects\urllib3
  Requirement already satisfied (use --upgrade to upgrade): urllib3===dev from file:///C:/projects/urllib3 in c:\projects\urllib3\.tox\py26\lib\site-packages
```

If it is ok, I can make a PR to fix the issue and attempt to persuade tox to use the 64bit python on appveyor.

**Comment by Lukasa** [comment]
That would be fantastic, thanks!
