### ISSUE TITLE
Problem with connectionpool.py

### ISSUE THREAD

**Issue by horacio9a** [shazow/urllib3#1273]
I am using Python 2.7.13 on Windows 7 and have several scripts which they use urllib3.
Until about 7 days ago, everything worked well but now I get error messages in the lines 706 and 552 of connectionpool.py
An error occurs in my scripts in the line it contains:

r = http_pool.urlopen('GET',url)

before that is line:

http_pool = urllib3.connection_from_url(url)

How to fix this?
Many thanks in advance

**Comment by haikuginger** [comment]
@horacio9a, can you post the full error, please?

As a general note, it's preferred to create a PoolManager, and then use `PoolManager.request()` to automatically handle connections for different hosts.

**Comment by horacio9a** [comment]
Thanks for suggestion @haikuginger . I replaced the lines in the script with this:

>>> from urllib3 import PoolManager
>>> manager = PoolManager()
>>> r = manager.request('GET', url)

and everything is doing OK again :)

**Comment by haikuginger** [comment]
Glad to hear it!
