### ISSUE TITLE
How to get real data, not the data from the cache?

### ISSUE THREAD

**Issue by horacio9a** [shazow/urllib3#1274]
I cann't get fresh data for a particular model using this script.
Using this link (url) with browser I get real data but while using the bottom script every time I get some other non-real data that is already downloaded from a cache. 
I guess the problem is the 'xml' structure of this page.
Is there a way to get real data with the script using some urllib3 method?

> from urllib3 import PoolManager
> url = 'https://www.ifriends.net/userurl_membrg/live/?psource=vchslideup&pclub={}'.format(model)
> http = PoolManager()
> r = http.request('GET', url)
> ps_data = (r.data)

**Comment by haikuginger** [comment]
urllib3 does not cache results, nor does what it hand back generally depend on the content type of the response.

It's possible that the site you're attempting to access may be doing some sort of user-agent discrimination and providing "real" data to browsers but not to scripts. However, determining that is outside the scope of what we can help you with.

Please let us know if you need further assistance.

**Comment by horacio9a** [comment]
I made a mistake because the previous script works ok but it does not provide all the necessary data.
This script does not work properly although I have tried various user-agents:

> url ='https://www.ifriends.net/membrg3/xml4swf.dll?pSWFAPPCODE=EasycamViewer&pClub={}'.format(model)
> user_agent = {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'}
> http = urllib3.PoolManager(headers=user_agent)
> r = http.urlopen('GET',url)
> ps_data = (r.data)

So for the same input model I get expired results each time from different models. 
Only once I get the fresh data from the required model and on that occasion I should have waited quite long time for the result.

**Comment by haikuginger** [comment]
@horacio9a, as mentioned, urllib3 _does not perform any caching_. Any responses you receive that are "expired" are received from the server on each request.

Additionally, as mentioned previously, we recommend you use the `.request()` method, not `urlopen`.

**Comment by horacio9a** [comment]
Thanks @haikuginger for the information and sugestion.
I see that urllib3 is not guilty, but I was hoping that someone would show me who is guilty ;)
Where is right place for this question?

**Comment by haikuginger** [comment]
@horacio9a, I'd suggest contacting the website host to determine what additional parameters their API might require that you're not passing.
