### ISSUE TITLE
request_encode_url gives InsecureRequestWarning and hangs indefinitely

### ISSUE THREAD

**Issue by mosegontar** [shazow/urllib3#1280]
I'm experiencing the following issue.

I am making GET requests  using the `request_encode_url` PoolManager method to two sites that do not have SSL: mose.io and mattbruenig.com

The following request (to https://mose.io)  gives the InsecureRequestWarning but still returns a response:

    > myheaders = {'Accept-Encoding': 'gzip,deflate', 'Accept': '*/*', 'Cookie': '', 'DNT': '1'}
    > pool = urllib3.PoolManager(num_pools=1, headers=myheaders)
    > pool.request_encode_url("GET", "https://mose.io", timeout=1).status
    /venv/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
    200

But this request (to https://mattbruenig.com) gives the warning and then hangs indefinitely:

    > myheaders = {'Accept-Encoding': 'gzip,deflate', 'Accept': '*/*', 'Cookie': '', 'DNT': '1'}
    > pool = urllib3.PoolManager(num_pools=1, headers=myheaders)
    > pool.request_encode_url("GET", "https://mattbruenig.com", timeout=1).status
    /venv/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning)
   

 Is there a way to get this to at least raise an exception, instead of hanging? I also would have expected it to timeout. Thanks a lot.

**Comment by Lukasa** [comment]
Yes: you can turn off retries.

This is not actually hanging. The server is returning a 503 Service Unavailable response with a Retry-After header set to 3600 seconds (a.k.a. one hour). urllib3 by default respects these responses, so we stop and hold-off until the retry-after time has passed.

In general if you want to do only exactly the request you ask for, you'll need to set retries=0, or more generally set a custom retry policy.

**Comment by mosegontar** [comment]
thank you!
