### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by steveoh** [shazow/urllib3#1288]
It appears that on osx after the recent root user patch that urllib3 is having issues or maybe the timing is convenient... either way

```
urllib3/fields.py", line 2, in <module>
import email.utils
ImportError: No module named utils
```

**Comment by sigmavirus24** [comment]
I don't think this is a problem for urllib3. I think your system is broken. If you do

```
$ python
>>> import email.utils
```

You should see this regardless of urllib3. For me, this works in Python 3.6 and Python 2.7 so I suspect that the upgrade caused you some distress with whatever Python you're trying to use. Try reinstalling python to fix your issue.

**Comment by steveoh** [comment]
sheesh, you're right. I had an email.py file in the cwd. 🤦‍♂️
