### ISSUE TITLE
urllib3 wrong computation of 'Content-Length' for file upload

### ISSUE THREAD

**Issue by gpiani** [shazow/urllib3#1300]
Hi! This is my first posting ever on this site. I hope to have come to the right place. 

System: Ubuntu 16.04, Python 3.5.

I need to upload a simple text file to Internet servers. With "curl" the operation goes smoothly, both with http and https protocols, both up/downloads. With urllib3 and other TCP-IP handlers (e.g., requests)  file downloads work correctly, also when authentication is necessary. Uploads, however, do not work.

A log verification with TCPDUMP indicates that with urllib3 (requests, etc.) the generated header for 'Content-Length' contains a wrong file length indication. The file is not uploaded, the servers return different error messages. 

code example
```python
headers = {'authorization': 'Basic ==codeduserpwd=='}
resp = http_client.request('PUT',
                           'https://webserver.com',
                           headers=headers,
                           fields={'filewhat': (filename, filename.open())}
                           )
```
Header log for urllib3 (does not work)
```
	PUT /remote.php/dav/files/gpiani/ HTTP/1.1
	Host: www.hosthere.com
	Accept-Encoding: identity
	Content-Length: 281
	Content-Type: multipart/form-data; boundary=b20a0...
	authorization:  Basic ==codeduserpwd==
```
Header log for curl (it works)
```
        PUT /remote.php/dav/files/gpiani/MYFILE HTTP/1.1
        Host: www.hosthere.com
        Authorization: Basic  ==codeduserpwd==
        User-Agent: curl/7.47.0
        Accept: */*
        Content-Length: 94
```
The two major differences are the file indication in the header and of course the content length. Concerning the first aspect I can take that in consideration while passing the destination file name, but without the correct file length the whole procedure does not work.

If anything needs to be tested I am of course fully interested to do it.

Thankful for your support!

**Comment by haikuginger** [comment]
@gpiani, one thing to be aware of is that we don't currently allow uploading file-like objects directly. You'd need to read the contents of the file into an in-memory buffer, explicitly encoded as bytes (for example: `open('fname', 'rb').read()`, which explicitly opens a file in binary mode). Can you verify that?

**Comment by SethMichaelLarson** [comment]
See #1030 for an implementation that was deferred to v2.

**Comment by gpiani** [comment]
Thank you Jesse and Seth! I shall try your suggestion in about one week
from now. In fact, uploading a binary-coded string of text would be a
perfect solution for my application. Shall do some tests with this
approach and let you know.

**Comment by sigmavirus24** [comment]
Since this isn't an actual defect in the library, I'm closing this issue. For future assistance using urllib3, I suggest using [StackOverflow](https://stackoverflow.com) to receive answers to your questions.
