### ISSUE TITLE
SSLError: HTTPSConnectionPool(host='www.quandl.com', port=443): Max retries exceeded

### ISSUE THREAD

**Issue by Suman5051** [shazow/urllib3#1302]
I am facing an issue. Kindly help me

Here's the code:

import pandas
import quandl
import time

df = quandl.get('FINRA/FNSQ_GOOGL')
print(df.head())

and the error which i am facing is:

Traceback (most recent call last):

  File "C:\Users\Desktop\My Folder\test.py", line 5, in <module>
    df = quandl.get('FINRA/FNSQ_GOOGL')

  File "C:\Python27\lib\site-packages\quandl\get.py", line 48, in get
    data = Dataset(dataset_args['code']).data(params=kwargs, handle_column_not_found=True)

  File "C:\Python27\lib\site-packages\quandl\model\dataset.py", line 47, in data
    return Data.all(**updated_options)

  File "C:\Python27\lib\site-packages\quandl\operations\list.py", line 14, in all
    r = Connection.request('get', path, **options)

  File "C:\Python27\lib\site-packages\quandl\connection.py", line 36, in request
    return cls.execute_request(http_verb, abs_url, **options)

  File "C:\Python27\lib\site-packages\quandl\connection.py", line 50, in execute_request
    raise e

SSLError: HTTPSConnectionPool(host='www.quandl.com', port=443): Max retries exceeded with url: /api/v3/datasets/FINRA/FNSQ_GOOGL/data?order=asc (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

I even tried the below code, but no luck,
import pandas 
import quandl
import time
df=''
while df=='':
try:
    df = quandl.get('FINRA/FNSQ_GOOGL')
except:
    time.sleep(5)
    print("try")
    continue
print(df.head())
It would be grateful if somebody help me solve this issue. Thanks in advance!!

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

Further more, it appears as if this is not actually related to urllib3. The exception looks familiar but there's no `urllib3` files in the traceback.
