### ISSUE TITLE
RECENT_DATE needs to be bumped

### ISSUE THREAD

**Issue by DimStar77** [shazow/urllib3#1303]
Test suite started failing, as RECENT_DATE is not recent enough:

```
[   62s]     def test_recent_date(self):
[   62s]         # This test is to make sure that the RECENT_DATE value
[   62s]         # doesn't get too far behind what the current date is.
[   62s]         # When this test fails update urllib3.connection.RECENT_DATE
[   62s]         # according to the rules defined in that file.
[   62s]         two_years = datetime.timedelta(days=365 * 2)
[   62s] >       assert RECENT_DATE > (datetime.datetime.today() - two_years).date()
[   62s] E       AssertionError: assert datetime.date(2016, 1, 1) > datetime.date(2016, 1, 1)
[   62s] E        +  where datetime.date(2016, 1, 1) = <built-in method date of datetime.datetime object at 0x7fb6899be198>()
[   62s] E        +    where <built-in method date of datetime.datetime object at 0x7fb6899be198> = (datetime.datetime(2017, 12, 31, 10, 16, 14, 472906) - datetime.timedelta(730)).date
[   62s] E        +      where datetime.datetime(2017, 12, 31, 10, 16, 14, 472906) = <built-in method today of type object at 0x7fb68e948d20>()
[   62s] E        +        where <built-in method today of type object at 0x7fb68e948d20> = <class 'datetime.datetime'>.today
[   62s] E        +          where <class 'datetime.datetime'> = datetime.datetime
```

**Comment by sigmavirus24** [comment]
https://github.com/shazow/urllib3/blob/da05fe2497e18b367cab159195a1ace9a74119e3/urllib3/connection.py#L59..L62

**Comment by DimStar77** [comment]
I can provide a patch - but what date should I pick? Preferably I'd go with 2018-01-01, but that means the test suite will only start passing tomorrow

Alternatively, 2017-01-01, but that is against the rule outlined in the file (within the last 6 months) - or we pick a date mid-year

**Comment by Lukasa** [comment]
The rule is *not* within the last 6 months. I appreciate that the wording could be clearer there. So the newest date you can pick is 2016-06-30.

**Comment by DimStar77** [comment]
```
# When updating RECENT_DATE, move it to
# within two years of the current date, and no
# earlier than 6 months ago.
```

2016-06-30 is earlier than 6 months ago - so the wording is definitively not what I would understand there. Looking at the current date, minus 6 months, would give us 2017-06-30 then though

**Comment by Lukasa** [comment]
> 2016-06-30 is earlier than 6 months ago - so the wording is definitively not what I would understand there

Agreed, but the reason it cannot mean that is that the requirement is redundant with "within two years of the current date": if "no earlier than 6 months ago" means "within 6 months of today" we don't need the two year admonition, and in fact may as well just write "set it to yesterday". As a result, I have to assume that the author (who may well have been me) meant "no more recent than", and swapped "earlier" in a false word match.

**Comment by DimStar77** [comment]
The wording was changed with https://github.com/shazow/urllib3/commit/5f093e00ead09b1302d2e12dc4f4db5f4825c4f5 - but indeed did not really make it much less confusing :)

**Comment by SethMichaelLarson** [comment]
Sorry for the terrible wording, thanks for fixing it. :)
