### ISSUE TITLE
Url lib not accessing link as expected getting 'HTTP/1.1 400 Bad Request\r\n'  after initial grant

### ISSUE THREAD

**Issue by tysondogerz** [shazow/urllib3#1312]
To summarise in 3 sentences. This is what happens to all my calls.  Url lib3 works fine initially but then things don't work all of a sudden.  Possible workaround?  It authenticates initially but then it looks like it gets redirected.

1) 'HTTP/1.1 302 Found\r\n'
2) Server header: Vary header.........
3) 'HTTP/1.1 400 Bad Request\r\n'

Full error:
https://pastebin.com/V9ibxTRX

```
    from __future__ import print_function
    import time
    import argparse
    import os
    import signal
    import sys
    import logging
    from selenium import webdriver
    import requests
    logging.basicConfig(level=logging.DEBUG)

    from client_config import ClientConfig
    from pyupdater.client import Client, AppUpdate, LibUpdate

    def check_for_update():
        client = Client(ClientConfig(), headers={'basic_auth': 'user:passwd'}, refresh=True)
        app_update = client.update_check(ClientConfig.APP_NAME, ClientConfig.APP_VERSION, channel='stable')

        if app_update is not None:  # is there a new update
            if app_update.download():  # the update download is made here
                if isinstance(app_update, AppUpdate):  # you should freeze it
                    app_update.extract_restart()
                    return True
                else:
                    app_update.extract()
                    return True
        return False


    def main():
        print('Current version is ', ClientConfig.APP_VERSION)
        if check_for_update():
            print('there\'s a new update :D')
        driver = webdriver.Firefox()
        driver.get('http://stackoverflow.com')

    if __name__ == "__main__":
        main()
```

I tried to change:

  ```@ line 366
              data = self.http_pool.urlopen('GET', file_url,
                                              preload_content=False,
                                              retries=max_download_retries,
                                              redirect = True)  ####

```

https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/downloader.py

But no such luck.  Quite strange behaviour.

**Comment by haikuginger** [comment]
This is something that you'll need to figure out on a higher level. If a server is returning 200 to one request and 400 to another, then it is likely that you're missing a core piece of application-layer logic that makes one of those requests sufficient and the other insufficient. If you can isolate a specific way that urllib3 is failing to work correctly (by which I mean failing to execute a properly-formed HTTP request that honors its API commitments), we're happy to take a look at that.
