### ISSUE TITLE
Disabling default headers.

### ISSUE THREAD

**Issue by GHXST01** [shazow/urllib3#1315]
Hey,

I'm wondering if it's possible to disable default headers.
The one in specific I would like to disable is Accept-Encoding.

This is not my decision so please no arguing about it being pointless.
I know 😛.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by GHXST01** [comment]
Hey @sigmavirus24 I noticed the actual issue is that `skip_accept_encoding=True` isn't being utilized.
