### ISSUE TITLE
Incomplete chunked responses are not retried

### ISSUE THREAD

**Issue by corehack** [shazow/urllib3#1352]
I am using Retry helper with requests library session. It looks like IncompleteRead which is a read error is not retried as I would expect.

Fetch the following URL:
https://httpbin.org/response-headers?Content-Type=text%2Fplain%3B+charset%3DUTF-8&Transfer-Encoding=chunked&Server=httpbin

You get:
```
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
Instead of max retries exception.

**Comment by corehack** [comment]
Hmm, if I use urllib3 directly I can see the request is being retried. Could be a requests bug

**Comment by sigmavirus24** [comment]
Without knowing how you're using retries with Requests, it's hard to say what's going wrong. And it doesn't seem you're running into this using urllib3 alone, although Requests does use urllib3 differently than most people use urllib3.

**Comment by corehack** [comment]
Yeah I created an issue there
