### ISSUE TITLE
support ip address typed subject alterative names when connecting to an ip address using https

### ISSUE THREAD

**Issue by sigmunau** [shazow/urllib3#258]
According to rfc6125 section 3.1.3.2 subjectAltName values of type iPAddress should be considered when the https connection is made directly to an ip address rather than a dns domain name. If a server uses such a certificate, urllib3 will fail to validate it, however other tools such as curl and go does. go even refuses to consider CN when verifying the certificate when connected by the

**Comment by bodgit** [comment]
I've just run into this issue trying to rely on IP address SAN's in a cert. I was using Python 2.7.10 but on a whim I tried Python 3.5.0 and it works there. Indeed https://hg.python.org/cpython/file/3.5/Lib/ssl.py#l254 shows there is now code that uses the IP SAN's if present.

What would need to happen to get this working on older Pythons? I'm guessing that simply updating the vendored code would fix versions `< 3.2` but versions `>= 3.2 && < 3.5` would use their own shipped version and remain broken?

**Comment by Lukasa** [comment]
@bodgit Yes, I suspect so. Also, our pyopenssl compatibility layer requires updating. I may take a swing at this tomorrow.

**Comment by tiran** [comment]
I don't like the implemention in Python stdlib and I have raised my concern but it was too late. IMO the code has two problems

1) The stdlib attempts to auto-detect if a string is a IPv4 or IPv6 address. It feels wrong.
2) It also sets the IP address as SNI but that is a violation of the protocol. 

https://bugs.python.org/msg244665

**Comment by tiran** [comment]
By the way for future compatibility the new API should be modelled after OpenSSL's new API. For a while OpenSSL is able to do proper validation of host names, IP addresses and email itself.

**Comment by Lukasa** [comment]
@tiran When it comes to copying the stdlib mostly what I'm going to do is copy the logic from `match_hostname`, and potentially a bit from the `getpeercert` function. I'm not going to adjust the SNI logic we have.

As to guessing the IP address type, is there any way around that?

**Comment by Lukasa** [comment]
I'd like to resurrect this a little bit and take another spin at it. Ideally if we can backport just the smallest bits of ipaddress we need then we can optionally have this support. It'll require some PyOpenSSL enhancement as well, but what doesn't?

**Comment by Lukasa** [comment]
For those watching this issue, see #922.
