### ISSUE TITLE
Retry: Add support for 503 Retry-after?

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#425]
https://twitter.com/akislyuk/status/484141116019580928

Maybe something like `Retry(status_whitelist=...?)` and if it includes 503 then `Retry.sleep()` could do something special when incremented with a 503 response?

Feels slippery...
##

**Comment by vfaronov** [comment]
I think this was done in #955.

**Comment by haikuginger** [comment]
So we have! Thanks @vfaronov!
