### ISSUE TITLE
urllib3 upload retry fails to seek file-object

### ISSUE THREAD

**Issue by joneskoo** [shazow/urllib3#459]
I believe urllib3 fails to seek file object to beginning when it retries the upload. This bug is probably the true reason why I got timeout in issue #442 .

I overwrote read method in file object to demonstrate this. 

https://gist.github.com/joneskoo/3fe7fb68836d9b387273

The retry handling is non-trivial and gets even more complicated as there's file objects and not strictly strings to deal with.

I believe the retry with file objects should:
1. seek file to beginning or position reported by tell() before reading the file object
2. FAIL if the file object does not support seeking

Currently if I understand correctly the current behaviour will corrupt uploads or result in Timeout error as I experienced before.

Thanks @Lukasa for continued help trying to debug this.
##

**Comment by nateprewitt** [comment]
This has been resolved with #1039.
