### ISSUE TITLE
urllib3 leaks lots of resources

### ISSUE THREAD

**Issue by kevinburke** [shazow/urllib3#495]
For fun I decided to run the tests with `PYTHONWARNINGS=always::DeprecationWarning,error::ResourceWarning nosetests`.

According to the warning in the socket module, virtually every test in urllib3 fails to properly close a socket. Example output:

https://travis-ci.org/kevinburke/urllib3/jobs/39233502#L697

    Exception ignored in: <ssl.SSLSocket fd=62, family=AddressFamily.AF_INET,  
    type=SocketType.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57685), 
    raddr=('127.0.0.1', 40285)>

I'm surprised no one has raised this issue, given how many people use the library. I'm forced to conclude

1. the python library is raising this error erroneously
2. everyone leaks sockets, and it's harmless
3. everyone leaks sockets, and no one cares because sockets are always available
3. the tests leak sockets more than most because they expose error conditions

What's going on? Is there something easy that can be done to fix this @sigmavirus24, @Lukasa, @jschneier , thoughts?

**Comment by smetj** [comment]
Hi,

fyi,
On PyPy -2.4.0 upgrading to urllib3-1.10 solves this problem for me.

**Comment by shazow** [comment]
@smetj Thanks for the update!

@sigmavirus24 How do you feel about closing this? Or do you have plans to investigate further?

**Comment by shazow** [comment]
@sigmavirus24 said to close until someone else complains. :)

**Comment by smetj** [comment]
For the sake of completeness.
I kept hitting this problem with the "requests" library.
 Apparently it comes bundled with a version of urllib3.
If you're using requests on PyPy, make sure you upgrade to the latest version.
I can confirm requests-2.5.1 fixes the problem for me.
