### ISSUE TITLE
HTTPS requests fail through a proxy

### ISSUE THREAD

**Issue by bhendo** [shazow/urllib3#50]
Requests to access a secure website (SSL/TLS) fail through a proxy.
Urllib3 does not properly implement the HTTP CONNECT method.

For example the following code should print 200.
Instead, with a burp proxy, it prints 502.

import urllib3

proxy = urllib3.proxy_from_url('http://localhost:8080/'
response = proxy.urlopen('GET', 'https://www.google.com/index.html')

print response.status

**Comment by schlamar** [comment]
FYI, this was done in https://github.com/shazow/urllib3/pull/170 :)

**Comment by shazow** [comment]
@schlamar Thanks! :)
