### ISSUE TITLE
urllib3 keeps connection open after failed fingerprint validation

### ISSUE THREAD

**Issue by untitaker** [shazow/urllib3#529]
1.  Launch a single-threaded HTTPS server, like the one from Werkzeug/Flask, with ad-hoc certificate generation.

2.  Paste this into a file called lol.py:

        from urllib3.poolmanager import PoolManager

        def x():
            # This is GitHub's certificate fingerprint. This function should not exit successfully.
            fingerprint = 'A0:C4:A7:46:00:ED:A7:2D:C0:BE:CB:9A:8C:B6:07:CA:58:EE:74:5E'  
            p = PoolManager(assert_fingerprint=fingerprint)
            r = p.request('GET', 'https://127.0.0.1:5000')
            p.clear()  # doesn't seem to matter

3.  Launch ``python -i lol.py``, in a Python 3 virtualenv with the latest PyPI-release of urllib3 installed.

4.  Execute ``x()`` once, an exception for the mismatching fingerprint is thrown.

5.  Execute ``x()`` again, the function doesn't terminate. Werkzeug is not responding to it because it is busy with another connection, but that one should've been closed.

Notes:

- If one kills the Python process where urllib3 is used, the connections are terminated and the server is usable again.

- This is Python-3-specific.

- This was found during usage with requests, which has the exact same problem. See https://github.com/untitaker/vdirsyncer/pull/161

**Comment by untitaker** [comment]
Also, here's a simple Flask app which will suffice for this test:

    import flask
    app = flask.Flask(__name__)

    @app.route('/')
    def index():
        return "haha!"

    app.run(ssl_context='adhoc')

**Comment by shazow** [comment]
+1 to closing connections after a failed validation. Should be reasonably easy to port this test to our test_socketlevel.py suite.

@untitaker Would you like to work on this PR to fix it?

**Comment by untitaker** [comment]
Yes, but please don't expect results until next week.

**Comment by shazow** [comment]
@untitaker This is open source, we expect nothing but love. :)

**Comment by untitaker** [comment]
Not sure where to start. The code at https://github.com/shazow/urllib3/blob/master/urllib3/connection.py#L241 raises the exception which hangs the connection, but I am not sure why it would cause any problems... ``match_hostname`` also raises exceptions of the same type, and they don't cause problems. Or do they?

**Comment by shazow** [comment]
Hm not sure why an exception raised would hang a connection.

@Lukasa @sigmavirus24 Any thoughts?

**Comment by Lukasa** [comment]
Raised exceptions can cause the interpreter to fail to exit in a threaded case. If we're not talking threading, the only thing I could think of is that the connection gets re-used after having been left in a bad way. Otherwise...

**Comment by untitaker** [comment]
The example above is not threaded though.

**Comment by untitaker** [comment]
In fact this works, in the sense that certificate verification fails but no connections are leaked:

    from urllib3.poolmanager import PoolManager
    import certifi

    def x():
        fingerprint = 'A0:C4:A7:46:00:ED:A7:2D:C0:BE:CB:9A:8C:B6:07:CA:58:EE:74:5E'
        p = PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())

        r = p.request('GET', 'https://127.0.0.1:5000')
        p.clear()  # doesn't seem to matter

**Comment by untitaker** [comment]
It seems though that the traceback for this test is originating from somewhere completely different.

**Comment by t-8ch** [comment]
@untitaker maybe you are hitting #524?
(sorry I am in my phone)

**Comment by untitaker** [comment]
Yeah, I also just noticed in a local test, but the example above doesn't use it.

**Comment by untitaker** [comment]
What completely irritates me that CA verification is already done when calling ``ssl_wrap_socket`` https://github.com/shazow/urllib3/blob/master/urllib3/connection.py#L234, while a few lines below, the same thing is done.

For this kind of TB to obtain, I had to apply [this patch](https://gist.github.com/untitaker/c0df8493db7fba23799c).

**Comment by t-8ch** [comment]
Have you seen #529?

**Comment by untitaker** [comment]
Lol that's the issue you're posting in.

**Comment by t-8ch** [comment]
Hmpf, indeed. I meant #526

**Comment by untitaker** [comment]
It seems that raising any exceptions in ``Connection.connect`` after calling ``self.sock.getpeercert`` causes this connection leak.

**Comment by untitaker** [comment]
Applying #526 doesn't help with both examples.

**Comment by t-8ch** [comment]
This fixes the issue for me:

```diff
diff --git a/urllib3/connectionpool.py b/urllib3/connectionpool.py
index 8bdf228..98b75f8 100644
--- a/urllib3/connectionpool.py
+++ b/urllib3/connectionpool.py
@@ -549,7 +549,7 @@ class HTTPConnectionPool(ConnectionPool, RequestMethods):
             # Timed out by queue.
             raise EmptyPoolError(self, "No pool connections are available.")
 
-        except (BaseSSLError, CertificateError) as e:
+        except (BaseSSLError, CertificateError, SSLError) as e:
             # Close the connection. If a connection is reused on which there
             # was a Certificate error, the next request will certainly raise
             # another Certificate error.
```

The problem is, that `BaseSSLError` comes from the stdlib `ssl` module and
`CertificateError` from `backports.ssl`. So we don't catch our own stuff.
Maybe we should clean this up.
And get a test.

**Comment by untitaker** [comment]
Neat. Working on PR...

**Comment by shazow** [comment]
+1, thanks for figuring this out. :)
