### ISSUE TITLE
Raise SSLError exception when using HTTPS via proxy

### ISSUE THREAD

**Issue by mrcuongnv** [shazow/urllib3#531]
Hi,

I used [requests](http://python-requests.org) to make a connection to a HTTPS-enabled site via a HTTP proxy which supports CONNECT.

```python
import requests
requests.get("https://www.google.com", proxies={"https": "http://127.0.0.1:8080"})
```

... and got the exception

```
SSLError: hostname '127.0.0.1' doesn't match 'www.google.com'
```

After debugging in current master branch, I found that the problem might due to the change of `actual_host` and `actual_port` in `_new_conn()` to proxy's ones.

```python
actual_host = self.host
actual_port = self.port
if self.proxy is not None:
    actual_host = self.proxy.host
    actual_port = self.proxy.port
```

https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L722

What should I do to overcome this problem?

**Comment by schlamar** [comment]
Issue should be somewhere around here: https://github.com/shazow/urllib3/blob/master/urllib3/connection.py#L210 Can you check the the `hostname´ variable before and after tunneling. Which Python version are you running? There might be an issue < 2.6.3

**Comment by mrcuongnv** [comment]
I use Python 2.7.8.

Btw, I checked my local version of connection.py and found that it was very short in comparison to the current version in GitHub. After upgrading urllib3 to the latest version, the problem has gone.

Thank you!
