### ISSUE TITLE
More Documentation Please

### ISSUE THREAD

**Issue by ObiWahn** [shazow/urllib3#536]
Hi,

I would like to use your lib to replace some python2 code that I wrote with urllib2 and poster. Now i almost remember no details and I know that it was not easy back then, but your lib does not make it much easier because the documentation is not good:

http://urllib3.readthedocs.org/en/latest/helpers.html#urllib3.filepost.encode_multipart_formdata
What is the return value and in which function should I put the return value?

Maybe I am spoiled by strongly typed languages. But for me it is totally un-obvious how to use the lib. So please add more documentation.

The code is pretty good read and understandable (e.g. https://github.com/shazow/urllib3/blob/master/urllib3/request.py). I am still convinced that an beginner friendly update of read the docs would be a big benefit for new users.

**Comment by shazow** [comment]
You shouldn't need to use the filepost submodule manually unless you're doing something strange, in which case you may need to become more familiar with the code. The more high-level stuff lives here: http://urllib3.readthedocs.org/

That said, I would love to have you write better documentation for urllib3! Please send a pull request and I'll merge it as soon as it's ready. :)
