### ISSUE TITLE
Misleading comment in connectionpool.py

### ISSUE THREAD

**Issue by inglesp** [shazow/urllib3#537]
At https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L356, there is a comment implying that in Python 2.7+, we can buffer HTTP responses by passing `buffering=True` to `HTTPConnection.getresponse`.

However, in Python 3, `http.client.HTTPConnection.getresponse` does not take any arguments, so line 356 triggers a `TypeError`, which is caught by the next line.

So, at the least there's a misleading comment, but there's also the possibility that we think we're buffering HTTP responses but we're actually not.

**Comment by shazow** [comment]
@inglesp Yea that doesn't sound great. Would you like to send a PR with a revision? :)
