### ISSUE TITLE
[rfe] provide access to chunks when server responds with `Transfer-Encoding: chunked`

### ISSUE THREAD

**Issue by TomasTomecek** [shazow/urllib3#550]
I've opened [an issue](https://github.com/kennethreitz/requests/issues/2449) at [requests](https://github.com/kennethreitz/requests) but was advised to move it here. There it goes:

When server responds with `Transfer-Encoding: chunked`, it would be nice if `urllib3` provided access to chunks sent by server. Therefore upper layers, `requests`, could process those encoded chunks and developers wouldn't need to decode those chunks.

More info:
http://en.wikipedia.org/wiki/Chunked_transfer_encoding
http://mihai.ibanescu.net/chunked-encoding-and-python-requests

**Comment by Lukasa** [comment]
Hello again!

So, the core problem here is `httplib`. We can achieve this if we grab direct access to the socket underlying `httplib` and decode the chunking ourselves. @shazow, is this a thing you want?

**Comment by shazow** [comment]
HMMM!! Stealing the socket from httplib is not a thing I have considered.

If it can be done in a reliable/safe way, that could be worthwhile. :)

**Comment by TomasTomecek** [comment]
...how about going even deeper and ask for RFE in `httplib`?

**Comment by shazow** [comment]
![tzos8](https://cloud.githubusercontent.com/assets/6292/6263461/18abc880-b7cd-11e4-9e74-3301abaee074.gif)

**Comment by Lukasa** [comment]
`httplib` should be viewed as a source of pain from which no light or joy can escape. @shazow has repeatedly asked me to rewrite `httplib`. One day I might even do that. =)

**Comment by TomasTomecek** [comment]
I can see there is already code in `httplib` which [reads chunked responses](https://hg.python.org/cpython/file/2.7/Lib/httplib.py#l590). The problem is, it doesn't return generator. Also, looking at [this blog post](http://blog.dowski.com/2008/04/02/reading-chunked-http11-responses/ ), one should be able to change response class, which looks kinda hacky (but doesn't require patching httplib)

**Comment by Lukasa** [comment]
That might be the better way to go about it.

**Comment by TomasTomecek** [comment]
@Lukasa @shazow 
does it mean that I can write a patch which could be merged at some point (or you would be wiling to work on it?). Just to be clear: I don't mind providing the patch. Shouldn't be that hard, I hope.

**Comment by Lukasa** [comment]
Ideally you'd write the patch. I'm busy rewriting httplib. ;)

**Comment by shazow** [comment]
@TomasTomecek Patches are always appreciated. :) Keep in mind that we have a 100% test coverage policy for merging.

Feel free to open a PR and ping it whenever you'd like us to take a look at it, we're happy to help you along the way.
