### ISSUE TITLE
Cut a new release for requests

### ISSUE THREAD

**Issue by ralphbean** [shazow/urllib3#554]
Requests bundled a new snapshot of urllib3 and did a release.  Can you do a release to match, please?

Looks like the latest is in [this commit](https://github.com/kennethreitz/requests/commit/58e513579a0934dbd737077f3069c04d68cf1a52) they updated to 29aa09bde9c42cc9a8d79aac47ee3d362b438cca

**Comment by shazow** [comment]
Can do, will do in a day or two. :) Thanks for the reminder.

**Comment by shazow** [comment]
Pushed v1.10.2: https://pypi.python.org/pypi/urllib3/1.10.2

**Comment by ralphbean** [comment]
Thanks @shazow!
