### ISSUE TITLE
Emit a warning on platforms where we can't configure OpenSSL as we'd like

### ISSUE THREAD

**Issue by alex** [shazow/urllib3#557]
Specifically this means:

* Python < 2.7.9 (Probably something for older Python 3s, but I don't know that off hand)
* and no pyOpenSSL + pyasn1 + ngd-httpsclient

On these platform we can't do all the configuration we'd like, including the fix for verification that we've been discussing. It'd be great if users know they should upgrade their Python (or install the appropriate optional dependencies)

**Comment by Lukasa** [comment]
+1. This sounds like a good idea to me.

**Comment by dstufft** [comment]
This should probably actually detect whether there is a ``SSLContext`` object or not instead of inspecting Python versions.

**Comment by alex** [comment]
Great point.

On Mon, Mar 2, 2015 at 7:08 AM, Donald Stufft <notifications@github.com>
wrote:

> This should probably actually detect whether there is a SSLContext object
> or not instead of inspecting Python versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shazow/urllib3/issues/557#issuecomment-76727578>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by sigmavirus24** [comment]
:+1:

**Comment by shazow** [comment]
Sounds good. Agree about checking for features rather than versions when possible.

Does anyone want to take this task?

**Comment by Lukasa** [comment]
I'll do it.

**Comment by Lukasa** [comment]
Alright, comments requested on #558.

**Comment by Lukasa** [comment]
Resolved in #558. =)

**Comment by agriffis** [comment]
Could someone provide pointers for "On these platform we can't do all the configuration we'd like, including the fix for verification that we've been discussing."  I'd like to fully understand the details of the warning, but I haven't been able to trace through the history beyond this statement.

**Comment by Lukasa** [comment]
Sure. =)

The SSLContext object is the modern way to configure TLS settings in Python. There are a number of things the SSLContext can do that platforms without it cannot do, mostly to do with disabling certain features. For example, you cannot disable TLS compression support without it: disabling TLS compression is necessary to avoid the CRIME attack. We also can't do SNI without an SSLContext.

Generally speaking, platforms without SSLContexts are dramatically less secure than those that have them.

**Comment by agriffis** [comment]
Thanks @Lukasa!
