### ISSUE TITLE
Don't prefer the stdlib defined Ciphers

### ISSUE THREAD

**Issue by dstufft** [shazow/urllib3#572]
Right now urllib3 does:

```python
try:
    from ssl import _DEFAULT_CIPHERS
except ImportError:
    _DEFAULT_CIPHERS = (
        'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+HIGH:'
        'DH+HIGH:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+HIGH:RSA+3DES:!aNULL:'
        '!eNULL:!MD5'
    )
```

Which means that it's going to prefer whatever ciphers Python prefers. However given that it's much easier to upgrade urllib3 (or requests or pip or ...) than it is to upgrade Python and that urllib3 (etc) has a much shorter release cycle I believe it would be a better idea to just ignore the ciphers that Python likes and just have urllib3 set it's own default ciphers.

**Comment by Lukasa** [comment]
I have no objection to doing that. =)

**Comment by sigmavirus24** [comment]
So I have the change here https://github.com/shazow/urllib3/compare/master...sigmavirus24:patch-1

The thing I'm concerned about is the following situation (which I'm uncertain of the likelihood). Let's say someone installs urllib3 (or requests). There may be an instance where they update to a newer patch-level of python that has an improved cipher list without upgrading urllib3. In that case, urllib3's cipher list will be less secure than the default. I wonder if we can be smarter than this. How does the following sound?

We maintain a list of ciphers we do not want in the default list and which may exist there. We split up the cipher list from the stdlib and remove the ones we want to forcibly exclude. Something like:

```py

cipher_blacklist = set([ ... ])
try:
    from ssl import _DEFAULT_CIPHERS
except ImportError:
    # define our own
else:
    ciphers = set(_DEFAULT_CIPHERS.split(':'))
    ciphers -= cipher_blacklist  # Remember this is mostly pseudocode
    _DEFAULT_CIPHERS = ':'.join(ciphers)
```

**Comment by Lukasa** [comment]
I feel like the risk here is pretty small, all things considered.

**Comment by t-8ch** [comment]
We should also reuse this in `contrib/pyopenssl.py`

**Comment by dstufft** [comment]
I almost think that trying to do something like that is getting too clever for our own good. Yea if someone uses an old urllib3 then they'll get possibly less secure ciphers, if someone uses an old requests they'll get possibly an insecure signing cert, or really any possible change like that.

I agree with @Lukasa that the risk is small and I think that the risk of being clever is greater.
