### ISSUE TITLE
Retry history (or maybe request history via retries?)

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#576]
Would be great if we have somekind of retry request history in the retry object. There's a TODO for this in the code.

Ideally we'd do this by replacing our observed errors counter with a list of objects describing the respective requests.

If we end up doing a request history (and requests have a retry attached per #578), then this issue would be obsolete.

Related: #185 which adds redirect_history, but we should be able to do better now that we've refactored some of the code.

**Comment by sigmavirus24** [comment]
I might take a look at this sometime in the future. Of course if someone wants to get involved in urllib3 we can work together on it if you'd like.

**Comment by nateprewitt** [comment]
This should be resolved in #848.
