### ISSUE TITLE
README: "You might already be using urllib3!" search is broken

### ISSUE THREAD

**Issue by cvrebert** [shazow/urllib3#577]
https://github.com/shazow/urllib3/blob/master/README.rst#you-might-already-be-using-urllib3 links to https://sourcegraph.com/search?q=package+urllib3 , which returns zero results since it seems to be searching within someone's GitHub repo that happens to be named "package".

**Comment by shazow** [comment]
Yeaaaa I've bugged @samertm at Sourcegraph about this. Turns out the feature is temporarily disabled, will be back eventually.

@cvrebert Do you have a better query/link we could use instead?

**Comment by cvrebert** [comment]
No, sadly.

**Comment by shazow** [comment]
[:(](http://www.sadtrombone.com/)

**Comment by sigmavirus24** [comment]
This still seems to be disabled :(

**Comment by shazow** [comment]
:cry:

**Comment by nateprewitt** [comment]
Looks like this section was removed in #920. Not sure if that would close this ticket out, or bring up reintroducing it elsewhere in the docs when (if?) it's fixed.

**Comment by nateprewitt** [comment]
Looks like this section was removed in #940. Not sure if that would close this ticket out, or bring up reintroducing it elsewhere in the docs when (if?) it's fixed.
