### ISSUE TITLE
Attach last retry object to response before returning

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#578]
Would be swell if our `response.HTTPResponse` object had a `retries` attribute (or maybe a better name?) which contained the latest (immutable) Retry object.

At least that way users can get some idea of how many retries occurred (derived from their original retries configuration). Bonus points if we store more useful data in the retry object for the user to inspect without having to do math.

This attachment could happen right before [returning the response here](https://github.com/shazow/urllib3/blob/431e80619efb73201f483467a68ee0c8a215e5d3/urllib3/connectionpool.py#L650).

(Mildly related to #576.)

**Comment by shazow** [comment]
Ping @wolever, he expressed some interest in doing this. :)

**Comment by nateprewitt** [comment]
This should be resolved in #848.
