### ISSUE TITLE
cert_reqs default to 'CERT_REQUIRED' when ca_certs is set

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#579]
Is this a reasonable change? Would make our boilerplate a little simpler/less crufty.

```diff
- http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
+ http = urllib3.PoolManager(ca_certs=certifi.where())
```

**Comment by shazow** [comment]
@Lukasa @sigmavirus24 @dstufft Thoughts on this?

**Comment by sigmavirus24** [comment]
Consider me :+1: 

That said, we should allow people to use alternate values if they know they need it.

**Comment by shazow** [comment]
Yea, it would be merely a default. Override would work as before.

**Comment by dstufft** [comment]
I'm +1

**Comment by Lukasa** [comment]
:+1: :shipit:
