### ISSUE TITLE
Drop/deprecate 3.2 support

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#591]
Requests has long since dropped support for Python 3.2, and now cryptography wants to do so as well. The 3.2 usage numbers aren't high, so I propose we should abandon our support for Python 3.2 by removing it as a test target from Tox and Travis.

**Comment by shazow** [comment]
No objections here. Will need to update the README too.

**Comment by sigmavirus24** [comment]
:+1: from me

**Comment by nateprewitt** [comment]
This was resolved by #787.
