### ISSUE TITLE
Cut a new release for requests-2.6.0

### ISSUE THREAD

**Issue by ralphbean** [shazow/urllib3#592]
Good morning.  :)  This is just like in #554 and the times before.

It seems that requests bundled another cut of urllib3 for the 2.6.0 release but there's no corresponding urllib3 release on pypi for the unbundlers out there.

https://github.com/kennethreitz/requests/commit/9adaae6

```
  $ git log -p v2.5.3..v2.6.0 --reverse -- requests/packages/urllib3
  commit a0790f37b762ec737b2a4a13c167aad2defa8575
  Author: Ian Cordasco <graffatcolmingov@gmail.com>
  Date:   Tue Mar 10 19:34:34 2015 -0500
  
      Update urllib3 to 43b5b2b452e4344374de7d08ececcca495079b8d
```

**Comment by shazow** [comment]
Acknowledged.

Hmm, any thoughts on v1.10.3 or v1.11? ([changes](https://github.com/shazow/urllib3/blob/master/CHANGES.rst)]

1.10.2 had a regression which got pulled back from pypi, so I kinda wanna make it 1.10.3.

**Comment by Lukasa** [comment]
+1 to 1.10.3.

**Comment by shazow** [comment]
Tagged and released: https://github.com/shazow/urllib3/tree/1.10.3

**Comment by ralphbean** [comment]
Thanks @Lukasa, @shazow!
