### ISSUE TITLE
Cut a new release for requests-2.6.2

### ISSUE THREAD

**Issue by ralphbean** [shazow/urllib3#600]
Requests 2.6.2 bundled urllib3 at commit 7b82da0fa3a13514d11a863e379e7541d0ec46ef.

Could you cut a 1.10.4 release to match them like in #592?

**Comment by shazow** [comment]
One of the benefits of requests vendoring urllib3 is that requests would ship with a more cutting-edge version of urllib3 that may be considered unstable for urllib3 and keep a faster pace. I suspect the last couple of releases of urllib3 were a mistake, as those versions proved to be ridden with regressions. :(

The plan right now is to push out another minor fix release once #599 is merged, but after that we're going to need to decide whether to slow down the urllib3 release process to what it was before or to fully synchronize the cadence of requests with urllib3 which defeats the point of vendoring. I'm sure distro maintainers would be far happier with the latter, but I'm generally happier with the former. :)

/cc @Lukasa @sigmavirus24

**Comment by Lukasa** [comment]
I think slowing down urllib3's release process is a good idea. Requests is also going to try to be a bit less aggressive with urllib3 releases where we can, per our shiny new release policy.

**Comment by shazow** [comment]
@sigmavirus24 Who would be a good person to verify that all the chunking stuff is working as desired now? Or should we just push out a new Requests release before I cut a urllib3 release again? :P

**Comment by shazow** [comment]
Tagged and pushed v1.10.4 which will be used for Requests v2.7.0.
