### ISSUE TITLE
Unit tests fail with exception gaierror

### ISSUE THREAD

**Issue by ddriddle** [shazow/urllib3#610]
When I run the unit tests for urllib3 v1.10.2 or the latest version (master) in GitHub I receive the following error:
```
urllib3/test$ nosetests
S.............................E.....................................S..S....................................Exception in thread Thread-11:
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/services/scratch/ddriddle/src/urllib3/dummyserver/server.py", line 88, in run
    self.server = self._start_server()
  File "/services/scratch/ddriddle/src/urllib3/dummyserver/server.py", line 75, in _start_server
    sock.bind((self.host, 0))
  File "/opt/rh/python27/root/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -2] Name or service not known
```
The problem seems to be that my system does not support IPv6 but socket.has_ipv6 returns true.

**Comment by shazow** [comment]
Mmm strange. Any ideas for how to fix this?

**Comment by ddriddle** [comment]
Yes I do. See pull request #611.

**Comment by ddriddle** [comment]
What needs to happen is to catch the gaierror then bind with an IPv4 address. Of course this breaks test_connectionpool.py:601:test_source_address since it also depends on socket.has_ipv6 so it is necessary to communicate to that function that it should not perform IPv6 tests. My solution fixes the problem but their maybe a more elegant solution.
