### ISSUE TITLE
UnicodeEncodeError handling gzipped responses on Google App Engine

### ISSUE THREAD

**Issue by agfor** [shazow/urllib3#616]
https://github.com/braintree/braintree_python/issues/53 originally reported the issue. It's due to using requests 2.6.1+, which pulled in a version of urllib3 including f21c2a2b73e4256ba2787f8470dbee6872987d2d, which causes the problem.

I am able to reproduce using app engine development mode when switching https://github.com/agfor/braintree-python-appengine to use requests 2.6.1+ and un-commenting out the development mode enabling code in main.py.

**Comment by Lukasa** [comment]
This issue has also been opened as kennethreitz/requests#2595. For now I'm closing this version to centralise over on requests: we'll reopen here if it turns out that requests 2.7.0 does not resolve the problem.

**Comment by agfor** [comment]
I believe this was actually a duplicate of https://github.com/shazow/urllib3/issues/441 and was fixed by 22a9713fab2ed831204711906a974c3beba3319e.
