### ISSUE TITLE
API to use custom SSLContexts in VerifiedHTTPSConnection/HTTPSConnectionPool

### ISSUE THREAD

**Issue by divergentdave** [shazow/urllib3#617]
I'd like to request an API for passing a custom `SSLContext` to higher level APIs, so that it eventually gets passed to `ssl_.ssl_wrap_context`. My motivating use case is that I'd like to selectively re-enable RC4 when talking with poorly configured servers. (see #551) It seems like [this](https://gist.github.com/paxswill/5ed7273059b34e90b184) is currently the best way to enable old ciphers, but I think it would be preferable to create a `SSLContext` using `_ssl.create_urllib3_context`, and then pass that to the `HTTPSConnectionPool` constructor.

To that end, I propose the following API change. A `context` keyword argument is added to the constructor of `VerifiedHTTPSConnection`. If present, this `SSLContext` is passed to `ssl_.ssl_wrap_context`. If a `context` is passed to `HTTPSConnectionPool`, it will be passed through to `VerifiedHTTPSConnection`.

Does this approach sound good? If so I'd be happy to start a PR. I see there are tests and docs to update; is there anything else I should look at?

**Comment by konklone** [comment]
:+1: RC4 is deprecated and dying, but is still present in enough places that savvy clients should be able to re-enable it when necessary without introducing hacks or seeking urllib3 alternatives.

**Comment by Lukasa** [comment]
This should already be being worked on in #507. =)

**Comment by konklone** [comment]
Nice! Also, glad to have generated another instance of "be being" in the world.

**Comment by Lukasa** [comment]
Yeah, it's definitely an unusual turn of phrase. :grin:

**Comment by shazow** [comment]
@divergentdave @konklone We would very much appreciate if you can help review the code in #507 and let us know if this addresses your problems and whether you have ideas for making that feature better. :)

Consider yourselves our key stakeholders so your opinion here matters a lot.
