### ISSUE TITLE
Change source_address every request ?

### ISSUE THREAD

**Issue by cattleyavns** [shazow/urllib3#629]
Hi everybody, I'm writting a proxy server with urllib3 that change source_address every time it open a request, for example:

- Request http://example.com/1.gif, source_address="192.168.1.3"
- Request http://example.com/2.gif, source_address="192.168.1.110"
- Request http://example.com/3.gif, source_address="192.168.1.3"
- Request http://example.com/4.gif, source_address="192.168.1.110"

...

Again and again, because I have cable and Wifi network, different IP, I want to do load balancing to improve my network speed and use as much bandwidth as possible, problem is how I can change source_address every request create, please me some tips to finish this problem.

Here is my test code, not even a proxy:

import urllib3
http = urllib3.PoolManager(num_pools=10, source_address=('192.168.1.110', 0))
http.source_address = "192.168.1.3"

r = http.urlopen('GET', 'http://www.ghacks.net/ip/')
print(r.data.decode('utf-8'))
print(http.headers)
print(r._original_response.msg)

The line "http.source_address = "192.168.1.3"" seem do nothing, the IP show still 192.168.1.110's IP.

It is possible because there is software already did that, dispatch-proxy in NodeJS but it is not perfect, at least there is no HTTPS support so I decide to write my own.

Thank!

**Comment by Lukasa** [comment]
The *simplest* way to do this is to use one PoolManager per source address. This is important: we mustn't accidentally use a connection with a different source address, and right now we don't include the source address in the uniqueness tuple for a connection. So you could, in this case, simply create two pool managers. This will be just as efficient in terms of the number of connections you use as any other solution to this problem.

Functionally, if @shazow feels like having some kind of extension here, we could do a few other things:

1. Add source address to the connection hash tuple, making it part of the connection pooling logic, and then allow an explicitly specified source address per connection.
2. Have the `PoolManager` automatically manage connection pools for different source addresses.

**Comment by shazow** [comment]
That's right. PoolManager manages its own pool of connections, and changing the specification of a connection mid-operation will not guarantee predictable results.

As @Lukasa said, the best way to do this it to create a pool manager for each source_address and load balance between them. See this comment for code examples and related discussion: https://github.com/shazow/urllib3/pull/376#issuecomment-41003161

We discussed the proposals you mentioned, Lukasa, and decided against them at the time. Could re-open the discussion if anyone feels strongly.

@cattleyavns If you'd be up for a small contribution, adding a recipe like this into our docs would be very appreciated. :)
