### ISSUE TITLE
[Small contribution] A way to combine urllib3 with PySocks and finally socks support

### ISSUE THREAD

**Issue by cattleyavns** [shazow/urllib3#630]
Hi!
I found a way to make urllib3 work with pySocks, I think we just need to modify a little bit to merge it into urllib3:

We will need chardet 2 for requests module:
pip install chardet urllib3
And pySocks for sure:
pip install pySocks
You can try socks proxy with Bitvise SSH Client, change the port 10080 to whatever you want. Hope this topic will at least help people who only want to use Socks with urllib3 or better will have socks5 built-in urllib3. Thank urllib3's author for making such a great library.

```
import time
import requests
from requests.packages.urllib3.connection import HTTPConnection as HTTPConnection_
import socks # https://github.com/Anorov/PySocks

def _init_hook(self, *args, **kw):
	self.socks = kw.pop('socks', None)
	self._init_org(*args, **kw)

def _new_conn_hook(self):
	socks_addr, socks_port = self.socks
	conn = socks.create_connection((self.host, self.port),
		proxy_type=socks.SOCKS5,
		proxy_addr=socks_addr,
		proxy_port=socks_port,
		timeout=self.timeout)
	return conn

HTTPConnection_._new_conn_org = HTTPConnection_._new_conn
HTTPConnection_._new_conn = _new_conn_hook

HTTPConnection_._init_org = HTTPConnection_.__init__
HTTPConnection_.__init__ = _init_hook

class SocksAdapter(requests.adapters.HTTPAdapter):
	def __init__(self, socks_addr, socks_port, *args, **kwargs):
		self.socks = (socks_addr, socks_port)
		super(SocksAdapter, self).__init__(*args, **kwargs)

	def get_connection(self, url, proxies=None):
		self.poolmanager.connection_pool_kw['socks'] = self.socks
		conn = super(SocksAdapter, self).get_connection(url, proxies)		
		return conn

def main():
	sess = requests.Session()
	sess.adapters['http://'] = SocksAdapter("127.0.0.1", 10080)
	url = "http://www.ghacks.net/ip/"
	r = sess.get(url)
	print((r.content))

if __name__ == '__main__':
	main()
```

**Comment by shazow** [comment]
Very interesting, thank you!

Some suggestions for making this more native-urllib3:

Create a subclass of `HTTPConnectionPool` which overrides the necessary methods, maybe call it `SocksHTTPConnectionPool`. Then we can add that to our `contrib` submodule that people can import and use in place of the normal `HTTPConnectionPool`.

Will this also work with HTTPS?

**Comment by cattleyavns** [comment]
I think only HTTP request will work, I will try to modify the code because HTTPS is really needed these days.

**Comment by shazow** [comment]
Obsoleted by #762
