### ISSUE TITLE
is_fp_closed should handle non-file-like body

### ISSUE THREAD

**Issue by xEtherealx** [shazow/urllib3#649]
is_fp_closed doesn't handle string-type bodies.  It checks whether obj.fp is None, but should probably also check whether obj is None.

**Comment by Lukasa** [comment]
I don't really think I agree. `is_fp_closed` is pretty strictly defined to expect a file-like object, down to being tested to only function on file-like objects. There's an explicit test that non-file objects shouldn't work.

I presume the *actual* problem is that you're trying to use `HTTPResponse.stream()` and finding that it explodes. Is that right?

**Comment by Lukasa** [comment]
Ah, I see, this is actually a follow-on of kennethreitz/requests#2635.

**Comment by xEtherealx** [comment]
I see, followed up there and you can probably go ahead and close this.
