### ISSUE TITLE
Problems with documentation TOC

### ISSUE THREAD

**Issue by Disassem** [shazow/urllib3#663]
Several `.. toctree::` commands in index.rst make following problems:
- On page security.html Previous topic is Contrib Modules instead of PoolManager
- Page Collections didn't include in "Next topic chain".

`security` included in main toctree twice (begin of index.rst) but `exceptions` not once.

Also there is one build warning: "urllib3\docs\security.rst:117: WARNING: duplicate label pyopenssl, other instance in urllib3\docs\contrib.rst".

**Comment by shazow** [comment]
@Disassem Any fixes/improvements to the docs are super-appreciated. Would you like to do a PR? :)

**Comment by Disassem** [comment]
Just now I don't know how to fix it. I'll think about this :)
