### ISSUE TITLE
Tell real URL from response

### ISSUE THREAD

**Issue by rr-** [shazow/urllib3#665]
In urllib2's HTTPResponse we have `.geturl()` that retrieves the actual URL that ended up being downloaded after all the redirections.

I saw no such thing in urllib3's documentation, nor any relevant methods in the actual code (as seen with `dir()`). Trying to get `response.getheader('host')` didn't help either.

This is especially important in scenarios involving constructing absolute URLs from relative links inside HTML pages.

**Comment by shazow** [comment]
I agree we need something like that, #576 is the same idea. :)
