### ISSUE TITLE
stream() "contract" changed in 1.10.3, can now raise IncompleteRead

### ISSUE THREAD

**Issue by jmoldow** [shazow/urllib3#673]
In 1.10.2, `HTTPResponse.stream()` always called `HTTPResponse.read()`. This method catches all `HTTPException` (including `IncompleteRead`), and re-raises them as `ProtocolError`.

In 1.10.3 and 1.10.4, `HTTPResponse.stream()` may call `HTTPResponse.read_chunked()` instead. This method may (via the `_update_chunk_length()` helper method) raise `IncompleteRead`. This exception will not be caught, and will be raised out of the call to `HTTPResponse.stream()`.

A project I work on recently upgraded to requests 2.7.0 (which has vendored urllib3 1.10.4), and has started to see crashes because of `IncompleteRead` being raised from `HTTPResponse.stream()`. We previously would catch `RequestException`, as requests would catch `ProtocolError` (but not `IncompleteRead`) and re-raise a `ChunkedEncodingError` in `Response.iter_content()`.

I'm not familiar with `urllib3.util.retry`, but at a glance it also seems like this change would negatively affect the `_is_read_error()` helper method.

**Comment by shazow** [comment]
Hm sorry about that. Are you proposing a specific fix, or is this a request for a major version bump?

**Comment by sigmavirus24** [comment]
The potentially simplest way to handle this is to have our own IncompleteRead error subclass ProtocolError and wrap the IncompleteRead from httplib. (Assuming I'm understanding the problem correctly that we're no catching httplib.IncompleteRead)

**Comment by kingsawyer** [comment]
I like sigma's suggestion. It preserves the information of the exception while allowing clients to continue to catch the same set of exceptions.

**Comment by sigmavirus24** [comment]
Thoughts @shazow?

**Comment by jmoldow** [comment]
@shazow I wasn't entirely sure if this was intentional or not. If it's not intentional, I would propose making it so that `read_chunked` catches the same set of exceptions that `read` does. Then a major version bump is not necessary.

@sigmavirus24's solution would work for this particular exception, though I don't know if there are other low-level exceptions that `read_chunked` may raise that `read` catches. It may also be possible to refactor the try/except in `read` into a context manager that is also used by `read_chunked`.

**Comment by shazow** [comment]
Yea we definitely shouldn't be leaking httplib exceptions.

**Comment by Lukasa** [comment]
+1, we shouldn't leak if we possibly can.

**Comment by jmoldow** [comment]
Thanks for helping me get this fixed.

@shazow Since this was a regression within the 1.10.x series, should a new release be made with this fix?

**Comment by shazow** [comment]
@jmoldow Philosophically I agree with you that we should cherrypick fixes and do bugfix releases for prior minor versions, but generally that's too much work for our volunteer effort here so we typically wait for the next release which should be very soon. Let's say next week? If we don't see a release early next week, please bug me. :)
