### ISSUE TITLE
setup.py extra_require for certifi, pyopenssl, other?

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#677]
Try to setup as many of https://urllib3.readthedocs.org/en/latest/security.html#security's recommended dependencies as possible.

Maybe something like `pip install urllib3[secure]`

**Comment by Lukasa** [comment]
<3

**Comment by shazow** [comment]
Someday would be nice to make that the default, and maybe have a `urllib3[minimal]` but that's tricky since pyopenssl requires several system packages (build-essential, libffi-dev, and libssl-dev).

/cc @sigmavirus24

**Comment by cattleyavns** [comment]
On Windows or Lubuntu we will have to compile cffi and crytography if we want to use pyOpenSSL, I wonder if pyOpenSSL can work without those twos.. ? To be honest I don't like compile anything but Python native.

**Comment by sigmavirus24** [comment]
@cattleyavns pyOpenSSL cannot work without cryptography which in turn cannot work without cffi.

**Comment by Lukasa** [comment]
However, cryptography ships windows wheels that require no compilation on that platform.
