### ISSUE TITLE
urllib3 1.11 does not provide the extra 'secure'

### ISSUE THREAD

**Issue by dethi** [shazow/urllib3#684]
I tried with Python 2.7 and 2.6 inside different virtualenv.

```bash
pip install 'urllib3[secure]'
```

**Comment by shazow** [comment]
@sigmavirus24 maow?

**Comment by Lukasa** [comment]
Looks like the fancy-pants versioning doesn't always work. What version of setuptools is being used here?

**Comment by shazow** [comment]
I'm getting the same thing with pip 7.1: `urllib3 1.11 does not provide the extra 'secure'`

**Comment by dethi** [comment]
```
pip 7.1.0
setuptools 18.0.1
```

**Comment by dethi** [comment]
@Lukasa I agree with you, **requests** doesn't use the versioning and it is working fine
https://github.com/kennethreitz/requests/blob/master/setup.py#L71-L73

**Comment by Lukasa** [comment]
Let's put up the @dstufft signal!

**Comment by shazow** [comment]
✳️🚨✳️

**Comment by sigmavirus24** [comment]
@dethi did you try `urllib3[security]`? You're examples say `secure` which is not the name of the extra.

**Comment by sigmavirus24** [comment]
Ah nevermind. Looked at the wrong link. secure is right.

**Comment by dstufft** [comment]
This appears to be a setuptools bug, the ``pkg_resources.Distribution`` and ``pkg_resources.DistInfoDistribution`` are saying that there is an extra named ``secure_python_version_2.7_``. This is affecting both the sdist and it's been "baked" in to produce a broken wheel as well. It's also producing a wheel that thinks the extra name is ``secure;python_version<="2.7"``.

So I would suggest either ditching the conditional extra stuff or contacting setuptools to see about making it work.

**Comment by sigmavirus24** [comment]
I figured it out. This is because I used `"` in the environment marker instead of `'`. >_<

Pull Request on the way

**Comment by sigmavirus24** [comment]
Or at least the wheel metadata is different. Still not able to do `pip install -e .[secure]`

**Comment by sigmavirus24** [comment]
After doing `python setup.py bdist_wheel` and unpacking the wheel, it looks like:

```
    "run_requires": [
        {
            "environment": "extra == \"secure; python_version<='2.7'\"",
            "requires": [
                "pyOpenSSL",
                "ndg-httpsclient",
                "pyasn1",
                "certifi"
            ]
        },
        {
            "environment": "extra == \"secure; python_version>'2.7'\"",
            "requires": [
                "certifi"
            ]
        }
    ],
```

Still isn't exactly correct in the `metadata.json` file in the wheel.

**Comment by shazow** [comment]
Any idea if this is fixable, or should we remove the install tag?

**Comment by dethi** [comment]
Have you try like this?

```
extras_require={
          'secure': [
              'pyOpenSSL;python_version<="2.7"',
              'ndg-httpsclient;python_version<="2.7"',
              'pyasn1;python_version<="2.7"',
              'certifi',
          ],
      },
```

**Comment by sigmavirus24** [comment]
That does not work. Since this is a bug we will have to provide one extra that installs everything even when it's unnecessary.

On August 7, 2015 4:21:53 AM CDT, Thibault Deutsch <notifications@github.com> wrote:
>Have you try like this?
>
>```
>extras_require={
>          'secure': [
>              'pyOpenSSL;python_version<="2.7"',
>              'ndg-httpsclient;python_version<="2.7"',
>              'pyasn1;python_version<="2.7"',
>              'certifi',
>          ],
>      },
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/shazow/urllib3/issues/684#issuecomment-128650830

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sigmavirus24** [comment]
@shazow alternative: What if we provide `urllib3[sni]` which we document as only for people using `urllib3` on Python 2.7.8 or lower. Then we provide another for certifi. I'm not sure what to name the second one though.
