### ISSUE TITLE
SSLError when reusing connectionpool after a ReadTimeoutError.

### ISSUE THREAD

**Issue by thomascellerier** [shazow/urllib3#687]
I have a `HTTPSConnectionPool` that throws a read time out, then (in a `__del__`) I reuse the same connection (created with urllib3.connection_from_url), then in case of error I do some teardown using the same connection and I get this error when reusing the connection from url object.
`urllib3.exceptions.SSLError: Underlying socket connection gone (_ssl.c:1568)`

reproduce with something like this:

```Python
conn = urllib3.connection_from_url(my_url)
try:
    conn.request('POST', '/mypath', body=mybody, headers=myheaders, timeout=10, retries=False)
except urllib3.ReadTimeoutError:
    conn.request('DELETE', '/someobect', headers=myheaders,  timeout=10, retries=False)
```

The read time out is due to an internal server error and the following requests to the same server work as expected. A workaround for now is to create a new connection object for each request.

**Comment by thomascellerier** [comment]
I realised this might be because I am executing code in a `__del__`.
I tried to make a minimal example to reproduce. The following example doesn't give me the same error but it does give me an error.

```Python
import urllib3
import gc
urllib3.disable_warnings()

url = 'https://192.168.111.46'

class MyObj:
    def __init__(self):
        self.conn = urllib3.connection_from_url(url)

    def do(self):
        r = self.conn.request('POST', '/mypath', headers={'Content-Type': 'application/json'}, body='{"my":"body"}', timeout=3, retries=False)
        print(r.data)

    def dont(self):
        r = self.conn.request('DELETE', '/someobject', timeout=3, retries=False)
        print(r.data)

class MyParentObj:
    def __init__(self):
        self.myobj = MyObj()

    def do(self):
        self.myobj.do()

    def __del__(self):
        self.myobj.dont()

myparentobj = MyParentObj()
myparentobj.do()
```

results in:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 618, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    myparentobj.do()
  File "test.py", line 24, in do
    self.myobj.do()
  File "test.py", line 12, in do
    r = self.conn.request('POST', '/mypath', headers={'Content-Type': 'application/json'}, body='{"my":"body"}', timeout=3, retries=False)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/request.py", line 149, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 607, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 378, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='192.168.111.46', port=None): Read timed out. (read timeout=3)
Exception ignored in: <bound method MyParentObj.__del__ of <__main__.MyParentObj object at 0x7f7935909518>>
Traceback (most recent call last):
  File "test.py", line 27, in __del__
  File "test.py", line 16, in dont
  File "/usr/local/lib/python3.4/dist-packages/urllib3/request.py", line 68, in request
  File "/usr/local/lib/python3.4/dist-packages/urllib3/request.py", line 89, in request_encode_url
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 778, in _validate_conn
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 227, in connect
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2199, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2132, in _find_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by shazow** [comment]
What version of urllib3 are you using? I believe we fixed this in the latest release.

**Comment by thomascellerier** [comment]
show urllib3
```
$ pip3 show urllib3
---
Name: urllib3
Version: 1.11
Location: /usr/local/lib/python3.4/dist-packages
Requires:
```

**Comment by shazow** [comment]
Hm yea that's not great.

@jlatherfold Would you be up for taking a look?

**Comment by sigmavirus24** [comment]
So doing things in `__del__` is generally a very very bad idea. That happens when the object in question is garbage collected. When that happens is not necessarily deterministic. What you're seeing (I believe) is the result of something else having been garbage collected long before `myparentobj.__del__` is called.

Also, you're getting a ReadTimeout before Python ignores the exception in `myparentobj.__del__`. That extended traceback is misleading but is telling you exactly what happened. There was a ReadTimeout so we raise the appropriate exception. Then your object is gc'd but other objects it needs were gc'd before it was gc'd so you're getting a totally different exception.

**Comment by shazow** [comment]
Ah that's a good point, I totally missed the part about `__del__`. Can you reproduce this if you have a PoolManager that lives outside of the object? (You can pass it in if you'd like)

The PoolManager will handle re-using connections for you, so you shouldn't need to worry keeping this extra state yourself.

**Comment by thomascellerier** [comment]
Shouldn't the my object hold a strong reference to the connection pool, preventing it from being garbage collected before? And this one in turn should have a strong reference to the socket object.
My workaround right now is to re-create the connection pool object at the start of the parent object's `__del__` method.

**Comment by thomascellerier** [comment]
Btw to give some context to what I am trying to achieve. It is some test library that is talking to a REST API and needs to do teardown at the end of the test. Using `__del__` allows the teardown to take basically zero lines of code. So the the test code POSTs some objects during the test execution, keeping a list of created objects in memory, and they are automatically DELETEd after the test is done running.

**Comment by shazow** [comment]
@thomascellerier Right now you're trying to replicate what PoolManager already does, including handling edge cases like this. Can you reproduce this by using a PoolManager that lives outside of your objects' lifetimes?

You can work around most edge cases by re-creating a connection pool every time you make a request, but that kind of defeats the point of connection pools. :)

**Comment by thomascellerier** [comment]
Ah I suppose I could make the pool manager a module variable. The thing is I wanted to restrict access to a single URL per object so ConnectionPool seemed like a better fit. I will try using PoolManager.

**Comment by sigmavirus24** [comment]
> Shouldn't the my object hold a strong reference to the connection pool, preventing it from being garbage collected before? And this one in turn should have a strong reference to the socket object.

That's not what is breaking. If you were to look at [the line referenced][] you'll see why importlib is in your traceback. The datetime module has already been garbage collected. When we do `datetime.date.today()` you get the exception which prevents your test clean up from working. That said, it's unclear (to me) why recreating the connection pool would fix that particular problem. Then again, if you are reimporting something in that method, that would explain it.

> Btw to give some context to what I am trying to achieve. It is some test library that is talking to a REST API and needs to do teardown at the end of the test. Using __del__ allows the teardown to take basically zero lines of code. So the the test code POSTs some objects during the test execution, keeping a list of created objects in memory, and they are automatically DELETEd after the test is done running.

So this is what test fixtures are for, not `__del__` methods. You should examine how other test libraries do proper test fixtures (`setUp`, `tearDown`, `setUpClass`, `tearDownClass` in `unittest` for example) and mimic that. Please don't abuse `__del__` for this, it will only lead to headaches and make your test library very buggy on alternative implementations of Python with different garbage collection systems (e.g., PyPy, Jython, etc.).

[the line referenced]: https://github.com/shazow/urllib3/blob/3441e8ed91e5ab86a37d411ba88421f7a4d17137/urllib3/connection.py#L227

**Comment by shazow** [comment]
> Ah I suppose I could make the pool manager a module variable.

module variable is fine, or you can pass in a reference to your pool when you create the object.

But yea, +1 to what @sigmavirus24 said. Avoid using `__del__` as it can be fairly unpredictable, unintuitive, and implementation-specific (JPython might behave completely differently than PyPy, for example).

I'm closing this for now, but feel free to re-open if you're able to reproduce this despite the suggestions. :)

**Comment by thomascellerier** [comment]
Ok, I found a solution based on `contextlib` `ExitStack` instead of using `__del__`. Objects needing teardown can simply register to that exit stack.Thanks for the help.
