### ISSUE TITLE
connectionpool.py does not respect disable_warnings()

### ISSUE THREAD

**Issue by rgcosma** [shazow/urllib3#689]
On a Centos & system, python-urllib3-1.10.2-1.el7_1.noarch
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made.
Going to said line, there is indeed an extraneous  if not conn.is_verified warnings.warn

**Comment by shazow** [comment]
Why is it extraneous?

`disable_warnings()` works by adding a filter to Python's warning system: https://github.com/shazow/urllib3/blob/master/urllib3/__init__.py

**Comment by rgcosma** [comment]
What led me to this: I'm trying to use salt-cloud with the vmware "driver", and on line 91 I see it does have said disable_warnings(), but when connecting to a vcenter, I still get the warning
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py

**Comment by shazow** [comment]
Do you know that it's working? I see an `except Exception:` so for all you know, it's failing to import never runs. :)

Anyways, can you reproduce this with just urllib3? If not, then it's likely a bug in salt or related to your distro packaging of it. Some distros rewrite requests' import paths to unvendor urllib3 and that tends to break things.

**Comment by rgcosma** [comment]
Well I removed the try/except, and it's the same warning so it wasn't failing there. Also, the file being imported is the one mentioned, and it came from the Centos .rpm
For now I just commented out the line in connectionpool.py

**Comment by shazow** [comment]
Okay, but there's nothing we can do if you can't reproduce the bug with just urllib3 unfortunately. Please re-open the issue if you can do that.

**Comment by shazow** [comment]
Btw my bet is that it's related to the distro's unvendoring stuff. Somewhere there are two copies of the HTTPWarning class and the disable_warnings is referring to the wrong one.

**Comment by dmig** [comment]
I face same issue. Here is a testcase:
```python
# coding: utf-8
import requests
import logging

logging.basicConfig(
    level=logging.DEBUG
)

session = requests.Session()
# doesn't matter which one to use
# requests.packages.urllib3.disable_warnings()
requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.HTTPWarning)
session.mount('http://', requests.adapters.HTTPAdapter(max_retries=1))

session.proxies = {
    'http': 'http://138.186.86.6:8080' # bad proxy, causes ConnectTimeout
}

response = session.get('http://google.com', allow_redirects=False, timeout=(1, 2))
```

@shazow, if you say it's not requests' problem, whats wrong with this testcase?

**Comment by dmig** [comment]
Tests show, that `warnings.simplefilter()` has no effect on `logging.warning()`. So, `urllib3.disable_warnings()` is simply nonfunctional.

Solutions:
- use `warnings.warn('message', exceptions.HTTPWarning)` instead of `logging.warning()`
- lower severity levels for insignificant warnings

**Comment by Lukasa** [comment]
@dmig Uh...what?

This original issue was to do with the InsecureRequestWarning. Your issue has nothing to do with that because no such warning exists in your example. I presume your concern is this:

```
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x10c296e90>, 'Connection to 138.186.86.6 timed out. (connect timeout=1)')': http://google.com/
```

This is not a warning, it's a log at warning level. It exists at warning level because it is potentially a signal of a genuine problem, and users that encounter connection timeouts likely want to know about them in their logs.

So I don't think you're seeing the same issue as the original poster is. `disable_warnings` is not supposed to change the log level. `disable_warnings` is not non-functional, it does exactly what it's supposed to do.
