### ISSUE TITLE
Preliminary SOCKS proxy support

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#690]
We've had some attempts to get this going over the years, this is the umbrella issue tracking these attempts and the goal is to get somekind of baseline support for SOCKS proxies into the urllib3 before we aspire towards more advanced features.

Related attempts (should be a great reference if anyone wants to tackle this):

- https://github.com/shazow/urllib3/pull/68 (original attempt using socksipy; outdated code)
- https://github.com/shazow/urllib3/pull/284 (another attempt using pysocks—a more up-to-date fork of socksipy; outdated code)
- https://github.com/shazow/urllib3/pull/486 (most recent attempt, refactored version of pysocks attempt)
- https://github.com/shazow/urllib3/pull/692 (another recent attempt, but mixes pysocks logic into the connectionpools)
- https://github.com/shazow/urllib3/issues/630 (recipe for wrapping pysocks)
- https://github.com/shazow/urllib3/pull/762 (@lukasa)

Suggestions:

- SOCKS proxy support should ideally be built into ProxyManager (or a similar manager if combining is not possible).
- Should use pysocks (unless there's anything newer?). Avoid vendoring if possible, we can enable support when pysocks is installed (also include a `urllib3[socks]` install tag which will pull in the dependency).

To complete this issue, the feature needs to be documented and have full test coverage so that it can be merged into urllib3 core (or at least contrib).

**Comment by JeremyRand** [comment]
As mentioned in https://github.com/shazow/urllib3/pull/486#issuecomment-128644883 , I can put $100 toward this via BountySource.  If I do so, BountySource would release the funds when the GitHub issue in question is closed -- given that, is this issue the correct one to put the bounty on?

**Comment by shazow** [comment]
@JeremyRand Yes, I think this would be best. Keep in mind, this issue is just for baseline SOCKS support—it doesn't necessarily include your specific requirements, though I suspect all those things should Just Work by default.

**Comment by shazow** [comment]
Ping to everyone who expressed interest in SOCKS support for urllib3, we're going to try raise a bounty for this issue here, please contribute: https://www.bountysource.com/issues/25474088-preliminary-socks-proxy-support

@Ofekmeister @zhao-ji @bpowers @laike9m @eordano @YS- @9b @ctoth @aleks-mariusz @josegonzalez @fmoo @itdaniher @cattleyavns @a3nm @jbrockmendel — I hope some of you will to the bounty, and maybe ask your employer if they'd be willing to help with this too?

And of course, contributors with prior attempts — @anorov @schlamar @foxx 

Ideally one of our original contributors will claim this. If we can get enough funding for at least a week of full-time work, I'll be willing to take this issue on myself.

**Comment by JeremyRand** [comment]
I just sent $50 via the Namecoin BountySource account; I'm in the process of buying some more BTC to fund my BountySource account, once I've done that I'll send the other $50.

**Comment by shazow** [comment]
@JeremyRand Thank you, much appreciated! :custard:

**Comment by Lukasa** [comment]
Depending on how my time pans out, I may consider taking this one on. It's annoying me now. ;)

**Comment by zhao-ji** [comment]
I've writen a socks5 proxy, i'll try it!

**Comment by Anorov** [comment]
I have made a PR here https://github.com/shazow/urllib3/pull/692 though no tests have been added yet.

**Comment by JeremyRand** [comment]
Remaining $50 posted as promised.

**Comment by jbrockmendel** [comment]
I'm not likely to be helpful on the coding front, but have a handful of socks5 proxies set up that I'm happy to run tests on.

**Comment by shazow** [comment]
Thanks. :) If anyone is up for testing out #692 and giving feedback, that'd be great.

**Comment by AlJohri** [comment]
Just added a little bit to the bounty. Thanks for working on this!

**Comment by shazow** [comment]
@AlJohri Thanks! If you'd like to get involved, pulling the code mention above and providing feedback would be most helpful. :)

**Comment by AlJohri** [comment]
I'll try to give it a shot in the near future, this is definitely a feature I'd want to invest in. I see that @lorien tried the branch and got some errors? #692

**Comment by lorien** [comment]
Hey guys, I've added +$50 for this bounty. Please, anybody, make socks support :)

**Comment by shazow** [comment]
Thanks for everyone providing bounties. I set [a goal for $1200](https://www.bountysource.com/issues/25474088-preliminary-socks-proxy-support), if it breaks that then I'll give it a shot myself. :)

**Comment by Lukasa** [comment]
Ok, so I'm planning to move this forward myself now. I've got some initial work in #762, and I'm going to try to press this forwards over the next few days to try to get this ready.

**Comment by kislyuk** [comment]
:+1: :shipit:

**Comment by cattleyavns** [comment]
Love you so much, Lukasa! ~~~♥

**Comment by shazow** [comment]
Hey everyone, @Lukasa is making great progress in #762. Please take a look and provide last-minute feedback before we merge. :)

**Comment by shazow** [comment]
Alright, it's merged into master, will be included in the next release (v1.14) some weeks later. Big thanks to @Lukasa!

**Comment by Lukasa** [comment]
\o/ :sparkles: :custard: :cake: :cookie:

**Comment by JeremyRand** [comment]
Awesome work @Lukasa , thank you for getting this done!  I will approve the collection of the bounty as soon as BountySource tech support gets back to me on why I don't see a button for doing so.  (I just sent them an email; my guess is that they'll get back to me on Monday.)  Cheers!

**Comment by JeremyRand** [comment]
BountySource hasn't yet gotten back to me; I assume this is because they've been away for holidays.  Hopefully they'll figure out why I don't see the approve button soon; if not, it looks like the bounty will be automatically awarded on Jan 2.

**Comment by Ofekmeister** [comment]
So, is SOCKS fully supported now? HTTPS, IPv6, etc.? If so, does anyone know how soon it will be incorporated in the Requests library?

**Comment by Lukasa** [comment]
@Ofekmeister HTTPS is fully supported. IPv6 is not, due to limitations in PySocks, but relatively little work is required to add that support and no changes need to be made in urllib3 to take advantage of it.
