### ISSUE TITLE
PyOpenSSL support doesn't work with TLSv1.1 and TLSv1.2

### ISSUE THREAD

**Issue by itamarst** [shazow/urllib3#695]
`docker-py` tries to use latest protocol version in the ssl module, so use ssl.PROTOCOL_TLSv1_2. Unfortunately urllib3.contrib.pyopenssl only has SSLv2_3 and TLSv1 so it breaks:

https://github.com/shazow/urllib3/blob/master/urllib3/contrib/pyopenssl.py#L68

**Comment by Lukasa** [comment]
Seems like a good idea to me. =)

**Comment by Lukasa** [comment]
To be clear this should be an extremely simple fix: conditionally attempt to use the TLSv1_1 and TLSv1_2 names, and if they exist then add them to the versions map.  This is a great 'first contribution' task.

**Comment by shazow** [comment]
+1, @itamarst would you like to do a PR for this?

**Comment by itamarst** [comment]
Might have a few free minutes at work tomorrow, maybe.
