### ISSUE TITLE
Cannot connect to "https://cdn01.boxcdn.net/_assets/img/not_found_box_logo-Czx5Gh.png"

### ISSUE THREAD

**Issue by cattleyavns** [shazow/urllib3#698]
My code:

'''
import urllib3
p = urllib3.PoolManager()
p.urlopen('GET', 'https://cdn01.boxcdn.net/_assets/img/not_found_box_logo-Czx5Gh.png')
print(p.data)
'''

My Python console never return me anything, this is Python itself or urllib3 problem ? If this is a Python problem then I think it should be fixed as soon as possible.

**Comment by Lukasa** [comment]
You say it doesn't return anything: what does it do? Does the program finish executing? Does it hang forever? Does it print an error?

**Comment by shazow** [comment]
In your code, p is the pool, not the response. You want to do something like this:

```python
import urllib3
http = urllib3.PoolManager()
resp = http.request('GET', 'https://cdn01.boxcdn.net/_assets/img/not_found_box_logo-Czx5Gh.png')
print(resp.data)
```

In the future, please ask these kinds of questions on StackOverflow. :)

**Comment by cattleyavns** [comment]
@Lukasa, @shazow: It hangs forever.., even with shazow's code:

'''import urllib3
http = urllib3.PoolManager()
resp = http.request('GET', 'https://cdn01.boxcdn.net/_assets/img/not_found_box_logo-Czx5Gh.png')
print(resp.data)
'''
Screenshot: http://i.imgur.com/O4BVTrs.png
Nothing happened after a very long time, but it works with other url really fine. For example:

'''import urllib3
http = urllib3.PoolManager()
resp = http.request('GET', 'https://dropbox.net')
print(resp.data)
'''

Screenshot: http://i.imgur.com/7FXqoHj.png

I think this is a bug. And sorry, I mistyped my 1st post.

**Comment by shazow** [comment]
It works for me. Sounds like their servers are throttling your IP. Try it from another connection? Also you can set a timeout so that it won't hang forever.

**Comment by cattleyavns** [comment]
@shazow: You are right, they somehow prevent me from loading that url, I hide my IP with Tor then everything become okay.

This thread can now rest in peace. Thanks.
