### ISSUE TITLE
Add a way to check if number of bytes received matches declared transfer length(s)

### ISSUE THREAD

**Issue by causton81** [shazow/urllib3#723]
This discussion originated on python requests (https://github.com/kennethreitz/requests/pull/2833). Basically, there are edge cases where a socket can appear to have closed normally (end-of-file) but was actually reset before sending/receiving all of a response. This may happen silently without raising any exceptions from urllib3.

A suggestion was made to allow users to enable a "strict transfer-length" check in urllib3. For what it's worth RFC2616 (http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4) describes when Content-Length should be used by servers. It seems like the chunked logic is probably safe from this, but probably want to confirm that too.

When I get a chance I'll try to submit a PR for comment.

**Comment by shazow** [comment]
Thanks for transferring the discussion over!

Definitely open to suggestions/proposals to this. I wonder if we could keep this at a relatively higher-level abstraction, like an attribute on RequestMethods and an extra check before returning something.

**Comment by Lukasa** [comment]
Keeping it high level sounds sensible. An extra check should be easy enough, especially as the underlying httplib object actually has exactly the attribute we want (`HTTPResponse.length`, for those interested, indicates how much data remains from the Content-Length header).

**Comment by nateprewitt** [comment]
Hey @Lukasa, I've been playing around with this and `urllib3.response.HTTPResponse` doesn't directly have a `length` attribute. You can access the attr on `HTTPResponse.original_response` but that isn't populated if the `original_response` wasn't from httplib.

Would we want to move the `length` attr up to `response.HTTPResponse`, populating it if it exists on the `original_response`, or computing the value if it doesn't? If not, perhaps it would be better to always compute it and not rely on `length` at all?

**Comment by Lukasa** [comment]
I'm open to always computing it.

**Comment by nateprewitt** [comment]
I believe that this can be closed now that #949 has been merged.
