### ISSUE TITLE
bug: timeout cause connection stay at FIN_WAIT2

### ISSUE THREAD

**Issue by cloudfly** [shazow/urllib3#732]
test code:  https://gist.github.com/cloudfly/a2b781fa1c9e70190707

If server-side is a long-polling action, can not response immediately.

this code will generate lots of `FIN_WAIT2` tcp connection

```
tcp        0      0 192.168.77.10:55785     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55750     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55781     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55776     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55769     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55788     192.168.77.1:8080       ESTABLISHED 27252/python
tcp        0      0 192.168.77.10:55757     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55779     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55774     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55743     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55768     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55762     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55771     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55741     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55783     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55759     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55748     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55751     192.168.77.1:8080       FIN_WAIT2   -
tcp        0      0 192.168.77.10:55746     192.168.77.1:8080       FIN_WAIT2   -
```

**Comment by Lukasa** [comment]
@cloudfly Why are you calling methods on the HTTPConnection objects directly? It's not a surprise your sample code doesn't work: urllib3 doesn't ever touch the connection object beyond line 6, that's just all pure `httplib` code. If you change line one of your code to `from httplib import HTTPConnection`, everything would basically work exactly the same.

This is not a urllib3 bug, I'm afraid, sorry.

**Comment by cloudfly** [comment]
Thanks @Lukasa . But I suffer a problem when I using `PoolManager`. can you help me to check this test code:

```python
def httplib_test2():
    pool = PoolManager(10)
    while True:
        try:
            resp =pool.request("GET", "http://192.168.77.1:8080/", timeout=1, preload_content=False)
            print resp.data
        except Exception as e:
            print e
        time.sleep(1)
```
this code also cause lots of `FIN_WAIT2` tcp connection(if server-side not response immediately). anywhere unproper?

**Comment by Lukasa** [comment]
No, this code is correct. What exception are you hitting?

**Comment by cloudfly** [comment]
As expected, this code will print Read timed out exception.  but also make lots of `FIN_WAIT2` tcp connections. 

I run a test server on my own server, which sleep hours for every request.

you can replace `http://192.168.77.1:8080/` to `http://121.41.118.21:4444/`. 

 then `netstat -ntp | grep 4444` will find the `FIN_WAIT2` connection is increasing every second.

 thank you every much.
