### ISSUE TITLE
Warn if we do not have access to SNI

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#753]
Suggested in kennethreitz/requests#2910. This would make it easier for people to correlate unexpected cert verification failures with the specific action they need to take.

**Comment by shazow** [comment]
+1 to more descriptive errors, ideally it should only affect when there is no SNI and SNI is required for the request to succeed.

**Comment by Lukasa** [comment]
Well, we can't really tell when SNI is required for the request to succeed, only when it's *likely* to be needed. In that case, I think warning once, on the first HTTPS request, on a platform that has no SNI is likely to be the way to go here.

**Comment by shazow** [comment]
I mean what about raising the warning only if the HTTPS request fails? (ie. before re-raising the exception).

**Comment by Lukasa** [comment]
The problem there is that kennethreitz/requests#2910 was actually caused by the request *succeeding* when it should have failed. We wouldn't have helped the user at all if we only raised the warning on failure.
