### ISSUE TITLE
Must remove square brackets from IPv6 addresses when using match_hostname

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#760]
Spotted in [OpenStack](https://bugs.launchpad.net/nova/+bug/1526413). Introduced by my fix #708.

Apparently, while `httplib` itself doesn't care about the square brackets, the `match_hostname` function needs them gone. I suggest we move the stripping down into our `ssl.py` module.

**Comment by mriedem** [comment]
This is the openstack bug, FYI: https://bugs.launchpad.net/nova/+bug/1526413

**Comment by sigmavirus24** [comment]
@Lukasa seems to be working on this so I'm labelling it in progress and assigning him :-P

**Comment by Lukasa** [comment]
Ok, fix has landed.
