### ISSUE TITLE
InsecurePlatformWarning can maybe be fixed by updating ndg-httpsclient?

### ISSUE THREAD

**Issue by wolfgang42** [shazow/urllib3#764]
The [documentation for InsecurePlatformWarning](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) suggests that to fix InsecurePlatformWarning messages you must either upgrade Python or use PyOpenSSL.

However, following the instructions on [this StackOverflow post](http://stackoverflow.com/a/29501899/1979340) I fixed the warning by simply upgrading `ndg-httpsclient`:
```sh
pip install --upgrade ndg-httpsclient
```

Is there a reason this (much simpler, IMHO) solution isn't in the documentation?

**Comment by shazow** [comment]
ndg-httpsclient is mentioned here: https://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl

But you're right, we should at least include the --upgrade flag in that example. Would you like to send a PR that makes our docs better?
