### ISSUE TITLE
connection_from_url  hangup forever in proxy environment

### ISSUE THREAD

**Issue by Fei-Guang** [shazow/urllib3#771]
$env | grep proxy
http_proxy=http://proxy.com:8080
$curl --head http://tunein.com/ | head -n 1
HTTP/1.1 200 OK

urllib2 works well but urllib3 hang up at connect forever

>>> import urllib3
>>> print urllib3.__version__
1.14
>>>conn = urllib3.connection_from_url('http://tunein.com/')
>>>r = conn.request('GET', '/')
it hang up forever

>>> import urllib2
>>> print urllib2.__version__
2.7
>>> response = urllib2.urlopen('http://tunein.com/')
>>>

**Comment by Lukasa** [comment]
urllib3 does not automatically discover your proxies, you need to tell it where they are. You could use requests, which does this, or you can be explicit about the proxies with urllib3 should use, [like this](http://urllib3.readthedocs.org/en/latest/#proxymanager).
