### ISSUE TITLE
SOCKS example code from wiki fail to run

### ISSUE THREAD

**Issue by cattleyavns** [shazow/urllib3#777]
Hi!
I took code from here: https://urllib3.readthedocs.org/en/latest/contrib.html#socks

And here is my result: http://prntscr.com/9njs5b

I'm using Windows 7, Python 3.5, urllib3 newest version.

**Comment by Lukasa** [comment]
That error looks like your PySocks is too old. What version do you have installed?

**Comment by cattleyavns** [comment]
Thanks very much, so problem is my pySocks is too old. Sorry for this inconvenient :)
