### ISSUE TITLE
Some HTTPS website cannot load without changing ssl_version

### ISSUE THREAD

**Issue by cattleyavns** [shazow/urllib3#778]
Some websites:

1. Default http://prntscr.com/9njwan FAIL | Override ssl_version to 'SSLv3' http://prntscr.com/9njwxr SUCCESS
2. Default http://prntscr.com/9njxdb FAIL | Override ssl_version to 'TLSv1' http://prntscr.com/9njxv5 SUCCESS
3. Default http://prntscr.com/9njzow FAIL | Override ssl_version to 'SSLv3' http://prntscr.com/9nk02x SUCCESS

So i doubt this is a bug because I think urllib3 should automatically detect exact ssl version to use or i should detect website's ssl version myself ? And how to do that ? Thank!

My web browsers like Firefox, IE, Chrome can load those websites without any problem, so I think this is a bug.

**Comment by Lukasa** [comment]
@cattleyavns Can you explain what happens when that code fails?

**Comment by cattleyavns** [comment]
Hi Lukasa, if this code fail then simply the page will never load, it stuck like in my images forever.

**Comment by Lukasa** [comment]
What's the timeout? I found for all three of those that the page *did* load, though it took a while.

**Comment by cattleyavns** [comment]
I didn't set a timeout in those tests, but it will stuck like that forever in my system (a fresh and newly reinstalled Windows 7 system)

If I set a timeout, Python interpreter will pop this popup: http://prntscr.com/9nl4eh

**Comment by Lukasa** [comment]
Sorry, I was unclear. Your terminal seems to say "Remote Interpreter Reinitialized". Did you do that manually, or did that happen after some length of time? After how long did that message appear?

**Comment by cattleyavns** [comment]
>> Your terminal seems to say "Remote Interpreter Reinitialized". Did you do that manually, or did that happen after some length of time? 

I press "Ctrl + F2" to force my Python Interpreter restart because it will stuck like that forever (or maybe about 1-2 hours ?) if no timeout was set.

>> After how long did that message appear?
It is weird that I set timeout to 10.0, but it actually take more than 10 second.

**Comment by Lukasa** [comment]
So how long did you wait before hitting Ctrl + F2?

**Comment by cattleyavns** [comment]
I wait randomly, but about 1-2 minutes, sometimes I leave my Python Interpreter alone but when i come back it still stuck like that if i didn't set a timeout.

But if i set ssl_version, the code show page source instantly

**Comment by Lukasa** [comment]
Ok, can you run this for me and tell me the result?

```python
import ssl
print(ssl.OPENSSL_VERSION)
```

**Comment by cattleyavns** [comment]
Here is my video: https://www.dropbox.com/s/rrv7kvqv3zj6ird/problem.mp4?dl=0

**Comment by cattleyavns** [comment]
>> Ok, can you run this for me and tell me the result?

My output:

'''
>>> import ssl
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 1.0.2d 9 Jul 2015
'''

**Comment by Lukasa** [comment]
@cattleyavns Are you familiar with using Wireshark? Would you be able to make a capture file of the connection for me?

**Comment by cattleyavns** [comment]
I think I can, just wait me a few minutes

**Comment by cattleyavns** [comment]
Hi Lukasa, here is my capture file, a FAIL and a SUCCESS:

FAIL https://www.dropbox.com/s/rmic84papk2s7r7/FAIL.pcapng?dl=0
SUCCESS https://www.dropbox.com/s/def6dk5c7an8zyq/SUCCESS.pcapng?dl=0

Hope this will be useful

**Comment by Lukasa** [comment]
Based on these capture files this server is just thoroughly misbehaving. In the TLSv1.2 case it is getting partway through the handshake and then just stopping for *no good reason*, hanging forever.

This is doubly perplexing because the connection works *fine* from my machine, using the exact same code. I compared the TLS handshakes, and the Client Hello (the only TLS message emitted by your machine before the connection falls over) send by your machine and the one sent by mine are *byte for byte identical* except for the random seed in them. Because that can't be relevant (if it were, your failure would be intermittent), I can only assume you have a middlebox somewhere in the network path from you that is doing some weird DPI of TLS handshakes and drops the packets.

The way your browser solves this is by attempting handshakes and falling back to older TLS versions if those handshakes fail. I don't urllib3 should automatically do that, because it represents a passive security risk: attackers attempting MITM attacks on urllib3 could simply kill the TCP connections in flight and force urllib3 to downgrade. I think in this case there's nothing we can do: you'll just need to discover what versions you can safely use and use those.

@shazow, do you disagree with my reasoning for not writing code for TLS fallback?

**Comment by cattleyavns** [comment]
Thank you very much for explaining that clear, but I think in my case, downgrade SSL version automatically is the best way because I use urllib3 to write a local proxy to debug my HTTP/HTTPS packet, but this problem happen a lot so I think better to do downgrade SSL version automatically than nothing.

Can you give me some idea, what should I modify, what kind of "try: except:" should I catch to have that feature, in proxy server environment I don't think it will be harmful, because other local proxy server like HandyCache, Proxydomo already ignored that problem.

**Comment by Lukasa** [comment]
Unfortunately, at least in the case of the first example, you'd have to catch the timeout. The reality is that TLS connections can fail in lots of different ways, and that will raise lots of different exceptions.

One thing we might want to consider is whether urllib3 could provide a richer Retry API that will let users adjust certain request parameters before retrying. Unfortunately, if we did that it would still take a while to appear.

Sadly, in the short term I think that means you'll basically have to catch nearly any exception urllib3 throws that suggests data may not have been received. You can reduce the scope a little bit by setting `preload_content=False` and then getting the data afterwards, which will mean the try...except should only affect the connection attempt.

**Comment by cattleyavns** [comment]
But it is weird that ssl module can get SSL information from those website without any problem.

```
import socket
import ssl
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
ssl_sock = ssl.wrap_socket(s)
ssl_sock.connect(('vozforums.com', 443))
print (repr(ssl_sock.getpeername()))
print (ssl_sock.cipher())
```

This code works very well, but problem is if I can get SSL information using .wrap_socket then .connect, then how to do the last but most important step is get the best ssl_version to use with PoolManager(ssl_version=ssl_version_from_the_step_above)

**Comment by Lukasa** [comment]
The problem here is that we configure a very strict TLS configuration. The reality is that it's hard to probe this from the outside.

**Comment by cattleyavns** [comment]
Hi Lukasa, I want to extend this thread because I found if I do 'ssl.wrap_socket' with urllib3.HTTPSConnectionPools._new_conn, my problem solved, I could connect to those websites.
I modified connectionpool.py, add:

```import ssl```
and modify:

```    def _new_conn(self):
        """
        Return a fresh :class:`httplib.HTTPSConnection`.
        """
        self.num_connections += 1
        log.info("Starting new HTTPS connection (%d): %s",
                 self.num_connections, self.host)

        if not self.ConnectionCls or self.ConnectionCls is DummyConnection:
            raise SSLError("Can't connect to HTTPS URL because the SSL "
                           "module is not available.")

        actual_host = self.host
        actual_port = self.port
        if self.proxy is not None:
            actual_host = self.proxy.host
            actual_port = self.proxy.port
        
        conn = self.ConnectionCls(host=actual_host, port=actual_port,
                                  timeout=self.timeout.connect_timeout,
                                  strict=self.strict, **self.conn_kw)
        sock = socket.create_connection((str(actual_host), int(actual_port)))
        conn.sock = ssl.wrap_socket(sock)

        return self._prepare_conn(conn)```

I know it is weird but somehow it worked (if I revert connectionpool.py to its original state then I cannot connect to those website in my first post in this thread): http://prntscr.com/9y2j4q

**Comment by Lukasa** [comment]
@cattleyavns The call to `wrap_socket` that you've made there does not apply any of our settings, and so that doesn't really tell you enough to know what the problem is. What you need to do is incrementally apply the settings from urllib3 to see which one causes your server to complain.

**Comment by sigmavirus24** [comment]
@cattleyavns that call also doesn't actually do any verification of the connection so it isn't actually secure because you aren't guaranteed to be talking to the server you think you are. You're just establishing a TLS connection with a server on a port. You're not verifying that the server returns a certificate you're expecting.
