### ISSUE TITLE
assert_hostname and assert_fingerprint attempting to .strip() boolean values in recent version

### ISSUE THREAD

**Issue by bpicolo** [shazow/urllib3#780]
Commit that looks to have caused issue (for hostname at least):
https://github.com/shazow/urllib3/commit/cc2d86fc13688e573721ee7a7571cb5315ef2017#diff-ba7cb8edcbac0c25e81c20eba663f317

self.assert_hostname (in addition to self.assert_fingerprint) are booleans. This raises an exception

Edit: Then again, let me make sure this is actually the intended use... I may be wrong and elasticsearch-py docs / urllib3 docs just aren't entirely clear as to what these attempt to do

**Comment by bpicolo** [comment]
Closing this, it seems this was mostly just a mixup of documentation on my part. Weird that these didn't actually fail hostname verification being passed bools before...

**Comment by shazow** [comment]
If you have any ideas for improving our docs, PRs for that are super welcome. :)
