### ISSUE TITLE
Drop Python 3.2 support?

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#786]
Noticed in #785 that virtualenv/pip no longer support Py32, so our travis is going to break if we continue to use them.

Anyone object to dropping Python 3.2 support from our test matrix and README? (Anywhere else?)

Here's some download counts of urllib3 by Python version from the last couple of days via @dstufft: 
<img width="149" alt="screen-shot-2016-01-19-20-53-44" src="https://cloud.githubusercontent.com/assets/6292/12437830/2f936bc8-bed6-11e5-95e2-cd8234e72fa1.png">

**Comment by dstufft** [comment]
![notearsonlydreams](https://cloud.githubusercontent.com/assets/145979/12437924/1fe30d04-bef0-11e5-843b-2eda5a6d3faf.png)

**Comment by sigmavirus24** [comment]
I'm :+1: on this.

**Comment by shazow** [comment]
![img_6974](https://cloud.githubusercontent.com/assets/6292/12438008/c894a430-bed7-11e5-8d1f-fba0c0d2842a.JPG)

**Comment by Lukasa** [comment]
Python 3.2 is over. Let's give it the dignified retirement it deserves. I'll prepare a PR to do the honours.
