### ISSUE TITLE
Add PyOpenSSL tests to the regular test runs.

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#791]
I've just noticed that, while we have tests that can run under PyOpenSSL, they don't run either under tox or Travis. I suggest that we promote those tests up to be full parts of our test suite, especially as PyOpenSSL can be critically important for some features.

While we're there, we should add `TestSSL` to the import from `test_socketlevel`, as the `SSL` tests are probably a good thing to have run under PyOpenSSL as well!

This will give us a hook for writing tests that only run under PyOpenSSL and the expectation that they will actually run on multiple platforms.

**Comment by Lukasa** [comment]
I just noticed that our PyOpenSSL compatibility layer doesn't get tested under Python 3. It turns out that this is because our PyOpenSSL compatibility layer literally doesn't support Python 3.

It's a bit mind-boggling that we've never noticed this fact before. Regardless, we should...probably fix that.

**Comment by shazow** [comment]
Great idea.

**Comment by caizixian** [comment]
Lack of PyOpenSSL support causes malfunction in requests under Python 3

https://github.com/kennethreitz/requests/issues/3006
