### ISSUE TITLE
Connection pool queue can still be exhausted by gevent timeouts

### ISSUE THREAD

**Issue by ml31415** [shazow/urllib3#805]
A similar error was discussed here https://github.com/shazow/urllib3/issues/644 already and some fix applied, but the problem still partly exists. Consider this code:

```python
from gevent import monkey, spawn, sleep, Timeout, joinall
monkey.patch_all()

import sys
from itertools import product
from urllib3.connectionpool import HTTPConnectionPool

def timed_read(cp, i, timeout, release=None, preload_content=True):
    try:
        with Timeout(timeout):
            resp = cp.urlopen('GET', 'http://httpbin.org/redirect/:1',
                              release_conn=release,
                              preload_content=preload)
            print "%s opened" % i
            sys.stdout.flush()
            data = resp.data
    except Timeout:
        print "%s timed out" % i
    else:
        content_len = int(resp.headers['content-length'])
        if len(data) != content_len:
            print "%s incomplete read: %s/%s" % (i, len(data), content_len)
        else:
            print "%s finished" % i
    sys.stdout.flush()


def main(timeout=10, release=None, preload=True, poolsize=2):
    print '-' * 10 + "  timeout=%s preload=%s release=%s " % (timeout, preload, release) + '-' * 10
    cp = HTTPConnectionPool('httpbin.org', block=True, maxsize=poolsize, timeout=None)
    group = []
    for i in range(3):
        group.append(spawn(timed_read, cp, i, timeout, release=release, preload_content=preload))
    joinall(group)

    current_size = cp.pool.qsize()
    if current_size != poolsize:
        print "poolsize decreased: %s" % current_size


for timeout, preload in product([10, 4, 0.1], [True, False]):
    main(timeout=timeout, preload=preload)
```

Setting a timeout that way may seem stupid, as it could be set on the connection itself, but it's just an example for having a timeout running on a longer running task including several calls into the connection pool. What happens is, that the connections are not properly returned back into the queue, and the queue finally runs empty, and any further call to it blocks forever:

<pre>
----------  timeout=10 preload=True release=None ----------
1 opened
1 finished
0 opened
0 finished
2 opened
2 finished
----------  timeout=10 preload=False release=None ----------
0 opened
0 finished
1 opened
1 finished
2 opened
2 finished
----------  timeout=4 preload=True release=None ----------
1 opened
1 finished
0 timed out
2 timed out
----------  timeout=4 preload=False release=None ----------
1 opened
1 finished
0 opened
0 finished
2 timed out
poolsize decreased: 1
----------  timeout=0.1 preload=True release=None ----------
0 timed out
1 timed out
2 timed out
----------  timeout=0.1 preload=False release=None ----------
0 timed out
1 timed out
2 timed out
poolsize decreased: 0
</pre>

Simply setting `preload_content` to `True` is not an option, as e.g. `False` is set by default by requests.

The main problem is in https://github.com/shazow/urllib3/blob/master/urllib3/response.py#L246 . The `Timeout` does not derive from `Exception`, so `self._original_response` is not closed in the except clause, and therefore the connection is not released in the finally clause.

**Comment by Lukasa** [comment]
Urgh, so `gevent.Timeout` is an instance of `BaseException`, which is pretty annoying. I understand why they did it (didn't want overbroad `except` clauses preventing the timeout from firing), but it leads to awkward problems like these.

The simplest way to do this might be just to broaden *our* `except` clause. Because there's no way we can swallow the exception inside our `except` block, we may want to write `except BaseException` instead and then comment why we did it.

Of course, this is a fairly nonsensical arms race, so the other option is to have an `else` clause that sets a boolean on clean exit, and if that boolean isn't present have the `finally` clause close and dispose of the connection. That would move almost all the error handling into `finally`, so it'd be fairly bloody similar to the current code, but might appease those who object to overbroad `except` blocks.

@shazow, I'm happy to do the legwork to fix this: do you have a preference as to how?

**Comment by shazow** [comment]
@Lukasa Yea I think a cleanup boolean + finally is the way to go for complex cleanups based on how the rest of our code has been evolving.

**Comment by ml31415** [comment]
Looks good to me.

**Comment by shazow** [comment]
@ml31415 Should be fixed in master, can you confirm? (Let's re-open if it's still an issue.)

**Comment by ml31415** [comment]
Hmmm, unfortunately it looks like  it's still there. Looks like i overlooked something initially :/

<pre>
----------  timeout=0.1 preload=False release=None ----------
0 timed out
1 timed out
2 timed out
poolsize decreased: 0
</pre>

**Comment by ml31415** [comment]
Though I think the changes in #805 are the right thing to do.

**Comment by shazow** [comment]
Yea we're keeping the changes, just removing the changelog entry that says it fixes a gevent thing since it's not fixed. :)

**Comment by Lukasa** [comment]
@ml31415 Do we have a shorter repro scenario than the one above? Ideally one it's not a problem for me to run locally?

**Comment by ml31415** [comment]
Hmm, not shorter, but at least local:

```python
from gevent import monkey, spawn, sleep, Timeout, joinall
from gevent.server import StreamServer
monkey.patch_all()

import sys
from itertools import product
from urllib3.connectionpool import HTTPConnectionPool


RESPONSE = """
HTTP/1.1 200 OK
Server: gevent
Content-Type: text/html; charset=windows-1251
Content-Encoding: identity
Content-Length: 10

asdfasdf

""".lstrip().replace('\n', '\r\n')
# Do not remove the final empty line!


class RawServer(object):
    def __init__(self, response, host='127.0.0.1'):
        self.response = response
        self.server = StreamServer((host, 0), self.handler)

    def handler(self, sock, addr):
        sleep(1)
        sock.sendall(self.response)

    @property
    def url(self):
        return 'http://%s:%s' % self.server.address

    def __enter__(self):
        self.server.start()
        return self

    def __exit__(self, *args, **kwargs):
        self.server.stop()


def timed_read(cp, i, timeout, host, port, release=None, preload_content=True):
    try:
        with Timeout(timeout):
            resp = cp.urlopen('GET', 'http://%s:%s' % (host, port),
                              release_conn=release,
                              preload_content=preload)
            print "%s opened" % i
            data = resp.data
    except Timeout:
        print "%s timed out" % i
    else:
        print "%s finished" % i


def main(timeout=10, release=None, preload=True, poolsize=2):
    with RawServer(RESPONSE) as s:
        host, port = s.server.address
        cp = HTTPConnectionPool(*s.server.address, block=True, maxsize=poolsize, timeout=None)
        print '-' * 10 + "  timeout=%s preload=%s release=%s " % (timeout, preload, release) + '-' * 10
        group = []
        for i in range(3):
            group.append(spawn(timed_read, cp, i, timeout, host, port, release=release, preload_content=preload))
        joinall(group)

    current_size = cp.pool.qsize()
    if current_size != poolsize:
        print "poolsize decreased: %s" % current_size


for timeout, preload in product([2, 0.1], [True, False]):
    main(timeout=timeout, preload=preload)
```

I'll try to get the whole thing more spot on than this.

**Comment by ml31415** [comment]
There is another scenario, that guaratees an exhausted pool, when the greenlet / thread fails, before the response is read (the timeout stuff is only there, so it doesn't block eternally on the empty loop):

```python
def timed_read(cp, i, timeout, host, port, release=None, preload_content=True):
    try:
        with Timeout(timeout):
            resp = cp.urlopen('GET', 'http://%s:%s' % (host, port),
                              release_conn=release,
                              preload_content=preload)
            print "%s opened" % i
            1 / 0
            data = resp.data
    except Timeout:
        print "%s timed out" % i
    except ZeroDivisionError:
        print "%s intentionally failed" % i
    else:
        print "%s finished" % i
```
I guess the best solution to this would be, if the response supports the with protocol, so we could do smth like:

```python

with cp.urlopen('asdf.org') as resp:
    1 / 0
    resp.data
´´´
And it still cleans itself up afterwards.

**Comment by ml31415** [comment]
Shorter test version:
```python
def test_response_closed():
    class Raiser(object):
        def read(self):
            raise Timeout()

    with RawServer(RESPONSE) as s:
        cp = HTTPConnectionPool(*s.server.address)
        resp = cp.urlopen('GET', s.url, preload_content=False)
        resp._fp = Raiser()
        try:
            resp.data
        except Timeout:
            print "timed out"
        assert resp._connection is None
        assert resp._original_response.isclosed()

```

**Comment by Lukasa** [comment]
@ml31415 Just to be clear, are you testing with the master branch? For me, the master branch passes your smaller test.

```
gevent==1.0.2
greenlet==0.4.9
-e git+git@github.com:Lukasa/urllib3.git@3ecc0cee79971e9cae9412266e07001c7922104b#egg=urllib3
wheel==0.26.0
```

**Comment by ml31415** [comment]
Hmm, yes the smaller test runs now, yes. Still the other one doesn't. And I actually don't really understand how it still fails :(

**Comment by Lukasa** [comment]
Ok, so the reason you're still seeing this problem is that, in basically all these cases the timeout is *actually* occurring in the connection handling code. This is not covered by the fix in the #806, because I didn't touch that other block there. I think it likely needs a similar change.

The change for that block is going to be a bit trickier in part because that block *already* has a condition variable for releasing the connection, and even worse, that condition variable is passed *into* the function (so I can't default it to something that will behave sensibly).

This is definitely fix-able, though it's going to be a bit frustrating to have two connection-close metavariables.

**Comment by Lukasa** [comment]
See #807 for a proposed fix.

**Comment by ml31415** [comment]
Guys, you're awesome! Thanks for fixing this that quickly!

**Comment by ml31415** [comment]
Hmm, maybe I should have started this in a separate issue. It got lost somewhat here. There is still a scenario for leaking connections, already mentioned above. It's when a thread opens a response, but then dies or finishes, before reading from it. E.g. it could die while doing some header parsing:

```python
def timed_read(cp, i, timeout, host, port, release=None, preload_content=True):
    resp = cp.urlopen('GET', 'http://%s:%s' % (host, port),
                      release_conn=release,
                      preload_content=preload)
    print "%s opened" % i
    resp.headers['asdfasdf']
    data = resp.data # Never read, never released
```
And there again is the deadlock on opening connection nr 2:
<pre>
----------  timeout=5 preload=False release=None ----------
1 opened
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "Schreibtisch/demo3.py", line 47, in timed_read
    resp.headers['asdfasdf']
  File "/usr/local/lib/python2.7/dist-packages/urllib3/_collections.py", line 151, in __getitem__
    val = self._container[key.lower()]
KeyError: 'asdfasdf'
<Greenlet at 0x7fe42a5f8e10: timed_read(<urllib3.connectionpool.HTTPConnectionPool object , 1, 5, '127.0.0.1', 40303, release=None, preload_content=False)> failed with KeyError

0 opened
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "Schreibtisch/demo3.py", line 47, in timed_read
    resp.headers['asdfasdf']
  File "/usr/local/lib/python2.7/dist-packages/urllib3/_collections.py", line 151, in __getitem__
    val = self._container[key.lower()]
KeyError: 'asdfasdf'
<Greenlet at 0x7fe42a5f8c30: timed_read(<urllib3.connectionpool.HTTPConnectionPool object , 0, 5, '127.0.0.1', 40303, release=None, preload_content=False)> failed with KeyError
</pre>

I already had suggested to support the with syntax for the response object. What do you think about it?

**Comment by Lukasa** [comment]
I think supporting the `with` syntax makes sense here.

My general position is that we're never going to be able to prevent users from leaking connections in their code: if they try hard enough they'll be able to do that. However, the corollary to that is that we should give users as many tools as possible to avoid leaking connections, and a `with` statement is one of them.

Can we open a separate issue for the `with` statement? I'd like to try to keep issues scoped tightly, especially when they get referenced in code comments. =)

**Comment by ml31415** [comment]
Sure, I'll open it.

**Comment by Lukasa** [comment]
Thanks @ml31415, you've been very helpful through all of this!
