### ISSUE TITLE
installing urllib3[secure] into a virtualenv breaks pip

### ISSUE THREAD

**Issue by ydgholz** [shazow/urllib3#811]
I created a virtualenv, activated it, and ran `pip install urllib3[secure]`. Every subsequent call to `pip` then fails:

```
$ pip install argparse
Downloading/unpacking argparse
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement argparse
Cleaning up...
No distributions at all found for argparse
Storing debug log for failure in /nail/home/dgholz/.pip/pip.log
```

I checked `https://pypi.simple.org`. and it seems that the certificate has a common name of '`www.python.org`', which doesn't match the host name '`pypi.python.org`'.

**Comment by shazow** [comment]
This might be more relevant to open in the pip repo? @dstufft any idea what's going on?

**Comment by sigmavirus24** [comment]
On March 3, 2016 7:38:12 PM CST, Andrey Petrov <notifications@github.com> wrote:
>This might be more relevant to open in the pip repo? @dstufft any idea
>what's going on?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/shazow/urllib3/issues/811#issuecomment-192050526

I wonder if we could find out what operating system this is happening on and how pip was installed. I suspect pip was installed with system packages. I don't know why the packages we need to enable SNI would cause pypi's certificate to fail verification when it otherwise works fine.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lukasa** [comment]
This is almost always exactly what happens when virtualenv and pip are installed via system packages on a system like ubuntu 14.04. This leads to a pip inside the virtualenv that is un-bundled, which means that updating urllib3 breaks pip. There is no other way updating urllib3 *can* break pip, because normally pip carries its own copy of urllib3.

@ydgholz You'll need to destroy this virtualenv and get a copy of virtualenv that does not install the system `pip` into the virtual environment. You can obtain one by removing the virtualenv you got from your system package manager and `pip install`ing one instead.

**Comment by shazow** [comment]
@ydgholz Please let us know if that doesn't solve your problem. Closing for now.

Might be nice to have this Q&A on stackoverflow or something.

**Comment by ydgholz** [comment]
Solves my problem, I created a docker & installed everything _just so_, and pip was able to install things fine after `pip install urllib3[secure]`.

**Comment by ifrh** [comment]
I face a somhow equal problem: I am doing some kind of "software archeology". 
In my setting I have multiple micromamba environments (for different Python versions one env). 
All of those micromamba envs "living" inside a docker container. 
Suddenly (perhaps the components of the docker base image had been changed - docker build runs more or less every week) in my case one of twenty enviroments has "broken" pip-functionality after installing urllib3[secure].

If I use pip to deinstall the package pyOpenSSL, which had been installed as dependency with `urllib3[secure]`, 
than pip could do its job again.

I hope my question is interesting enough that someone here will be able to give me an expert answer and I can learn something.

How do I resolve this runtime error comming inside a micromamba environment for an old tool [without upgrading to newer Python-Version] ?.

I asked yesterday in the neighborhood : 
- https://github.com/pyca/pyopenssl/issues/1503 


Error message of pip in my case is in this environment is the information:  
> "it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time".
Complete message see below.

Forcing the same error without calling pip is possible:

```
python -c "import urllib3.contrib.pyopenssl; urllib3.contrib.pyopenssl.inject_into_urllib3(); import urllib3; urllib3.PoolManager().request(\"GET\", 'https://example.com/')"  
```

No problem was using urllib:
```
python -c "import ssl; import urllib.request; context = ssl.create_default_context(); response = urllib.request.urlopen('https://example.com/', context=context)"
```
```
Collecting coverage
ERROR: Exception:
Traceback (most recent call last):
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
[...]
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/pip/_internal/download.py", line 439, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
[...]
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/pip/_vendor/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
[...]
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 283, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 412, in verify_mode
    _verify_callback
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/OpenSSL/SSL.py", line 1119, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/home/user/micromamba/envs/d20py34/lib/python3.4/site-packages/OpenSSL/SSL.py", line 338, in __init__
    "int (*)(int, X509_STORE_CTX *)", wrapper)
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
```

**Comment by ifrh** [comment]
> How do I resolve this runtime error comming inside a micromamba environment for an old tool [without upgrading to newer Python-Version] ?.

Just for record:
ReInstalling inside the micromamba environment libffi fixed that problem.
`micromamba install libffi=3.3`
` + libffi            3.3  he6710b0_2  anaconda          55kB`

Somehow libffi was updated to 3.4.8. ...
