### ISSUE TITLE
parse_url fails when given credentials in the URL with '/', '#', or '?'

### ISSUE THREAD

**Issue by haikuginger** [shazow/urllib3#814]
Technically, this behavior is compliant with RFC-3986 in that the "authority" section should end at the next instance of one of those characters. However, RFC-2617, which specifies the HTTP Basic Auth scheme, does not specifically exclude those characters as valid, which means that there are valid RFC-2617 usernames and passwords which cannot currently be transmitted inside the URL for handling.

This behavior has received an issue filing on pip in the context of an HTTP proxy.

The attached pull request changes behavior such that any authorization information (separated from the rest of the URL by the reserved character '@') is pulled from the URL prior to scanning for the end of the authority section (separated from the rest of the URL by the aforementioned reserved characters). The PR also includes regression tests to ensure that this behavior change stays in place.

Sources:
https://github.com/pypa/pip/issues/3267
http://tools.ietf.org/html/rfc3986#section-3.2
https://tools.ietf.org/html/rfc2617#section-2

**Comment by sigmavirus24** [comment]
The RFC says specifically:

```
The authority component is preceded by a double slash ("//") and is
terminated by the next slash ("/"), question mark ("?"), or number
sign ("#") character, or by the end of the URI.
```

In other words, the current behaviour is correct in expecting the authority to be terminated by the first `/` (or `?` or `#`) it finds after the preceeding `//`. Am I sympathetic to people trying to use proxy URIs with pip? Absolutely. I think hacking together something that violates the RFC has the potential for nasty surprises later on.

**Comment by haikuginger** [comment]
Closing, as it sounds like this is not something that can be parsed out of the URL in a standards-compliant manner.

**Comment by shazow** [comment]
@haikuginger Thanks for giving it a shot! :)
