### ISSUE TITLE
Honor PYTHONWARNINGS for SNIMissingWarning

### ISSUE THREAD

**Issue by vincent-legoll** [shazow/urllib3#816]
.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

I'm not here to discuss the validity of those warnings, but when I tried to get rid of them with the PYTHONWARNINGS environment variable, it only works for the InsecurePlatformWarning one. The other is always displayed whatever I put in PYTHONWARNINGS.

Please advise what PYTHONWARNINGS value to use to get rid of this one, this is a documented python feature: 
https://docs.python.org/2/library/warnings.html
https://docs.python.org/2/using/cmdline.html?highlight=pythonwarnings#envvar-PYTHONWARNINGS

Also seen the same problem here: in https://github.com/shazow/urllib3/issues/497

Thanks

**Comment by Lukasa** [comment]
Arg, yes, good spot. Want to try the patch from #817 to see if that solves your problem?

**Comment by vincent-legoll** [comment]
I've not tried the patch file per se, but redid the same modification in place, and it worked. Thanks.
