### ISSUE TITLE
Cannot run tests on Ubuntu 14.04 LTS + Python 3

### ISSUE THREAD

**Issue by davidfstr** [shazow/urllib3#822]
#### Repro Steps

```
# (Install Docker from: http://www.docker.com )

# If OS X, start with:
$ docker-machine start default; eval "$(docker-machine env default)"

# If OS X or Linux, continue with:
$ docker run -it ubuntu:trusty  # Ubuntu 14.04 LTS
$$ apt-get update
$$ apt-get install git -y
$$ apt-get install python3-pip -y
$$ pip3 install virtualenv
$$ git clone https://github.com/shazow/urllib3
$$ cd urllib3/
$$ virtualenv venv
$$ source venv/bin/activate
$$ make test
```

#### Output

```
python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    long_description=open('README.rst').read() + '\n\n' + open('CHANGES.rst').read(),
  File "/urllib3/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 4597: ordinal not in range(128)
make: *** [*.egg-info] Error 1
```

#### Notes

My best guess is that the `read()`s in setup.py should have an encoding specified. Probably UTF-8.

**Comment by davidfstr** [comment]
Likely fix that works on Python 2 and 3: `io.open('README.rst', encoding='utf8')`

**Comment by davidfstr** [comment]
Oh you support Python 2.6 too. Here's a more-compatible version: `codecs.open('README.rst', encoding='utf8')`

**Comment by shazow** [comment]
Hm strange, can't reproduce the error on Python 3.5. Does changing it to `u'\n\n'` help at all?

```diff
- long_description=open('README.rst').read() + '\n\n' + open('CHANGES.rst').read(),
+ long_description=open('README.rst').read() + u'\n\n' + open('CHANGES.rst').read(),
```

**Comment by Lukasa** [comment]
This is *almost certainly* a locale problem. We can resolve it in one of two ways:

- we could purge all non-acsii characters from the changelog and readme and keep them purged
- we can just use the change to `codecs` to ensure that they're always opened and decoded as UTF-8.

I feel like the second one is the best approach.

**Comment by haikuginger** [comment]
I can reproduce with `export LC_ALL=C` on Ubuntu 14.04. If it's all right, I can have a PR ready in a bit.

**Comment by Lukasa** [comment]
I'm happy to review.
