### ISSUE TITLE
ImportModule error ngd-httpsclient

### ISSUE THREAD

**Issue by james-hoegerl** [shazow/urllib3#826]
Using AWS Lambda to send push notifications to Pusher app in Python. When I install Pusher and all its dependencies to a directory and zip up to Lambda I run a simple test and get this error.

`No module named ndg.httpsclient.ssl_peer_verification`
Here is the code I'm trying to run.

```
    from pusher import Pusher

    pusher = Pusher(app_id=u'id', key=u'key', secret=u'secret')

    def createPitchZip(context, event):

        pusher.trigger('testchannel', 'testevent', {u'some': u'data'})
```

I've seen several posts about this but installing the dependencies individually doesn't seem to be helping.

Here is the stack trace

```
Traceback (most recent call last):
    File "pusherlambda.py", line 2, in <module> 
         pusher = Pusher(app_id=u'*****', key=*****', secret=u'****')
    File "/home/vagrant/Code/Lamdba/venv/lib/python2.7/site-packages/pusher/pusher.py", line 42, in __init__
         from pusher.requests import RequestsBackend
    File "/home/vagrant/Code/Lamdba/venv/lib/python2.7/site-packages/pusher/requests.py", line 12, in <module>
        import urllib3.contrib.pyopenssl
    File "/home/vagrant/Code/Lamdba/venv/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
        from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
ImportError: No module named ndg.httpsclient.ssl_peer_verification
```

Went from pusher repo issue to requests repo issue and the sent me over this way. Banging my head off the wall for this one. Any help would be appreciated.

**Comment by sigmavirus24** [comment]
Closing this to just talk on the requests issue.
