### ISSUE TITLE
PoolManagers are overly case-sensitive.

### ISSUE THREAD

**Issue by Lukasa** [shazow/urllib3#833]
In a URI, both scheme and authority are case-insensitive: that is, the scheme, host, and port should all be considered case insensitively (and basically treated as lower-case).

Unfortunately, the PoolManager and ProxyManager do not consistently do that. The biggest problem is in the ProxyManager, where `connection_from_host` will incorrectly treat any HTTPS scheme with a capital letter in it like a HTTP connection (which isn't great), but the flaw is pretty common elsewhere in those objects (e.g. an uppercased host will get a different connection pool to a lowercased host).

At the very minimum we should be using a lowercased scheme at all points in the urllib3 stack. We should also consider whether we want to be case-sensitive about domains (I'm inclined to say that we do not).

Related: kennethreitz/requests#3075.

**Comment by shazow** [comment]
+1, we should build this behaviour into our new PoolKey namedtuples somehow. Maybe we need a duck interface that returns normalized tuple values given some request context. Like:

```python
pool_key = pool_key_cls.from_request(request_content)  # Or some better method name
```

Then we can build in the lower-casing normalizing logic into the pool_key_cls as-needed.

**Comment by Lukasa** [comment]
I'm not entirely sure that's enough, but to be fair I'm not sat down with the code right now so I can't be sure.
