### ISSUE TITLE
Some HTTPS URLs fail to download with "sslv3 alert handshake failure"

### ISSUE THREAD

**Issue by davidfstr** [shazow/urllib3#837]
### Environment

* urllib 1.15
* Python 3.4.0rc1
* OS X 10.11.3 (15D21) - El Capitan

### Repro Steps

```
>>> import urllib3
>>> urllib3.__version__
'1.15'
>>> url = 'https://files.yande.re/sample/02a50945798910f0f13dcab3123e698b/yande.re%20351635%20sample%20bou_nin%20kimono%20landscape%20umbrella.jpg'
>>> http = urllib3.PoolManager()
>>> response = http.request(method='GET', url=url)
```

### Expected Results

No exception. Binary contents of URL available in `response.data`.

### Actual Results

Following exceptions thrown:

* ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:598)
* urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:598)

Full traceback at: <https://gist.github.com/davidfstr/9ec1db7dfd1ce5fd3565d88ece4b7e6b>

### Notes

I think I remember stumbling across a similar issue in the past. As I recall it was related to an SSL library on OS X being an outdated version, or similar.

**Comment by Lukasa** [comment]
The SSL version on OS X is OpenSSL version 0.9.8zh, which is so incorrigibly ancient as to be useless. In particular, it misses support for a lot of modern cipher suites and protocols. You should be able to resolve this problem by installing urllib3 using `pip install urllib3[secure]`, and then beginning your program with `import urllib3.contrib.pyopenssl; urllib3.contrib.pyopenssl.inject_into_urllib3()`.

Alternatively, if that is too much work, you can install an updated version of OpenSSL and Python from Homebrew, which will also avoid this issue.
