### ISSUE TITLE
urllib3 attempts to use IPv6 even when IPv6 is disabled

### ISSUE THREAD

**Issue by kz26** [shazow/urllib3#838]
This is an issue when running on a server without IPv6 (must be disabled because the network does not support it). Example when connecting to https://graph.facebook.com using requests and IPv4 happens to fail:

```
HTTPSConnectionPool(host='graph.facebook.com', port=443): Max retries exceeded with url: /v2.5/me/feed (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4dbd158518>: Failed to establish a new connection: [Errno 97] Address family not supported by protocol',))
Traceback (most recent call last):
  File "/home/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/home/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 71, in create_connection
    sock = socket.socket(af, socktype, proto)
  File "/usr/lib/python3.4/socket.py", line 126, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

urllib3 should throw an exception after exhausting all IPv4 options instead of trying (and invariably failing) IPv6.

See closed issue https://github.com/kennethreitz/requests/issues/3084.

**Comment by haikuginger** [comment]
PR opened to handle suppressing IPv6 DNS results when IPv6 isn't available. I think that suppressing exceptions until we've tried all the DNS entries available is the correct behavior in general; we can't know if we "really can't" establish a connection until we've tried all the options, at which point there's not a good way to tell which exception is the "correct" one to raise.
