### ISSUE TITLE
Should reset connection pools after fork

### ISSUE THREAD

**Issue by tesseract2048** [shazow/urllib3#850]
Consider this scenario:

process A creates a connection pool and send a request to `url0`, and then fork twice. Then we got process B & C.
process B and C then send another request to `url0` at nearly the same moment, then the underlying connection they used would be the identical one, causing confused response.

**Comment by Lukasa** [comment]
@tesseract2048 Yes, connection pools should be reset after forking, but I don't believe that urllib3 should be doing it.

This has been discussed elsewhere, but generally speaking we don't know the user's intent: do they want only the child to own the connections, or only the parent? IMO, if a user is going to fork, they should be maintaining discipline over their own state, and should clear the connection pools from whichever process they want to no longer have access to them.

**Comment by shazow** [comment]
Right. I'm open to proposals that can reliably detect and warn (or even reset) when a fork happened, but that's borderline out of scope as urllib3 does not have any multiprocess-safe mechanics (we're merely threadsafe).

@tesseract2048 I'm closing this issue for now, but if you'd like to submit a PR to this effect I welcome it. :)

I would also appreciate any recipes you'd like to add to our documentation about how to use urllib3 properly in a multiprocess environment. This would be ideal, I think.

**Comment by tesseract2048** [comment]
Thanks for response, @Lukasa @shazow .

I think adding description to the effect to document helps little because users may be just simply combining two libraries (i.e. python-requests and multi process thrift server), so connection polling and fork are done separately. Maybe they are not even aware of these implementation details before things actually break (and probably break with little chance and hard to repeat).

What do you say, if letting user specify whether they want to keep connections alive after fork (reset by default)? We could use POSIX calls such as `pthread_atfork` to detect a fork then handle the situation properly.

**Comment by shazow** [comment]
@tesseract2048 Does that work on every platform (win/linux/mac/etc) without edge cases? I suspect it would be safer to provide a multi-process recipe in the docs than try to detect it automagically.

**Comment by Lukasa** [comment]
As far as I know `pthread_atfork` isn't exposed by Python by default, so we'd need to add a dep to make that call.

**Comment by tesseract2048** [comment]
Hi, @shazow @Lukasa . I cannot come up with any edge cases now but there could be many.
Another simpler idea would be associating a `pid` to each connection pool object, each process then checks its owner pid with associated pid (before using) to decide what to do. Does this sound portable?
We can introduce the mechanism and keep current behavior by default, then let other libraries to decide the policy.

**Comment by shazow** [comment]
At what point does the pool check the pid? What happens if a fork happens mid-use?

**Comment by tesseract2048** [comment]
For example: 
Before obtaining connection, check stored pid. If it's different from current pid, run these `atfork` policies. Then and set pid to current one.

If fork happens mid-use, and we are giving user two choices: after fork, either keep connections or get rid of all of them, cases are:
A. if there are no inflight request in any living connection, everything is fine.
B. if user chooses not to preserve connections after fork (e.g. keep these connections to parent process), and there are one or more requests inflight, we can still detect the fork and get rid of these connections by closing them (closing file descriptor instead of socket). Process that sent these requests are still able to receive further responses.
C. if user chooses to preserve connections after fork, and there are one or more requests inflight, the thread that waiting for response are generally not preserved after fork (one thread cannot doing both forking and blocking i/o at the same time), so if things like gevent is not used, child process will 'forget' about these requests. Parent are still able to receive further responses. In this case, as long as child process issues new request after these responses arrives, everything is fine. Otherwise, there could be a problem. However, it is not worse than current situation. It is user's choice to keep these connections.

**Comment by Lukasa** [comment]
> if there are no inflight request in any living connection, everything is fine.

That's not true at all: we pool the connections. If there are no in-flight requests we still need to iterate over the pool and clear it.

> and there are one or more requests inflight

The problem here is that we don't really know if requests are in-flight: the prior contract of urllib3 is that once we've grabbed a connection from the pool it's the property of the caller until they hand it back to us. We really shouldn't be tearing down connections under their feet.

That said, there shouldn't be any requests in-flight in the sense you mention it in part 3, because threading and forking are generally not mixed (though if there are we're in trouble, because we'll leak the connections from the pool).

**Comment by tesseract2048** [comment]
Yes. By `everything is fine` I mean in this case it's trivial to clear the connection pool if necessary.

IMO it is simpler if it is caller's responsibility to return the connection, since there are no edge cases about in-flight requests: if one grab a connection, send the request, then before receiving response, another thread called `fork`, that connection will not be visible to children process. I won't consider it as leak because eventually the connection will be returned to parent process.

**Comment by shazow** [comment]
@tesseract2048 How do you feel about adding something like this to our docs instead?

> ## How to use urllib3 in a multi-process environment?
> Make sure to fork _before_ using your urllib3 pools and everything will be good. Resources cannot be shared between processes, and behaviour of pre-used pools after forking to a new process is undefined.

Seems like less work and should satisfy the reasonably tiny subset of our users who rely on this functionality. :)

**Comment by tesseract2048** [comment]
@shazow That makes sense. 
Thanks.

**Comment by shazow** [comment]
@tesseract2048 Would you like to submit a PR to add this to our docs?

**Comment by tesseract2048** [comment]
Sure, @shazow.
I'll submit a PR in a couple of days.

**Comment by rabbbit** [comment]
For completeness, this has bitten me severely when using Requests and Celery. 

I've raised https://github.com/requests/requests/issues/4323 to discuss.

**Comment by geogeim** [comment]
hey, i'm facing this issue, i'm using a library that uses urllib3 internally, could you please show me how can i reset the connection pools after fork?
