### ISSUE TITLE
urllib3 1.15.1 does not provide the extra 'socks'

### ISSUE THREAD

**Issue by kevinoid** [shazow/urllib3#863]
When installing urllib3 using `pip` according to the instructions on the [Contrib Modules](https://urllib3.readthedocs.io/en/latest/contrib.html#socks) page, the following messages are produced:

    $ pip install -U urllib3[socks]
    Collecting urllib3[socks]
      Using cached urllib3-1.15.1-py2.py3-none-any.whl
      urllib3 1.15.1 does not provide the extra 'socks'
    Installing collected packages: urllib3
    Successfully installed urllib3

And the `PySocks` package is not installed, resulting in the following error on import:

    $ python -c 'from urllib3.contrib.socks import SOCKSProxyManager'
    /home/user/.local/lib/python2.7/site-packages/urllib3/contrib/socks.py:31: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.org/en/latest/contrib.html#socks-proxies
      DependencyWarning
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/.local/lib/python2.7/site-packages/urllib3/contrib/socks.py", line 21, in <module>
        import socks
    ImportError: No module named socks

This occurs with both Python 2.7 and 3.5.  It appears to be similar to #684 which was resolved by adding `metadata` to `setup.cfg` in #706.  Perhaps a similar fix for `socks` is needed?

Thanks,
Kevin

**Comment by haikuginger** [comment]
This sounds right to me; it looks like `provides-extra` in `setup.cfg` might be overriding the extras listed in `setup.py`.

**Comment by Lukasa** [comment]
Agh, this is my bad: good catch folks! Python packaging still biting me in the ass.

**Comment by shazow** [comment]
Wonder if we can make somekind of integration tests for packaging, but maybe not worth the effort.

**Comment by haikuginger** [comment]
Not sure! Packaging is somewhat of a mystery to me.

**Comment by kevinoid** [comment]
Great!  Thanks for the very quick fix!
