### ISSUE TITLE
Github: Protected branches?

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#865]
Do we want to enable protected branches? If so, for which? (master/release?)

**Comment by Lukasa** [comment]
While the number of people who have merge permissions on this repo is kinda small and they have pretty major respect for the integrity of the master/release branches. *However*, I also think it's generally good practice: while that's true now it may not be true later, and the overhead of turning them on is relatively low.

TL;DR: Do it, for master and all the release branches.

**Comment by sigmavirus24** [comment]
I'm also 👍 on turning these on.

**Comment by shazow** [comment]
Also FYI I added @haikuginger as a collaborator on the repo because he wants to be more involved and has been doing great work. :)

**Comment by shazow** [comment]
Ok, master and release are protected now, master requires travis passing to merge.

**Comment by Lukasa** [comment]
Welcome to the team @haikuginger! :sparkles: :custard:

**Comment by haikuginger** [comment]
Thanks, @shazow, @Lukasa!

**Comment by shazow** [comment]
FYI also added @dstufft as a collaborator on the repo as pip is one of our primary "customers" that we target features for. Feel free to cc him for relevant code reviews and whatnot.
