### ISSUE TITLE
Release v1.16 (and maybe v1.17)

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#870]
Current plan is to cut the existing changelist for v1.16 and cut v1.17 shortly after with just #835 and #849.

FYI I'm kinda scrambling to get my PyCon talk ready for next week so this maneuver might have to wait a bit longer unless anyone is hurting. :x

**Comment by haikuginger** [comment]
I'm 👍 on all counts. No rush, though; enjoy PyCon!

**Comment by Lukasa** [comment]
I think there's no immediate rush on this: worst case we can just grab some coffee and YOLO the release out at PyCon. =D

**Comment by shazow** [comment]
Sorry been swamped with stuff and I'm on the road right now, SOON!

**Comment by shazow** [comment]
Can I yolo-change `preload_content=False` default for v1.17? Is this going to cause a lot of regret?

**Comment by haikuginger** [comment]
I'd be 👍 on that - I'd rather have it in with other possibly-breaking changes than on its own.

**Comment by Lukasa** [comment]
@shazow YOLO away.

**Comment by shazow** [comment]
v1.16 has been cut and released, kinda afraid of v1.17.

**Comment by haikuginger** [comment]
🍪!

**Comment by Lukasa** [comment]
I believe in v1.17!

**Comment by shazow** [comment]
Bunch of tests fail if I just yolochange `preload_content=False` so I'm going to put it off for now. Maybe we should start a sessionmanager branch with all the breaking things we'd like to include in it, and start merging PRs into there.

Also, if we want to add more automagic sessionmanager features (auto-ssl, auto-appengine, or whatever else wanted to include), should we try to fit those in before releasing to avoid breaking again later?

**Comment by haikuginger** [comment]
Maybe those don't go into SessionManager, but we do those for the `.request()` method in #868?

**Comment by Lukasa** [comment]
Let's not forget about #835!!!

**Comment by haikuginger** [comment]
Yes, #835!

**Comment by shazow** [comment]
> Maybe those don't go into SessionManager, but we do those for the `.request()` method in #868?

1. I think that's too complicated to fit into a stand-alone global function
2. I want people to be able to create instances of this, too.

Basically we need SessionManager to know about a bunch of auto-configuration features that can be disabled as-desired. In fact, opening an issue for supporting disabling cookies.

**Comment by shazow** [comment]
How do we feel about a persistent branch that we can merge all of these PRs into right now and rebase off that for upcoming stuff until we're ready vs doing the v1.17 thing? (Also any volunteers? :P)

**Comment by haikuginger** [comment]
I guess with SessionManager being my baby, so to speak, I'm volunteering.

I'll need a good rundown of all the breaking features we want to stick in this bad boy. So far, here's what I'm thinking:

- [ ] #885 - params/form_fields arguments
- [ ] #888 - Cookie disabling
- [ ] #835 - SSL Context/autocreation of same for secure sessions by default
- [ ] (No ticket yet) - SessionManager extension for sending HTTP basic auth to particular domain

What else is there? I want to get a good list of what the release goals are first.

I will obviously need some assistance here, especially from @sigmavirus24 and @Lukasa on the SSL-related item(s).

**Comment by Lukasa** [comment]
I think this set is mostly fine. I'm happy to help out with #835.

**Comment by Lukasa** [comment]
Uh....so I shipped these releases already.
