### ISSUE TITLE
unhandled exception when creating new Retry object

### ISSUE THREAD

**Issue by alanhamlett** [shazow/urllib3#871]
```python
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "urllib3/util/retry.py", line 285, in increment
    _observed_errors=_observed_errors)
  File "urllib3/util/retry.py", line 151, in new
    raise_on_status=self.raise_on_status,
AttributeError: 'Retry' object has no attribute 'raise_on_status'
```

You can reproduce this by changing line 140 of `urllib3/connection.py` to:
```
140         try:
141             raise SocketTimeout('')
142             conn = connection.create_connection(
143                 (self.host, self.port), self.timeout, **extra_kw)
144
145         except SocketTimeout as e:
```

This forces a `SocketTimeout` and causes the unhandled exception when calling `Retry.new`.

**Comment by Lukasa** [comment]
If I make that change, all I see is a `MaxRetryError`. Can you tell us what version of urllib3 you're using and where you installed it from?

**Comment by alanhamlett** [comment]
I tested using urllib3 v1.15.1 packaged with the current requests release. It doesn't happen when using the latest master of urllib3 with requests so I'll ask them to upgrade urllib3.

**Comment by shazow** [comment]
Thanks @alanhamlett!

**Comment by alanhamlett** [comment]
New issue: kennethreitz/requests#3217
