### ISSUE TITLE
`connectionpool.ConnectionPool.close()` has zero args

### ISSUE THREAD

**Issue by tharvik** [shazow/urllib3#873]
As written [here](https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L93), `close()` do not except any argument. I guess it was meant to have `self` (as overriden in `HTTPConnectionPool`). Or maybe having the `staticmethod` decorator. Or is it some weird corner case to keep compatibility?

**Comment by Lukasa** [comment]
That looks like an error case to me. It doesn't matter, because that method never gets called: it's just used to define the expected interface. But still, it should probably be cleaned up. Want to provide a patch?

**Comment by shazow** [comment]
Fixed now, thank you!
