### ISSUE TITLE
log server / server info on connectionpool

### ISSUE THREAD

**Issue by jvanasco** [shazow/urllib3#881]
The current implementation of connectionpool logs only the "local path" of a url - it does not log the server component.

https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L400-L401

this logging is not useful in multithreaded applications *if* there are as few as 2 concurrent connections. it also becomes increasingly confusing if there are redirects involved.  

logging would be much better if the server were included somewhere on that line.

**Comment by haikuginger** [comment]
This doesn't sound unreasonable to me. It should be a relatively straightforward change to include `self.host` in the debug line, so I think it's more a matter of getting agreement on "should we".

**Comment by shazow** [comment]
That log line has been there since ~2007. When I first wrote it, it was supposed to mimic what you'd see in a webserver log file. Given that a ConnectionPool only services a single host, it didn't make sense to put the host in there.

I'd be open to add more advanced logging into the PoolManager (or SessionManager), though.

**Comment by Lukasa** [comment]
@shazow Other than trying to mimic web server logs is there any reason not to put the host in there? It kinda seems like it's the most natural place for it...

**Comment by jvanasco** [comment]
I understand the need to not break existing code. Perhaps this info could be appended to the line, or there could be an argument/namespace variable to allow toggling between existing and "future" options?

As-is, the line is largely useless when used with concurrent threaded workers.  Logging often looked like this (loosely recreated):

	INFO:Starting new HTTP connection (1): example.com
	INFO:Starting new HTTP connection (1): aaa.example.com
	INFO:Starting new HTTP connection (1): bbb.example.com
	INFO:Starting new HTTP connection (1): ccc.example.com
	INFO:Starting new HTTP connection (1): ddd.example.com
	INFO:Starting new HTTP connection (1): eee.example.com
	DEBUG:"GET /path/1 HTTP/1.1" 404 56286
	DEBUG:"GET /path/2 HTTP/1.1" 404 56286
	DEBUG:"GET /path/3 HTTP/1.1" 404 56286
	DEBUG:"GET /path/4 HTTP/1.1" 404 56286
	DEBUG:"GET /path/5 HTTP/1.1" 404 56286
	INFO:Starting new HTTP connection (1): fff.example.com
	DEBUG:"GET /path/6 HTTP/1.1" 404 56286
	DEBUG:"GET /path/7 HTTP/1.1" 404 56286

That's 7 requests.  Imagine batch-processing in 100 threads :/

Trying to figure out exactly which combination of host and url correspond to a each other and ultimately triggers an exception is not fun. 

I just patched urllib3 to show the full url. 

> Given that a ConnectionPool only services a single host, it didn't make sense to put the host in there.

That makes perfect sense and still holds true in most applications, however the logging loses all utility when deferring work to threads (an, I assume, when using the multiprocessing module).

**Comment by shazow** [comment]
@Lukasa 

> Other than trying to mimic web server logs is there any reason not to put the host in there? It kinda seems like it's the most natural place for it...

No strong reason, aside from the usual fear of breaking someone's code but I'm not super worried about it in this case.

Prepending `host:port` probably makes most sense? So we'll get...

```
INFO:Starting new HTTP connection (1): eee.example.com
DEBUG:eee.example.com:80 "GET /path/1 HTTP/1.1" 404 56286
```

But if we were logging at the PoolManager level, we could dump the entire pool key.

**Comment by haikuginger** [comment]
`PoolManager.urlopen` sounds like a good place to put the domain-aware logging to me.

**Comment by birm** [comment]
We can probably close this issue :)

**Comment by Lukasa** [comment]
Agreed. =)
