### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#884]
Our docs right now are a mishmash of things appended with random pull requests over the years. Would be great to have someone (ahem, @jonparrott kinda just volunteered) go through and re-organize and write some more narratives.

Some tasks:

- [x] Make sure the full TOC is available on the landing page (currently not, ugh! we have a bunch of sections that are effectively hidden.)
- [x] Clean up the landing page to de-emphasize lower-level components and talk about the primary flow more (and make sure examples are as much default-secure as we can).
- [x] Clarify areas of the docs which are higher-level vs lower-level stuff (aka not for beginners). Somekind of colourcoding would be ideal but not sure how easy this would be with Sphinx.
- [x] Reduce emphasis that urllib3 is for "lower level" stuff—it's not *just* for lower-level stuff. This has been scaring some beginners.
- [x] Recipes section for different usecases
  - [x] appengine
  - [x] request with a body/json blob
  - [x] streaming to/from file (e.g. https://stackoverflow.com/questions/27387783/how-to-download-a-file-with-urllib3)
  - [x] custom tls stuff
  - other things?
- [x] Make sure README is reasonably sync'd with what our latest docs say.
- Any other ideas?

**Comment by shazow** [comment]
\*shifty eyes\*

**Comment by haikuginger** [comment]
🤐

**Comment by shazow** [comment]
Just ran into a stackoverflower at PDX and he had some feedback about our docs, added some ideas to the body. Keep em' coming!

**Comment by jonparrott** [comment]
Excellent!

**Comment by jonparrott** [comment]
Proposed new TOC:

1. Homepage (sections, not subpages)
  1. Introduction
  2. Installation
  3. Quick sample
2. User guide (subpages or sections)
  1. Making requests
  1. Response content
  1. Sending request data
  1. Using timeouts
  1. Retrying requests
  1. Errors and Exceptions
3. Advanced usage (subpages or sections)
  1. Streaming
  1. Proxies
  1. Connection pools
  1. SSL
  1. App Engine
3. Reference (autodocs)
4. Contributing

@shazow let me know your thoughts, we can always shift stuff around once the content is written. I can get started soon once you're cool with a TOC.

**Comment by shazow** [comment]
Looks great!

Some thoughts:

- Maybe rename SSL to "Security (TLS and SSL)" for ctrl+f'ing purposes.
- Introduction should include a basic example right off the bat, and quick sample should have a couple more slightly more complicated but very common examples.
- I suppose User Guide is basically a recipe collection, or is that more narrative? For recipes, I'd love to see "Downloading and uploading files" and "Sending and receiving JSON". https://stackoverflow.com/questions/tagged/urllib3 is a good list of questions that often come up.
- Another good recipe would be providing custom retry/redirect logic. (aka turn off our logic, and have a basic example of doing it yourself)
- Another user guide item would be logging. All the kinds of logs we expose, and how to turn them on/off/tweak.
- What line are we drawing between user guide and advanced usage? To me, advanced usage is something that requires overriding or diving into lower-level components. So just connection pools, on that list. As far as advanced usage goes, we could talk about overriding some functionality.

**Comment by jonparrott** [comment]
> Maybe rename SSL to "Security (TLS and SSL)" for ctrl+f'ing purposes.

Split this - there's now a "basic" SSL verification section in the user guide, and we'll have a security section in advance usage for topics such as custom certs and client certs.

> recipe collection, or is that more narrative

It's a narrative recipe guide. :)

I've expanded the subsections for sending/receiving to include the various types.

> Another good recipe would be providing custom retry/redirect logic. (aka turn off our logic, and have a basic example of doing it yourself)

Added.

> Another user guide item would be logging. All the kinds of logs we expose, and how to turn them on/off/tweak.

Added, totally agree.

> What line are we drawing between user guide and advanced usage?

Requests seems to draw the line at basically anything beyond just making a request. I'd say anything that less than 90% of users would need to see. Another way to draw the line is anything that requires more thought than just copy & paste.

**Comment by jonparrott** [comment]
re: the user/advanced divide: we can always move things around. I just need a starting structure so I can start writing.

**Comment by shazow** [comment]
Sounds good. Thank you so much Jon! :)

**Comment by jonparrott** [comment]
Some final questions before I start sending PRs:

1. I'm assuming you're going to prefer smaller PRs, so I'm going to try to break this up into little bits. Which means that some pages will be in a weird state here and there. Do you prefer we start a new branch here (new-docs) and I can submit PRs against that?
2. Are you okay with me changing the sphinx theme?

**Comment by shazow** [comment]
1. Big PR is fine, entirely up to you on how you'd like to iterate. Bonus points if you make me a collaborator on your repo so I can commit to the PR directly with nits rather than bugging you.
2. Sure. :)

**Comment by jonparrott** [comment]
The new docs are merged, but I still need to follow up with two things:

1. Write a section on using client certificates
2. Update the readme/sync the readme with documentation.

**Comment by shazow** [comment]
_\<A wild shazow appears\>_

Hiii, just had a chance to consume the new docs. ❤️ 

Some superquick feedback while trying to answer [this StackOverflow question](https://stackoverflow.com/questions/38410661/python3-urllib3-crawler-cant-limit-max-connections-to-aa-single-domain).

- Would be great to have some examples of how to configure various aspects of PoolManager and ConnectionPools below them (maxsize, block, difference between maxsize and num_pools).
- Since we're probably going to deprecate the `response.data` magic property eventually (in favour for `.read()`), would be good to normalize the docs examples to using `.read()` (unless we're unhappy with `.read()`? then that should be a discussion).

:sparkles: 💨 :sparkles:

**Comment by Lukasa** [comment]
My only note is that I'd want to emphasise `.stream()` as well as `.read()` (because generators are awesome). Otherwise, all good feedback.

**Comment by jonparrott** [comment]
Sounds reasonable. I'll cover that on my next pass through the docs. :)

**Comment by jonparrott** [comment]
So, on second look this isn't very clean:

Current sample:

```python
>>> r = http.request('GET', 'http://httpbin.org/robots.txt')
>>> r.data
b'User-agent: *\nDisallow: /deny\n'
```

If we just switch this to `read()`:

```python
>>> r = http.request('GET', 'http://httpbin.org/robots.txt')
>>> r.read()
b''
```

Empty? *GASP*?!

It's because the content is pre-loaded, so I'd have to make **all** of the samples do:

```python
>>> r = http.request('GET', 'http://httpbin.org/robots.txt', preload_content=False)
>>> r.read()
b'User-agent: *\nDisallow: /deny\n'
```

Do we plant to make `preload_content` be `True` by default? When that happens it makes sense to update the docs?
