### ISSUE TITLE
Socks supports HTTP_NO_TUNNEL, urllib3 doesn't seem to

### ISSUE THREAD

**Issue by birm** [shazow/urllib3#896]
Should urllib3 reflect this in the socks contrib module?

**Comment by Lukasa** [comment]
Hi there!

It's not *immediately* clear how this should work. I've looked around for HTTP_NO_TUNNEL for a while, and ultimately it's not clear to me *at all* what it actually does.

Can I get an explanation of how it's supposed to be used and what effect it has?

**Comment by birm** [comment]
Using http_no_tunnel proxy type doesn't negotiate http, and rewrites headers. There may be other uses, but I think the main one is when a proxy doesn't support connect.

**Comment by Lukasa** [comment]
@birm Right, but I don't understand what that has to do with SOCKS.

SOCKS isn't a HTTP-based connection mechanism, it's its own protocol.

**Comment by birm** [comment]
That's true. I think that it makes more sense to change poolmanager to support this as a scheme, rather than mimic httplib's grouping of a non-socks protocol in the socks module.

**Comment by Lukasa** [comment]
For http, presumably this is no different to accessing a proxy with a `http://` scheme?

**Comment by birm** [comment]
For the most part, except for headers.

**Comment by birm** [comment]
I believe your're right, so long as at no point HTTPConnection.set_tunnel() is called by httplib for http requests, which it doesn't seem to be. Thanks.

**Comment by Lukasa** [comment]
No problem, thanks for tolerating my confusion!

**Comment by shazow** [comment]
@Lukasa Thank you for figuring this out. :)
