### ISSUE TITLE
Announcement: @lukasa is the lead maintainer until further notice

### ISSUE THREAD

**Issue by shazow** [shazow/urllib3#909]
Hi everyone who watches urllib3 issues. 👋 

I'm taking a 3-6mo hiatus from urllib3. That is, if everything is happy at 3mo I will probably continue for 6mo, until January 1, 2017 **[update: continuing further with quarterly evaluations]**. Logistically this means I will mute Github urllib3 notifications and forego day-to-day involvement, but I'm still reachable if there are questions or I can be helpful in specific situations.

@lukasa will be taking on responsibility as lead maintainer for the direction of the project in the duration, he will have access to the pypi package and whatever other administrative things are needed. @sigmavirus24 will also be around to help push things forward.

While I'm at it, I want to thank @haikuginger and @jonparrott for choosing to get involved and taking on a lot of big tasks lately. Also @dstufft for making his feedback available as we dig deeper into designing our higher-level APIs. I'm grateful to have you all as collaborators on the project. ✨ :custard: :sparkles:

I look forward to seeing exciting changes when I'm back, maybe then will be a good time to start a strong sprint towards v2.0!

If anyone has questions or concerns, comments here are welcome or email me. ❤️ 

For reference (mostly my own), @Lukasa has urllib3 admin privileges on the following platforms: Github, PyPi, ReadTheDocs.

**Comment by haikuginger** [comment]
Enjoy the well-earned break!

**Comment by shazow** [comment]
A huge thanks for @Lukasa. Consider yourself honourably discharged! 💜
