### ISSUE TITLE
AttributeError: 'Retry' object has no attribute 'history'

### ISSUE THREAD

**Issue by alanhamlett** [shazow/urllib3#917]
This is related to #871. I'll add a failing test soon to reproduce this bug:

```
Traceback (most recent call last):
  File "requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 403, in send
    timeout=timeout
  File "requests/packages/urllib3/connectionpool.py", line 642, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "requests/packages/urllib3/util/retry.py", line 295, in increment
    history = self.history + (RequestHistory(method, url, error, status, redirect_location),)
AttributeError: 'Retry' object has no attribute 'history'
```

Printing `dir(self)` from `urllib3/util/retry.py` on line 294 gives this output:
`['BACKOFF_MAX', 'DEFAULT', 'DEFAULT_METHOD_WHITELIST', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '    __reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_is_connection_error', '_is_read_error', '_observed_errors', 'backoff_factor', 'connect', 'from_int'    , 'get_backoff_time', 'increment', 'is_exhausted', 'is_forced_retry', 'method_whitelist', 'new', 'raise_on_redirect', 'raise_on_status', 'read', 'redirect', 'sleep', 'status_forcelist', 'total']`

Strangely `history` is not an attribute. Printing `inspect.getfile(self.__class__)` shows the correct retry.pyc file so not sure how the `Retry` class is missing the `history` attribute. When opening the source version of retry.pyc, the `Retry` class has history defined in `__init__`, so I'm stumped.

Even though requests is using an old urllib3 version, the urllib3 above is the current master version.

**Comment by sigmavirus24** [comment]
> Even though requests is using an old urllib3 version, the urllib3 above is the current master version.

This doesn't quite make sense to me. Can you explain this a bit more?

**Comment by Lukasa** [comment]
@sigmavirus24 I suspect that means that the urllib3 in that requests install is the current master version. How have you arranged to do that @alanhamlett?

**Comment by sigmavirus24** [comment]
@Lukasa that's what I would have thought except for the "Even though requests is using an old urllib3 version"

**Comment by haikuginger** [comment]
That's my understanding as well @Lukasa. @sigmavirus24, my guess would be that he means that requests comes stock with an older version of urllib3, which he's replaced with the current master branch of urllib3.

**Comment by alanhamlett** [comment]
@Lukasa is correct, I unzipped the urllib3 package from urllib3-master.zip into `requests/packages`.

**Comment by alanhamlett** [comment]
My bad, requests was passing urllib3 a pickled `Retry` class from a previous urllib3 version.
