### ISSUE TITLE
Doc link for SSL warnings is broken

### ISSUE THREAD

**Issue by rbcarson** [shazow/urllib3#918]
#887 removed docs/security.rst, but it's still referenced as https://urllib3.readthedocs.org/en/latest/security.html in the message for InsecureRequestWarning, InsecurePlatformWarning, and SNIMissingWarning.

For example:

```
requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

```
requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

**Comment by Lukasa** [comment]
Yup, this very much seems like it's worth fixing. Ideally we'd fixup the link: @jonparrott?

**Comment by jonparrott** [comment]
@Lukasa yes, we should fix the URL in the exception itself, but we should also setup a redirect.

You can do so on readthedocs: https://readthedocs.org/dashboard/urllib3/redirects/

We should redirect `/security.html` -> `/advanced-usage.html#ssl-warnings`

**Comment by Lukasa** [comment]
Ok, that's done. Sadly, RTD doesn't behave well redirecting to fragments at this time: see rtfd/readthedocs.org#2287.

**Comment by jonparrott** [comment]
Oh, man, that's lame. Hopefully they can get that fixed without breaking a bunch of other people. :)

**Comment by jonparrott** [comment]
@Lukasa does using an "Exact Redirect" instead of a "Page Redirect" work?

**Comment by Lukasa** [comment]
In principle it could, but I'd like to keep the versioning the same, and exact redirects don't do that.

**Comment by jonparrott** [comment]
Gotcha.
