### ISSUE TITLE
steam(None) can result in an infinite loop

### ISSUE THREAD

**Issue by nateprewitt** [shazow/urllib3#928]
Currently calling `stream(None)` can result in an `HTTPResponse` trying to read a response forever. 

This occurs [here](https://github.com/shazow/urllib3/blob/master/urllib3/response.py#L361-L365) because `is_fp_closed` won't evaluate to `True` in certain cases. The below test provided by @Lukasa shows the issue in our current implementation of `is_fp_closed`. Currently, in Python 3,  `_close_conn` does not call `super().close()`, which means that the `closed` attribute will never be set. We can fix this by checking `isclosed()` first, if it exists, which will appropriately evaluate to True when the contents of the stream have been completely read.

See related discussion in [kennethreitz/requests#3421](https://github.com/kennethreitz/requests/issues/3421)

```python
class TestStream(SocketDummyServerTestCase):
    def test_stream_none_unchunked_response_does_not_hang(self):
        done_event = Event()

        def socket_handler(listener):
            sock = listener.accept()[0]

            buf = b''
            while not buf.endswith(b'\r\n\r\n'):
                buf += sock.recv(65536)

            sock.send(
                b'HTTP/1.1 200 OK\r\n'
                b'Content-Length: 12\r\n'
                b'Content-type: text/plain\r\n'
                b'\r\n'
                b'hello, world'
            )
            done_event.wait(5)
            sock.close()

        self._start_server(socket_handler)
        pool = HTTPConnectionPool(self.host, self.port, retries=False)
        r = pool.request('GET', '/', timeout=1, preload_content=False)

        # Stream should read to the end.
        self.assertEqual([b'hello, world'], list(r.stream(None)))

        done_event.set()
```

**Comment by tobinus** [comment]
Thank you for taking your time to address this, @nateprewitt and @Lukasa! :tada:
