### ISSUE TITLE
The returned code is not complete

### ISSUE THREAD

**Issue by Pikatchu38** [shazow/urllib3#931]
Hello,

I use this code:

```
#!/usr/bin/python3.4
# -*-coding:Utf-8 -*
import certifi
import urllib3
url_microsoft = 'https://support.microsoft.com/fr-fr/help/17780/featured-wallpapers'
http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
conn = http.request('GET', url_microsoft, headers={'User-agent':'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.16 Safari/537.36','Cookie':'cookie_name=cookie_value'})
print(conn.data)
```

The returned code is not complete on this web page.

For example the tag title is empty:
`<title` `ng-bind="title"></title>`

If i use inspector in firebug the tag title is:
`<title` class="ng-binding" ng-bind="title">Sélection de `papiers&nbsp;peints</title>`

All text is empty on this web page.

Is it an issue?

**Comment by Lukasa** [comment]
This is almost certainly because that page loads its data dynamically, using Javascript. urllib3 is just a HTTP client: it cannot execute Javascript. If you need to, you'll need to look into tools like Selenium.
