### ISSUE TITLE
detection of dropped persistent connection fails if server resets connection

### ISSUE THREAD

**Issue by cavedon** [shazow/urllib3#944]
urllib3 automatically reestablishes a connection if the the persistent connections gets closed by the server (normally with a TCP FIN packet):

```
In [11]: http = urllib3.PoolManager()

In [19]: r = http.request('GET', 'http://127.0.0.1', retries=0)
DEBUG:urllib3.connectionpool:"GET / HTTP/1.1" 200 177

In [20]: r = http.request('GET', 'http://127.0.0.1', retries=0)
INFO:urllib3.connectionpool:Resetting dropped connection: 127.0.0.1
DEBUG:urllib3.connectionpool:"GET / HTTP/1.1" 200 177
```

There is a race condition however that leads urllib3 to receive a TCP RST and subsequently raise an exception:
1) we have established persistent connection between urllib3 and a server that already had a few successful requests exchange
2) urllib3 sends a new request
3) the http server decides to expire that connection
4) the kernel of the server received the new request
5) the http server closes the socket
6) the kernel sends out a RST
7) urllib3 raises an exception instead of opening a new connection

The OS of the server sends out a RST (instead of FIN) because there is unread data in the buffer of socket. The data was unread because by the time it was received the http server had already expired the connection, but had not closed the socket yet.

See example here:
```
In [8]: r = http.request('GET', 'http://127.0.0.1:18888', retries=0)
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:urllib3.connectionpool:"GET / HTTP/1.1" 200 3

In [9]: r = http.request('GET', 'http://127.0.0.1:18888', retries=0)
---------------------------------------------------------------------------
MaxRetryError                             Traceback (most recent call last)
<ipython-input-9-e3b5959a51e7> in <module>()
----> 1 r = http.request('GET', 'http://127.0.0.1:18888', retries=0)

/usr/lib/python2.7/dist-packages/urllib3/request.pyc in request(self, method, url, fields, headers, **urlopen_kw)
     72             return self.request_encode_url(method, url, fields=fields,
     73                                            headers=headers,
---> 74                                            **urlopen_kw)
     75         else:
     76             return self.request_encode_body(method, url, fields=fields,

/usr/lib/python2.7/dist-packages/urllib3/request.pyc in request_encode_url(self, method, url, fields, **urlopen_kw)
     85         if fields:
     86             url += '?' + urlencode(fields)
---> 87         return self.urlopen(method, url, **urlopen_kw)
     88 
     89     def request_encode_body(self, method, url, fields=None, headers=None,

/usr/lib/python2.7/dist-packages/urllib3/poolmanager.pyc in urlopen(self, method, url, redirect, **kw)
    153             response = conn.urlopen(method, url, **kw)
    154         else:
--> 155             response = conn.urlopen(method, u.request_uri, **kw)
    156 
    157         redirect_location = redirect and response.get_redirect_location()

/usr/lib/python2.7/dist-packages/urllib3/connectionpool.pyc in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, **response_kw)
    544                     raise ConnectionError('Connection failed.', e)
    545 
--> 546                 raise MaxRetryError(self, url, e)
    547 
    548             # Keep track of the error for the retry warning.

MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=18888): Max retries exceeded with url: / (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)
```

Traffic capture attached: [rst.pcap.zip](https://github.com/shazow/urllib3/files/400697/rst.pcap.zip)

The desired behavior here would be for urllib3 to detect this dropped connection as well, like for the normal case, and to create a new one.

**Comment by Lukasa** [comment]
Thanks for raising this issue!

The problem with detecting this as a dropped connection is that it's very hard to tell the difference between this case and a "forced" RST, where the server decided to have a little temper tantrum and throw a RST packet at us rather than drain the socket.

However, urllib3 does have a builtin resolution method for this if you're happy to use it, and that is [retries](https://urllib3.readthedocs.io/en/latest/user-guide.html#retrying-requests). If you specify a retry count, urllib3 will automatically retry safe request methods. It will still not (by default) retry things like POST or PUT, because those may have had server side-effects that we're not yet aware of, but this gets you 80% of the way there.

Is that helpful?
