### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CERT_CERT_REQUIRED' if 'ssl.py' in project

### ISSUE THREAD

**Issue by Miserlou** [shazow/urllib3#948]
I had a strange error because of the import soup in ssl_.py Reported downstream here: https://github.com/boto/botocore/issues/1007#issuecomment-240184362

@jamesls did the detective work [here](https://github.com/boto/botocore/issues/1007#issuecomment-240184362), but essentially it boils down to that if you have an 'ssl.py' in your project, then this:

```
try:  # Test for SSL features
    import ssl
    from ssl import wrap_socket, CERT_NONE, PROTOCOL_SSLv23
    from ssl import HAS_SNI  # Has SNI?
except ImportError:
    pass
```
will cascade to this:
```
    if isinstance(candidate, str):
        res = getattr(ssl, candidate, None)
        if res is None:
            res = getattr(ssl, 'CERT_' + candidate)
        return res
```
having `res` equal to `CERT_CERT_REQUIRED`, which obviously isn't correct. 

Obviously this isn't a critical problem, but it was pretty cryptic and imagine that there are a fair few projects that use urllib3 which may have an ssl.py who may bump into this, so perhaps you could make this more graceful.

**Comment by Lukasa** [comment]
@Miserlou Thanks for the report!

Generally speaking I'm relatively unsympathetic to this, unfortunately. The same rule applies to any module that shadows a stdlib module's name. Of course, it depends on what urllib3 version you have and how you invoke it: we recently added `from __future__ import absolute_import` which should resolve this problem in most cases.

Regardless, short of decorating *every single* stdlib import to avoid this issue, I don't think there's much more we can do than we have currently done.
