### ISSUE TITLE
Allow IP in addition to (IP, port) tuple for source_address argument

### ISSUE THREAD

**Issue by avamsi** [shazow/urllib3#959]
In [`HTTPConnection`](https://github.com/shazow/urllib3/blob/master/urllib3/connection.py#L67) and [`create_connection`](https://github.com/shazow/urllib3/blob/master/urllib3/util/connection.py#L51) it would be better if `source_address` argument accepts IP address directly in addition to (IP, port) tuple.

Something like
``` python
if not isinstance(source_address, tuple):
    source_address = (source_address, 0)
```

**Comment by Lukasa** [comment]
Thanks for this!

In this instance, we're sticking to the same API as used [by the standard library](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection) to attempt to minimise our divergence from it.

You can get the equivalent behaviour by setting port to `0`.
