### ISSUE TITLE
Urllib3 tries to use socks proxy even when socks proxy is not configured.

### ISSUE THREAD

**Issue by himanshub16** [shazow/urllib3#961]
I have not configured any socks proxy in my environment variables (neither .bashrc, nor /etc/environment). I do have http_proxy and https_proxy set up.
 
Every time I use the requests module, I get an error from urllib3, 
`ValueError: Unable to determine SOCKS version from socks://*****`

Any solution?

**Comment by haikuginger** [comment]
Can you tell us more about your environment? Some example code would be great, as would the version of Requests that you're using. Finally, if you want to do `printenv` in your shell and give us what it returns (obviously removing any sensitive information), that'd be very helpful.

**Comment by Lukasa** [comment]
This is not a urllib3 issue, it's a requests issue. Please open it over there. =)
