### ISSUE TITLE
possible issue with setup.py command

### ISSUE THREAD

**Issue by marcinkuzminski** [shazow/urllib3#997]
We're running our build system via nix, and we generate package data automatically trying to build full dependency tree. Recently our build system broke because of urllib3 updates.

we're receving an error:

` error in urllib3 setup command: Invalid environment marker: python_version <= "2.7"`

I'm not sure if it's our build system or something with a special marker in setup.py

We'll investigate more, however i'm opening this ticket to potentially point out a problem.

**Comment by marcinkuzminski** [comment]
Full trace for reference:

```
Collecting elasticsearch==2.3.0 (from rhodecode-tools==0.10.0->-r ./requirements.txt (line 126))
/home/marcink/.virtualenvs/pip2nix/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached elasticsearch-2.3.0.tar.gz
  Saved /tmp/tmpyB3tycpip2nix/elasticsearch-2.3.0.tar.gz
Collecting elasticsearch-dsl==2.0.0 (from rhodecode-tools==0.10.0->-r ./requirements.txt (line 126))
  Using cached elasticsearch-dsl-2.0.0.tar.gz
  Saved /tmp/tmpyB3tycpip2nix/elasticsearch-dsl-2.0.0.tar.gz
Collecting python-editor>=0.3 (from alembic==0.8.4->-r ./requirements.txt (line 42))
  Using cached python-editor-1.0.1.tar.gz
  Saved /tmp/tmpyB3tycpip2nix/python-editor-1.0.1.tar.gz
Collecting ws4py (from channelstream==0.5.2->-r ./requirements.txt (line 51))
  Using cached ws4py-0.3.5.zip
  Saved /tmp/tmpyB3tycpip2nix/ws4py-0.3.5.zip
Collecting Chameleon>=2.5.1 (from deform==2.0a2->-r ./requirements.txt (line 59))
  Using cached Chameleon-2.25.tar.gz
  Saved /tmp/tmpyB3tycpip2nix/Chameleon-2.25.tar.gz
Collecting peppercorn>=0.3 (from deform==2.0a2->-r ./requirements.txt (line 59))
  Using cached peppercorn-0.5.tar.gz
  Saved /tmp/tmpyB3tycpip2nix/peppercorn-0.5.tar.gz
Collecting urllib3<2.0,>=1.8 (from elasticsearch==2.3.0->rhodecode-tools==0.10.0->-r ./requirements.txt (line 126))
  Using cached urllib3-1.18.tar.gz
  Saved /tmp/tmpyB3tycpip2nix/urllib3-1.18.tar.gz
    Complete output from command python setup.py egg_info:
    error in urllib3 setup command: Invalid environment marker: python_version <= "2.7"
```

**Comment by Lukasa** [comment]
This is going to be the result of your build system. That marker is not understood by older versions of setuptools. You can likely fix it by doing `pip install -U setuptools`. If you'd like to avoid that, I'm planning to push out a new release of urllib3 sometime soon that reverts that specific change.

**Comment by genemat** [comment]
Thank You Lukasa! Had a similar issue as  marcinkuzminski . 

After downloading urllib3, I couldn't run urllib3 setup,  `python2 setup.py install`

Running `pip install -U setuptools` resolved this issue.  urllib3 setup then ran fine, also my other programs dependent on urllib3 also ran fine afterwards.

For reference here is the error message I got from `python setup.py install` before fixing it via `pip install -U setuptools`

`python setup.py install

/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error in urllib3 setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`

**Comment by pquentin** [comment]
Django has an interesting solution here where they're able to give an error message: https://github.com/django/django/blob/master/setup.py
